In [1]:
#import necessary libraries.
import pandas as pd

In [4]:
#Read data from the csv file into the dataframe and set passengerId column s index.
df = pd.read_csv('Titanic-Dataset.csv', index_col='PassengerId')
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [9]:
df.head(10)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [12]:
#df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    object
 3   Sex       891 non-null    object
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    object
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    object
 10  Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 83.5+ KB

In [14]:
df2 = df.drop(columns=['Cabin', 'Embarked'])
df2.head(10)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
PassengerId,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625
8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708

In [32]:
#Check number of unique names
df2['Name'].nunique()

891

In [80]:
#Check whether Survived column contains only 0 or 1.
df2['Survived'].isin([0, 1]).value_counts()

#Checks whether Pclass column contains 1, 2, 3 only.
df2['Pclass'].isin([1, 2, 3]).value_counts()

#Checks whether Sex column contains only male or female.
df2['Sex'].isin(['male', 'female']).value_counts()

#Check whether SibSp column has null values.
df2['SibSp'].isnull().value_counts()

#Checks whether Parch column has null values.
df2['Parch'].isnull().value_counts()

#Checks whether the Fare column has null values.
df2['Fare'].isnull().value_counts()

#Checks whether the Ticket column has null values.
df2['Ticket'].isnull().value_counts()

Ticket
False    891
Name: count, dtype: int64

In [68]:
#Check number of null values in the Age column.
df2['Age'].isnull().value_counts()
df2['Age'].describe()
df2['Age'].mode()

#Fill Null Values of age with mean of all ages
df2['Age'].fillna(df2['Age'].mean(), inplace=True)

#Convert the age from float64 to int32
df2['Age'] =  df2['Age'].astype('int32')

C:\Users\admin\AppData\Local\Temp\ipykernel_36308\2653294242.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Age'].fillna(df2['Age'].mean(), inplace=True)

In [75]:
df2.head(10)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
PassengerId,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500
6,0,3,"Moran, Mr. James",male,29,0,0,330877,8.4583
7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.8625
8,0,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.0750
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27,0,2,347742,11.1333
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14,1,0,237736,30.0708

In [113]:
df2['Ticket'] = df['Ticket']
df2.head(10)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
PassengerId,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500
6,0,3,"Moran, Mr. James",male,29,0,0,330877,8.4583
7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.8625
8,0,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.0750
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27,0,2,347742,11.1333
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14,1,0,237736,30.0708

In [127]:
#Regex to remove the letters and values before the space from the ticket number
df2['Ticket'] = df2['Ticket'].str.replace(r'^\S+\s+', '', regex=True)

In [126]:
df2.head(10)
df2.tail(10)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
PassengerId,,,,,,,,,
882,0,3,"Markun, Mr. Johann",male,33,0,0,349257,7.8958
883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22,0,0,7552,10.5167
884,0,2,"Banfield, Mr. Frederick James",male,28,0,0,34068,10.5000
885,0,3,"Sutehall, Mr. Henry Jr",male,25,0,0,392076,7.0500
886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39,0,5,382652,29.1250
887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.0000
888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29,1,2,6607,23.4500
890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000
891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500

In [158]:
df2[['Surname', 'First_Second_Name']] = df2['Name'].str.strip().str.split(',', n=1, expand=True)
df2.head(10)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Surname,First_Second_Name
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,21171,7.2500,Braund,Mr. Owen Harris
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,17599,71.2833,Cumings,Mrs. John Bradley (Florence Briggs Thayer)
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,3101282,7.9250,Heikkinen,Miss. Laina
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,Futrelle,Mrs. Jacques Heath (Lily May Peel)
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,Allen,Mr. William Henry
6,0,3,"Moran, Mr. James",male,29,0,0,330877,8.4583,Moran,Mr. James
7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.8625,McCarthy,Mr. Timothy J
8,0,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.0750,Palsson,Master. Gosta Leonard
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27,0,2,347742,11.1333,Johnson,Mrs. Oscar W (Elisabeth Vilhelmina Berg)
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14,1,0,237736,30.0708,Nasser,Mrs. Nicholas (Adele Achem)

In [146]:
df2.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare'],
      dtype='object')

In [162]:
df2[['Surname','First_Second_Name']].head(20)

                   Surname                            First_Second_Name
PassengerId
1                   Braund                              Mr. Owen Harris
2                  Cumings   Mrs. John Bradley (Florence Briggs Thayer)
3                Heikkinen                                  Miss. Laina
4                 Futrelle           Mrs. Jacques Heath (Lily May Peel)
5                    Allen                            Mr. William Henry
6                    Moran                                    Mr. James
7                 McCarthy                                Mr. Timothy J
8                  Palsson                        Master. Gosta Leonard
9                  Johnson     Mrs. Oscar W (Elisabeth Vilhelmina Berg)
10                  Nasser                  Mrs. Nicholas (Adele Achem)
11               Sandstrom                         Miss. Marguerite Rut
12                 Bonnell                              Miss. Elizabeth
13             Saundercock                            Mr. William Henry
14               Andersson                             Mr. Anders Johan
15                 Vestrom                  Miss. Hulda Amanda Adolfina
16                 Hewlett                       Mrs. (Mary D Kingcome)
17                    Rice                               Master. Eugene
18                Williams                           Mr. Charles Eugene
19           Vander Planke     Mrs. Julius (Emelia Maria Vandemoortele)
20              Masselmani                                  Mrs. Fatima

In [166]:
df2['First_Second_Name'] = df2['First_Second_Name'].str.replace(r'\s*\(.*\)', '', regex=True)
df2.head(20)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Surname,First_Second_Name
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,21171,7.2500,Braund,Mr. Owen Harris
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,17599,71.2833,Cumings,Mrs. John Bradley
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,3101282,7.9250,Heikkinen,Miss. Laina
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,Futrelle,Mrs. Jacques Heath
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,Allen,Mr. William Henry
6,0,3,"Moran, Mr. James",male,29,0,0,330877,8.4583,Moran,Mr. James
7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.8625,McCarthy,Mr. Timothy J
8,0,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.0750,Palsson,Master. Gosta Leonard
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27,0,2,347742,11.1333,Johnson,Mrs. Oscar W
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14,1,0,237736,30.0708,Nasser,Mrs. Nicholas
11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4,1,1,9549,16.7000,Sandstrom,Miss. Marguerite Rut
12,1,1,"Bonnell, Miss. Elizabeth",female,58,0,0,113783,26.5500,Bonnell,Miss. Elizabeth
13,0,3,"Saundercock, Mr. William Henry",male,20,0,0,2151,8.0500,Saundercock,Mr. William Henry
14,0,3,"Andersson, Mr. Anders Johan",male,39,1,5,347082,31.2750,Andersson,Mr. Anders Johan
15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14,0,0,350406,7.8542,Vestrom,Miss. Hulda Amanda Adolfina
16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55,0,0,248706,16.0000,Hewlett,Mrs.
17,0,3,"Rice, Master. Eugene",male,2,4,1,382652,29.1250,Rice,Master. Eugene
18,1,2,"Williams, Mr. Charles Eugene",male,29,0,0,244373,13.0000,Williams,Mr. Charles Eugene
19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31,1,0,345763,18.0000,Vander Planke,Mrs. Julius
20,1,3,"Masselmani, Mrs. Fatima",female,29,0,0,2649,7.2250,Masselmani,Mrs. Fatima

In [169]:
df2.drop(columns='Name', inplace=True)
df2.to_csv('Cleaned_Titanic_Dataset.csv')