In [30]:
import pandas as pd
pd.set_option('display.max_columns', 500)

### Loading and Understanding the dataset.

In [31]:
healthcare_df = pd.read_excel('../data/raw/Healthcare Dataset.xlsx')
healthcare_df.head(10)

,Location,_Location_latitude,_Location_longitude,_Location_altitude,_Location_precision,Date and Time,Age,Gender,Marital Status,"How many children do you have, if any?",Employment Status,Monthly Household Income,Have you ever had health insurance?,"If yes, which insurance cover?",When was the last time you visited a hospital for medical treatment? (In Months),Did you have health insurance during your last hospital visit?,Have you ever had a routine check-up with a doctor or healthcare provider?,"If you answered yes to the previous question, what time period (in years) do you stay before having your routine check-up?","Have you ever had a cancer screening (e.g. mammogram, colonoscopy, etc.)?","If you answered yes to the previous question, what time period (in years) do you stay before having your Cancer screening?",Your Picture,Your Picture_URL,_id,_uuid,_submission_time,_validation_status,_notes,_status,_submitted_by,__version__,_tags,_index
0,-0.2742007 36.058336 1882.2000732421875 20.0,-0.274201,36.058336,1882.200073,20.000,NaT,41-50,Female,Married,2.0,Self-employed,20001-30000,Yes,Nhif,53.0,No,Yes,2,No,2,NaN,NaN,230162389,aa30304f-84f2-4c1b-b30a-371241f2ff17,2023-04-05 08:44:06,NaN,NaN,submitted_via_web,NaN,vJ8gEKnN2pccxThc5jnkz4,NaN,1
1,-0.7158125 37.1475058 1361.9000244140625 20.0,-0.715812,37.147506,1361.900024,20.000,2023-05-15 13:38:00,18-30,Male,Single,0.0,Unemployed,Less than 10000,No,NaN,8.0,No,Yes,1,No,NaN,NaN,NaN,238299334,63c461e3-b3ef-47cf-9632-0c912a639f46,2023-05-15 10:44:01,NaN,NaN,submitted_via_web,safra_data,vMrCPR7NLZZJrf4PTsQ8uH,NaN,2
2,-0.7158157 37.1475082 1361.9000244140625 20.0,-0.715816,37.147508,1361.900024,20.000,2023-05-15 13:49:00,41-50,Female,Married,5.0,Self-employed,20001-30000,No,Nhif,6.0,Yes,No,NaN,Yes,4+,NaN,NaN,238301092,4209a55d-a983-433f-8ce0-bce6cd28d713,2023-05-15 10:51:08,NaN,NaN,submitted_via_web,safra_data,vMrCPR7NLZZJrf4PTsQ8uH,NaN,3
3,-0.7157082 37.14749 1361.9000244140625 20.0,-0.715708,37.147490,1361.900024,20.000,2023-05-15 14:19:00,18-30,Male,Single,NaN,Self-employed,10001-20000,Yes,Nhif,16.0,Yes,No,NaN,No,NaN,NaN,NaN,238311207,2eba9b13-1706-4faf-b7a7-e45e9dcf48ab,2023-05-15 11:22:19,NaN,NaN,submitted_via_web,safra_data,vMrCPR7NLZZJrf4PTsQ8uH,NaN,4
4,-0.7157337 37.1474799 1361.9000244140625 20.0,-0.715734,37.147480,1361.900024,20.000,2023-05-15 14:30:00,41-50,Male,Married,7.0,Self-employed,20001-30000,Yes,Nhif,13.0,Yes,No,NaN,Yes,4+,NaN,NaN,238314477,1f49cb82-75ff-4391-b69b-973a6ce698ee,2023-05-15 11:33:21,NaN,NaN,submitted_via_web,safra_data,vMrCPR7NLZZJrf4PTsQ8uH,NaN,5
5,-0.7158041 37.1475364 1361.9000244140625 26.107,-0.715804,37.147536,1361.900024,26.107,2023-05-15 14:35:00,18-30,Female,Single,NaN,Unemployed,10001-20000,Yes,Nhif,2.0,Yes,No,NaN,No,NaN,NaN,NaN,238315229,70d15a1e-6a9a-48c8-8e02-c2affb168542,2023-05-15 11:36:52,NaN,NaN,submitted_via_web,safra_data,vMrCPR7NLZZJrf4PTsQ8uH,NaN,6
6,-0.715893 37.1473531 1361.5999755859375 32.483,-0.715893,37.147353,1361.599976,32.483,2023-05-15 14:39:00,31-40,Female,Married,2.0,Self-employed,10001-20000,Yes,Nhif,4.0,Yes,No,NaN,No,NaN,NaN,NaN,238316269,f7b24863-38a7-46c4-a3b8-2b88e95d2204,2023-05-15 11:41:06,NaN,NaN,submitted_via_web,safra_data,vMrCPR7NLZZJrf4PTsQ8uH,NaN,7
7,-0.7159403 37.1463094 1362.2000732421875 56.1,-0.715940,37.146309,1362.200073,56.100,2023-05-15 14:44:00,18-30,Male,Single,NaN,Self-employed,Less than 10000,No,NaN,24.0,No,No,NaN,No,NaN,NaN,NaN,238317405,ff54d156-afd8-4533-8f0a-8760400ab686,2023-05-15 11:45:34,NaN,NaN,submitted_via_web,safra_data,vMrCPR7NLZZJrf4PTsQ8uH,NaN,8
8,-0.7159117 37.1470772 1362.2000732421875 33.011,-0.715912,37.147077,1362.200073,33.011,2023-05-15 14:46:00,31-40,Female,Married,3.0,Employed,20001-30000,Yes,Nhif,5.0,Yes,No,NaN,No,NaN,NaN,NaN,238317928,4df9afd7-5915-4de7-8afb-650c7299494d,2023-05-15 11:47:41,NaN,NaN,submitted_via_web,safra_data,vMrCPR7NLZZJrf4PTsQ8uH,NaN,9
9,-0.7158706 37.1466718 1362.2000732421875 52.4,-0.715871,37.146672,1362.200073,52.400,2023-05-15 14:48:00,31-40,Female,Married,2.0,Employed,10001-20000,Yes,Nhif,6.0,Yes,No,NaN,No,NaN,NaN,NaN,238318482,0c18d7c3-c955-4e2c-889f-33ac23d5d76b,2023-05-15 11:49:41,NaN,NaN,submitted_via_web,safra_data,vMrCPR7NLZZJrf4PTsQ8uH,NaN,10

In [32]:
healthcare_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6158 entries, 0 to 6157
Data columns (total 32 columns):
 #   Column                                                                                                                      Non-Null Count  Dtype
---  ------                                                                                                                      --------------  -----
 0   Location                                                                                                                    5805 non-null   object
 1   _Location_latitude                                                                                                          5805 non-null   float64
 2   _Location_longitude                                                                                                         5805 non-null   float64
 3   _Location_altitude                                                                                                          5805 non-null   float64
 4   _Location_precision                                                                                                         5805 non-null   float64
 5   Date and Time                                                                                                               6010 non-null   datetime64[ns]
 6   Age                                                                                                                         6140 non-null   object
 7   Gender                                                                                                                      6141 non-null   object
 8   Marital Status                                                                                                              6140 non-null   object
 9   How many children do you have, if any?                                                                                      5533 non-null   float64
 10  Employment Status                                                                                                           6134 non-null   object
 11  Monthly Household Income                                                                                                    5899 non-null   object
 12  Have you ever had health insurance?                                                                                         6139 non-null   object
 13  If yes, which insurance cover?                                                                                              3618 non-null   object
 14  When was the last time you visited a hospital for medical treatment? (In Months)                                            6000 non-null   float64
 15  Did you have health insurance during your last hospital visit?                                                              6102 non-null   object
 16  Have you ever had a routine check-up with a doctor or healthcare provider?                                                  6135 non-null   object
 17  If you answered yes to the previous question, what time period (in years) do you stay before having your routine check-up?  1776 non-null   object
 18  Have you ever had a cancer screening (e.g. mammogram, colonoscopy, etc.)?                                                   6127 non-null   object
 19  If you answered yes to the previous question, what time period (in years) do you stay before having your Cancer screening?  1565 non-null   object
 20  Your Picture                                                                                                                0 non-null      float64
 21  Your Picture_URL                                                                                                            0 non-null      float64
 22  _id                                                                                                                         6158 non-null   int64
 23  _uuid                                                                                                                       6158 non-null   object
 24  _submission_time                                                                                                            6158 non-null   datetime64[ns]
 25  _validation_status                                                                                                          0 non-null      float64
 26  _notes                                                                                                                      0 non-null      float64
 27  _status                                                                                                                     6158 non-null   object
 28  _submitted_by                                                                                                               6157 non-null   object
 29  __version__                                                                                                                 6158 non-null   object
 30  _tags                                                                                                                       0 non-null      float64
 31  _index                                                                                                                      6158 non-null   int64
dtypes: datetime64[ns](2), float64(11), int64(2), object(17)
memory usage: 1.5+ MB

In [33]:
healthcare_df.columns

Index(['Location', '_Location_latitude', '_Location_longitude',
       '_Location_altitude', '_Location_precision', 'Date and Time', 'Age',
       'Gender', 'Marital Status', 'How many children do you have, if any?',
       'Employment Status', 'Monthly Household Income',
       'Have you ever had health insurance?', 'If yes, which insurance cover?',
       'When was the last time you visited a hospital for medical treatment? (In Months)',
       'Did you have health insurance during your last hospital visit?',
       'Have you ever had a routine check-up with a doctor or healthcare provider?',
       'If you answered yes to the previous question, what time period (in years) do you stay before having your routine check-up?',
       'Have you ever had a cancer screening (e.g. mammogram, colonoscopy, etc.)?',
       'If you answered yes to the previous question, what time period (in years) do you stay before having your Cancer screening?',
       'Your Picture', 'Your Picture_URL', '_id', '_uuid', '_submission_time',
       '_validation_status', '_notes', '_status', '_submitted_by',
       '__version__', '_tags', '_index'],
      dtype='object')

In [34]:
healthcare_df.shape

(6158, 32)

In [35]:
healthcare_df.describe()

,_Location_latitude,_Location_longitude,_Location_altitude,_Location_precision,Date and Time,"How many children do you have, if any?",When was the last time you visited a hospital for medical treatment? (In Months),Your Picture,Your Picture_URL,_id,_submission_time,_validation_status,_notes,_tags,_index
count,5805.000000,5805.000000,5805.000000,5805.000000,6010,5533.000000,6000.000000,0.0,0.0,6.158000e+03,6158,0.0,0.0,0.0,6158.000000
mean,-0.737841,36.715208,1536.439555,71.217272,2023-06-23 12:19:03.484193280,147.165371,6.651875,NaN,NaN,2.482603e+08,2023-06-25 04:21:26.056349440,NaN,NaN,NaN,3079.500000
min,-4.051936,34.092111,-201.295000,0.000000,2023-05-15 08:35:00,0.000000,0.000000,NaN,NaN,2.301624e+08,2023-04-05 08:44:06,NaN,NaN,NaN,1.000000
25%,-1.259315,36.379644,1348.900024,4.100000,2023-06-16 10:18:30,1.000000,2.000000,NaN,NaN,2.469582e+08,2023-06-19 10:27:25.750000128,NaN,NaN,NaN,1540.250000
50%,-0.726425,36.866007,1592.900024,4.820000,2023-06-23 10:22:00,2.000000,4.000000,NaN,NaN,2.486249e+08,2023-06-26 09:56:12.500000,NaN,NaN,NaN,3079.500000
75%,-0.378057,37.146309,1857.600000,7.196000,2023-06-30 15:33:30,3.000000,8.000000,NaN,NaN,2.499817e+08,2023-07-03 13:40:47,NaN,NaN,NaN,4618.750000
max,1.842157,39.692109,2988.477000,4900.000000,2023-07-27 12:00:00,800159.000000,2021.000000,NaN,NaN,2.584794e+08,2023-08-07 09:12:14,NaN,NaN,NaN,6158.000000
std,0.870519,0.866878,494.157138,388.100302,NaN,10757.084650,37.295530,NaN,NaN,2.565886e+06,NaN,NaN,NaN,NaN,1777.805811

In [36]:
# Loop and print each column's description individually
for column in healthcare_df.columns:
    print(f"--- Description for column: {column} ---")
    print(healthcare_df[column].describe())
    print("\n")

--- Description for column: Location ---
count                                               5805
unique                                              5646
top       0.1596770603786683 37.744335271418095 65.0 0.0
freq                                                  13
Name: Location, dtype: object


--- Description for column: _Location_latitude ---
count    5805.000000
mean       -0.737841
std         0.870519
min        -4.051936
25%        -1.259315
50%        -0.726425
75%        -0.378057
max         1.842157
Name: _Location_latitude, dtype: float64


--- Description for column: _Location_longitude ---
count    5805.000000
mean       36.715208
std         0.866878
min        34.092111
25%        36.379644
50%        36.866007
75%        37.146309
max        39.692109
Name: _Location_longitude, dtype: float64


--- Description for column: _Location_altitude ---
count    5805.000000
mean     1536.439555
std       494.157138
min      -201.295000
25%      1348.900024
50%      1592.900024
75%      1857.600000
max      2988.477000
Name: _Location_altitude, dtype: float64


--- Description for column: _Location_precision ---
count    5805.000000
mean       71.217272
std       388.100302
min         0.000000
25%         4.100000
50%         4.820000
75%         7.196000
max      4900.000000
Name: _Location_precision, dtype: float64


--- Description for column: Date and Time ---
count                             6010
mean     2023-06-23 12:19:03.484193280
min                2023-05-15 08:35:00
25%                2023-06-16 10:18:30
50%                2023-06-23 10:22:00
75%                2023-06-30 15:33:30
max                2023-07-27 12:00:00
Name: Date and Time, dtype: object


--- Description for column: Age ---
count      6140
unique        5
top       18-30
freq       2183
Name: Age, dtype: object


--- Description for column: Gender ---
count     6141
unique       2
top       Male
freq      3107
Name: Gender, dtype: object


--- Description for column: Marital Status ---
count        6140
unique          3
top       Married
freq         3654
Name: Marital Status, dtype: object


--- Description for column: How many children do you have, if any? ---
count      5533.000000
mean        147.165371
std       10757.084650
min           0.000000
25%           1.000000
50%           2.000000
75%           3.000000
max      800159.000000
Name: How many children do you have, if any?, dtype: float64


--- Description for column: Employment Status ---
count         6134
unique           3
top       Employed
freq          2177
Name: Employment Status, dtype: object


--- Description for column: Monthly Household Income ---
count                5899
unique                  6
top       Less than 10000
freq                 1837
Name: Monthly Household Income, dtype: object


--- Description for column: Have you ever had health insurance? ---
count     6139
unique       2
top        Yes
freq      3558
Name: Have you ever had health insurance?, dtype: object


--- Description for column: If yes, which insurance cover? ---
count     3618
unique     262
top       NHIF
freq      1170
Name: If yes, which insurance cover?, dtype: object


--- Description for column: When was the last time you visited a hospital for medical treatment? (In Months) ---
count    6000.000000
mean        6.651875
std        37.295530
min         0.000000
25%         2.000000
50%         4.000000
75%         8.000000
max      2021.000000
Name: When was the last time you visited a hospital for medical treatment? (In Months), dtype: float64


--- Description for column: Did you have health insurance during your last hospital visit? ---
count     6102
unique       2
top         No
freq      3264
Name: Did you have health insurance during your last hospital visit?, dtype: object


--- Description for column: Have you ever had a routine check-up with a doctor or healthcare provider? ---
count     6135
unique       2
top         No
freq      4342
Name: Have you ever had a routine check-up with a doctor or healthcare provider?, dtype: object


--- Description for column: If you answered yes to the previous question, what time period (in years) do you stay before having your routine check-up? ---
count     1776
unique       4
top          1
freq       827
Name: If you answered yes to the previous question, what time period (in years) do you stay before having your routine check-up?, dtype: int64


--- Description for column: Have you ever had a cancer screening (e.g. mammogram, colonoscopy, etc.)? ---
count     6127
unique       2
top         No
freq      4661
Name: Have you ever had a cancer screening (e.g. mammogram, colonoscopy, etc.)?, dtype: object


--- Description for column: If you answered yes to the previous question, what time period (in years) do you stay before having your Cancer screening? ---
count     1565
unique       4
top         4+
freq       460
Name: If you answered yes to the previous question, what time period (in years) do you stay before having your Cancer screening?, dtype: object


--- Description for column: Your Picture ---
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: Your Picture, dtype: float64


--- Description for column: Your Picture_URL ---
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: Your Picture_URL, dtype: float64


--- Description for column: _id ---
count    6.158000e+03
mean     2.482603e+08
std      2.565886e+06
min      2.301624e+08
25%      2.469582e+08
50%      2.486249e+08
75%      2.499817e+08
max      2.584794e+08
Name: _id, dtype: float64


--- Description for column: _uuid ---
count                                     6158
unique                                    6158
top       aa30304f-84f2-4c1b-b30a-371241f2ff17
freq                                         1
Name: _uuid, dtype: object


--- Description for column: _submission_time ---
count                             6158
mean     2023-06-25 04:21:26.056349440
min                2023-04-05 08:44:06
25%      2023-06-19 10:27:25.750000128
50%         2023-06-26 09:56:12.500000
75%                2023-07-03 13:40:47
max                2023-08-07 09:12:14
Name: _submission_time, dtype: object


--- Description for column: _validation_status ---
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: _validation_status, dtype: float64


--- Description for column: _notes ---
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: _notes, dtype: float64


--- Description for column: _status ---
count                  6158
unique                    1
top       submitted_via_web
freq                   6158
Name: _status, dtype: object


--- Description for column: _submitted_by ---
count           6157
unique             1
top       safra_data
freq            6157
Name: _submitted_by, dtype: object


--- Description for column: __version__ ---
count                       6158
unique                         4
top       vNRCdRrE8Lpm9kXT55RgPB
freq                        5035
Name: __version__, dtype: object


--- Description for column: _tags ---
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: _tags, dtype: float64


--- Description for column: _index ---
count    6158.000000
mean     3079.500000
std      1777.805811
min         1.000000
25%      1540.250000
50%      3079.500000
75%      4618.750000
max      6158.000000
Name: _index, dtype: float64

In [37]:
healthcare_df.isnull().sum()

Location                                                                                                                       353
_Location_latitude                                                                                                             353
_Location_longitude                                                                                                            353
_Location_altitude                                                                                                             353
_Location_precision                                                                                                            353
Date and Time                                                                                                                  148
Age                                                                                                                             18
Gender                                                                                                                          17
Marital Status                                                                                                                  18
How many children do you have, if any?                                                                                         625
Employment Status                                                                                                               24
Monthly Household Income                                                                                                       259
Have you ever had health insurance?                                                                                             19
If yes, which insurance cover?                                                                                                2540
When was the last time you visited a hospital for medical treatment? (In Months)                                               158
Did you have health insurance during your last hospital visit?                                                                  56
Have you ever had a routine check-up with a doctor or healthcare provider?                                                      23
If you answered yes to the previous question, what time period (in years) do you stay before having your routine check-up?    4382
Have you ever had a cancer screening (e.g. mammogram, colonoscopy, etc.)?                                                       31
If you answered yes to the previous question, what time period (in years) do you stay before having your Cancer screening?    4593
Your Picture                                                                                                                  6158
Your Picture_URL                                                                                                              6158
_id                                                                                                                              0
_uuid                                                                                                                            0
_submission_time                                                                                                                 0
_validation_status                                                                                                            6158
_notes                                                                                                                        6158
_status                                                                                                                          0
_submitted_by                                                                                                                    1
__version__                                                                                                                      0
_tags                                                                                                                         6158
_index                                                                                                                           0
dtype: int64

In [38]:
healthcare_df.duplicated().sum()

0

In [39]:
healthcare_df.tail()

,Location,_Location_latitude,_Location_longitude,_Location_altitude,_Location_precision,Date and Time,Age,Gender,Marital Status,"How many children do you have, if any?",Employment Status,Monthly Household Income,Have you ever had health insurance?,"If yes, which insurance cover?",When was the last time you visited a hospital for medical treatment? (In Months),Did you have health insurance during your last hospital visit?,Have you ever had a routine check-up with a doctor or healthcare provider?,"If you answered yes to the previous question, what time period (in years) do you stay before having your routine check-up?","Have you ever had a cancer screening (e.g. mammogram, colonoscopy, etc.)?","If you answered yes to the previous question, what time period (in years) do you stay before having your Cancer screening?",Your Picture,Your Picture_URL,_id,_uuid,_submission_time,_validation_status,_notes,_status,_submitted_by,__version__,_tags,_index
6153,-1.2693104 36.8916948 1618.0 4.816,-1.269310,36.891695,1618.000000,4.816,2023-07-19 08:55:00,18-30,Female,Single,NaN,Self-employed,Less than 10000,Yes,ICEA LION GROUP,3.0,Yes,Yes,2,No,NaN,NaN,NaN,258479363,4634218f-df21-4e98-a159-6b87edc11b35,2023-08-07 09:12:11,NaN,NaN,submitted_via_web,safra_data,vNRCdRrE8Lpm9kXT55RgPB,NaN,6154
6154,-1.2705219 36.8923876 1594.9000244140625 5.0,-1.270522,36.892388,1594.900024,5.000,2023-07-19 08:59:00,41-50,Male,Married,6.0,Self-employed,40001-50000,Yes,APA INSURANCE,3.0,Yes,Yes,1,Yes,1,NaN,NaN,258479365,42076e39-7c01-4f78-a894-2a2158d61798,2023-08-07 09:12:12,NaN,NaN,submitted_via_web,safra_data,vNRCdRrE8Lpm9kXT55RgPB,NaN,6155
6155,-1.2718084 36.8931014 1594.9000244140625 4.84,-1.271808,36.893101,1594.900024,4.840,2023-07-19 09:56:00,31-40,Female,Married,3.0,Employed,10001-20000,Yes,NHIF,6.0,Yes,No,NaN,Yes,2,NaN,NaN,258479369,ee33d8cb-4b92-4f98-9ab2-b61ffd5d3a84,2023-08-07 09:12:12,NaN,NaN,submitted_via_web,safra_data,vNRCdRrE8Lpm9kXT55RgPB,NaN,6156
6156,-1.2730717 36.8938328 1594.9000244140625 4.84,-1.273072,36.893833,1594.900024,4.840,2023-07-19 10:02:00,31-40,Male,Divorced,2.0,Self-employed,Less than 10000,Yes,CIC INSURANCE GROUP,5.0,Yes,Yes,2,Yes,1,NaN,NaN,258479374,66c4ac84-e315-4197-8d3b-d814b837f7e6,2023-08-07 09:12:13,NaN,NaN,submitted_via_web,safra_data,vNRCdRrE8Lpm9kXT55RgPB,NaN,6157
6157,-1.2739374 36.8942481 1594.9000244140625 4.616,-1.273937,36.894248,1594.900024,4.616,2023-07-19 11:05:00,31-40,Female,Married,1.0,Unemployed,Less than 10000,Yes,NHIF,3.0,Yes,Yes,1,Yes,1,NaN,NaN,258479375,a9afdc88-0163-4af5-9b5d-64c277e17f54,2023-08-07 09:12:14,NaN,NaN,submitted_via_web,safra_data,vNRCdRrE8Lpm9kXT55RgPB,NaN,6158

In [40]:
healthcare_df.index

RangeIndex(start=0, stop=6158, step=1)