In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', 200)

In [2]:
HealthCare_df = pd.read_csv('../data/raw/healthcare_biotech_patient_dataset.csv')
HealthCare_df.head(15)

,patient_id,age,gender,ethnicity,region,insurance_type,income_bracket,height_cm,weight_kg,bmi,systolic_bp,diastolic_bp,heart_rate,cholesterol_total,ldl,hdl,glucose_fasting,hba1c,smoking_status,alcohol_consumption,physical_activity_level,family_history_diabetes,family_history_heart_disease,white_blood_cell_count,red_blood_cell_count,platelet_count,crp_level,vitamin_d_level,gene_marker_score,biomarker_a,biomarker_b,num_chronic_conditions,num_prior_hospital_visits,medication_count,admission_type,department,treatment_type,had_surgery,length_of_stay_days,admission_date,discharge_date,readmitted_30days,total_healthcare_cost
0,158790,39.9,f,NaN,West,MEDICARE,NaN,152.8,90.3,NaN,133.0,70.0,80.0,212.0,106.0,59.0,125.0,7.2,Never,Moderate,Light,0,0,NaN,3.20,190.0,2.79,NaN,32.92,1.70,38.11,1,2,1.0,Emergency,Emergency,Medication,0,3,2022-01-24,2022-01-27,1,2778.44
1,314295,17.7,M,NaN,Northeast,medicare,100k-150k,172.9,88.3,29.5,114.0,71.0,66.0,219.0,131.0,68.0,98.0,NaN,NaN,NaN,Sedentary,1,0,NaN,5.11,281.0,8.84,27.0,29.68,NaN,NaN,0,1,0.0,Elective,Orthopedics,Combination,0,2,2022-02-20,2022-02-22,0,2102.12
2,173610,55.5,FEMALE,Hispanic,South,PRIVATE,25k-50k,173.0,69.0,23.1,113.0,65.0,66.0,193.0,112.0,75.0,112.0,7.2,Current,NaN,Moderate,1,0,7.61,5.76,295.0,NaN,35.9,31.48,NaN,NaN,0,2,2.0,Newborn,Pediatrics,Medication,0,0,2023-10-14,2023-10-14,0,1452.31
3,296884,32.4,Male,Hispanic,Northeast,NaN,50k-75k,173.8,95.3,31.5,118.0,64.0,70.0,210.0,NaN,NaN,95.0,6.4,Never,Heavy,Light,0,0,7.12,4.97,286.0,NaN,NaN,21.80,5.33,54.51,1,0,1.0,Emergency,Emergency,Therapy,0,0,2022-12-11,2022-12-11,0,2005.37
4,324447,81.0,F,Black,Northeast,medicare,NaN,158.6,92.5,36.8,124.0,77.0,75.0,NaN,162.0,51.0,120.0,7.4,Never,NaN,Sedentary,1,0,NaN,NaN,185.0,1.99,27.1,40.84,NaN,45.67,2,5,1.0,Elective,Endocrinology,Observation,0,2,2021-01-26,2021-01-28,0,3840.04
5,223935,49.5,MALE,Unknown,Midwest,private,25k-50k,182.9,78.4,23.4,138.0,78.0,74.0,208.0,119.0,67.0,103.0,6.6,Former,Light,Active,0,1,7.83,4.35,276.0,11.84,11.1,43.75,1.36,58.40,0,2,0.0,Emergency,General Medicine,Medication,0,4,2020-05-06,2020-05-10,1,2207.07
6,332159,52.3,F,White,Midwest,uninsured,25k-50k,166.9,64.6,23.2,126.0,71.0,76.0,246.0,NaN,66.0,112.0,6.2,Former,Light,Moderate,0,1,7.69,3.35,287.0,8.36,39.3,41.02,7.02,NaN,0,1,0.0,Emergency,Oncology,Therapy,0,1,2020-02-09,2020-02-10,0,1805.02
7,14143,6.9,F,Black,Midwest,Medicaid,100k-150k,172.8,71.2,23.8,111.0,77.0,83.0,215.0,140.0,NaN,104.0,5.5,never,Light,Light,0,1,8.27,4.55,175.0,6.50,NaN,19.73,2.39,NaN,0,0,0.0,Urgent,Oncology,Medication,0,2,2020-08-20,2020-08-22,0,2217.61
8,26611,22.0,female,Asian,Northeast,Medicare,25k-50k,163.1,67.8,25.5,114.0,61.0,84.0,243.0,129.0,NaN,112.0,6.4,Former,Light,Light,1,0,8.12,5.78,158.0,7.36,NaN,48.13,5.47,NaN,1,4,0.0,Emergency,Emergency,Medication,0,0,2022-01-30,2022-01-30,0,2205.64
9,115623,42.5,F,Asian,Northeast,NaN,NaN,171.6,96.9,32.9,134.0,90.0,82.0,275.0,NaN,54.0,134.0,6.5,Never,Light,Moderate,0,0,5.45,4.46,293.0,8.46,NaN,53.93,1.67,51.03,2,6,0.0,Emergency,Oncology,Surgery,1,3,2023-11-21,2023-11-24,1,5191.19
10,222889,32.4,f,Hispanic,Midwest,Medicare,50k-75k,155.9,69.2,28.5,139.0,66.0,63.0,158.0,103.0,68.0,91.0,5.9,Never,NaN,Light,1,0,7.30,4.69,289.0,4.79,NaN,42.09,2.17,42.55,1,6,1.0,Elective,Surgery,Medication,0,1,2024-11-29,2024-11-30,1,2728.30
11,109095,51.6,Non-binary,Hispanic,Northeast,medicaid,<25k,NaN,67.4,27.1,140.0,80.0,74.0,217.0,109.0,NaN,96.0,6.2,Never,Moderate,Sedentary,1,1,7.39,5.16,236.0,NaN,28.8,50.30,3.21,34.32,2,5,NaN,Elective,Oncology,Surgery,1,2,2021-02-21,2021-02-23,0,2712.79
12,264612,28.3,F,White,Midwest,Priv.,50k-75k,152.8,65.8,28.2,108.0,84.0,83.0,NaN,124.0,67.0,85.0,6.1,Current,NaN,NaN,0,0,6.20,5.47,201.0,1.89,NaN,24.60,0.69,51.09,0,1,1.0,Elective,Emergency,Medication,0,3,2024-08-16,2024-08-19,0,2516.84
13,345858,55.9,male,Hispanic,West,VA,25k-50k,167.0,98.1,35.2,138.0,86.0,86.0,NaN,209.0,65.0,115.0,6.5,Current,Light,Sedentary,0,1,4.76,5.26,249.0,2.42,27.5,38.04,4.45,41.95,5,2,3.0,Urgent,Surgery,Surgery,1,5,2024-01-03,2024-01-08,1,6843.19
14,101714,67.2,male,Asian,West,medicaid,50k-75k,189.1,64.6,18.1,143.0,85.0,78.0,237.0,148.0,NaN,123.0,6.9,Never,NaN,Sedentary,1,0,4.83,5.22,150.0,8.52,18.4,37.58,NaN,59.94,5,6,3.0,Emergency,Pediatrics,Medication,0,3,2022-12-30,2023-01-02,0,3623.08

## Removing Duplicates

In [3]:
HealthCare = HealthCare_df.drop_duplicates().copy()

In [4]:
HealthCare.duplicated().sum()

0

## Handling Null Values

In [5]:
HealthCare.isnull().sum()

patient_id                           0
age                                  0
gender                            3913
ethnicity                        19683
region                               0
insurance_type                   27076
income_bracket                   58912
height_cm                        23627
weight_kg                        23611
bmi                              15731
systolic_bp                      19407
diastolic_bp                     19510
heart_rate                           0
cholesterol_total                39710
ldl                              59204
hdl                              59230
glucose_fasting                  31767
hba1c                            78245
smoking_status                   27426
alcohol_consumption             160358
physical_activity_level          39408
family_history_diabetes              0
family_history_heart_disease         0
white_blood_cell_count           47179
red_blood_cell_count             46984
platelet_count                   47227
crp_level                        70576
vitamin_d_level                  98044
gene_marker_score                    0
biomarker_a                     118222
biomarker_b                     118279
num_chronic_conditions               0
num_prior_hospital_visits            0
medication_count                 19648
admission_type                       0
department                           0
treatment_type                       0
had_surgery                          0
length_of_stay_days                  0
admission_date                       0
discharge_date                       0
readmitted_30days                    0
total_healthcare_cost                0
dtype: int64

In [6]:
HealthCare[['gender', 'ethnicity']] = HealthCare[['gender', 'ethnicity']].fillna('Other')

In [7]:
HealthCare['insurance_type'] = HealthCare['insurance_type'].fillna('Uninsured')

In [8]:
HealthCare['income_bracket'] = HealthCare['income_bracket'].fillna('Undisclosed')

In [9]:
HealthCare[['height_cm', 'weight_kg']] = HealthCare[['height_cm', 'weight_kg']].fillna(HealthCare[['height_cm', 'weight_kg']].mean())

In [10]:
BMI = HealthCare['weight_kg'] / pow((HealthCare['height_cm'] / 100), 2)
HealthCare['bmi'] = HealthCare['bmi'].fillna(BMI)

In [11]:
HealthCare['systolic_bp'] = HealthCare['systolic_bp'].fillna(HealthCare.groupby('age')['systolic_bp'].transform('median'))

In [12]:
HealthCare['diastolic_bp'] = HealthCare['diastolic_bp'].fillna(HealthCare.groupby('age')['diastolic_bp'].transform('median'))

In [13]:
# Drop rows only if ALL three primary lipid metrics are missing
HealthCare.dropna(subset=['cholesterol_total', 'ldl', 'hdl'], how='all', inplace=True)

In [14]:
# Fill missing values using the median of matching age cohorts
for col in ['cholesterol_total', 'ldl', 'hdl']:
    HealthCare[col] = HealthCare[col].fillna(HealthCare.groupby('age')[col].transform('median'))

In [15]:
# Drop rows ONLY if fasting glucose is missing
HealthCare.dropna(subset=['glucose_fasting'], inplace=True)

In [16]:
HealthCare['hba1c'] = (HealthCare['glucose_fasting'] + 46.7) / 28.7

In [17]:
HealthCare['smoking_status'] = HealthCare['smoking_status'].fillna('Unknown')

In [18]:
HealthCare['alcohol_consumption'] = HealthCare['alcohol_consumption'].fillna('Unknown')

In [19]:
HealthCare['physical_activity_level'] = HealthCare['physical_activity_level'].fillna('Unknown')

In [20]:
# Drop rows ONLY if both WBC and RBC are missing entirely
HealthCare.dropna(subset=['white_blood_cell_count', 'red_blood_cell_count'], how='all', inplace=True)

In [21]:
# RBC must use gender because male/female reference ranges differ significantly
HealthCare['red_blood_cell_count'] = HealthCare['red_blood_cell_count'].fillna(
    HealthCare.groupby(['gender', 'age'])['red_blood_cell_count'].transform('median')
)

In [22]:
# WBC can be filled using age-group medians
HealthCare['white_blood_cell_count'] = HealthCare['white_blood_cell_count'].fillna(
    HealthCare.groupby('age')['white_blood_cell_count'].transform('median')
)

In [23]:
HealthCare.dropna(subset=['red_blood_cell_count'], inplace=True)

In [24]:
# Fill missing platelets using the median of matching age cohorts
HealthCare['platelet_count'] = HealthCare['platelet_count'].fillna(
    HealthCare.groupby('age')['platelet_count'].transform('median')
)

In [25]:
# Create temporary WBC tiers to calculate realistic CRP levels
HealthCare['wbc_tier'] = pd.qcut(HealthCare['white_blood_cell_count'], q=4, labels=['Low', 'Normal', 'High', 'Very High'])

# Fill missing CRP using the median of patients in the same immune tier
HealthCare['crp_level'] = HealthCare['crp_level'].fillna(
    HealthCare.groupby('wbc_tier', observed=True)['crp_level'].transform('median')
)

# Drop the temporary tier column
HealthCare.drop(columns=['wbc_tier'], inplace=True)

In [26]:
# Create a mask that excludes the 'Other' group from the calculation
known_ethnicities = HealthCare[HealthCare['ethnicity'] != 'Other']

# Calculate the medians using only known backgrounds
ethnic_medians = known_ethnicities.groupby(['ethnicity', 'age'])['vitamin_d_level'].median()

# Create the multi-index template for alignment
multi_index = ['ethnicity', 'age']

# Set the index temporarily to match ethnic_medians, fill the nulls, and reset it back
HealthCare['vitamin_d_level'] = (
    HealthCare.set_index(multi_index)['vitamin_d_level']
    .fillna(ethnic_medians)
    .values
)

# Final safety fallback using just age for anyone left over
HealthCare['vitamin_d_level'] = HealthCare['vitamin_d_level'].fillna(
    HealthCare.groupby('age')['vitamin_d_level'].transform('median')
)

In [27]:
# Fix Sparsely Ordered Specialty Markers with an explicit fallback chain
for col in ['biomarker_a', 'biomarker_b']:
    if col in HealthCare.columns:
        # Step 1: Try filling with specific gender + age medians
        gender_age_median = HealthCare.groupby(['gender', 'age'])[col].transform('median').round()
        HealthCare[col] = HealthCare[col].fillna(gender_age_median)
        
        # Step 2: Widened Fallback - Fill any remaining empty slices using just age medians
        age_median = HealthCare.groupby('age')[col].transform('median').round()
        HealthCare[col] = HealthCare[col].fillna(age_median)
        
        # Step 3: Global Safety Net - Fill remaining edge cases with the global rounded median
        global_median = HealthCare[col].median()
        # If the whole column is empty (edge case), default to 0 to prevent crashes
        if pd.isna(global_median):
            global_median = 0
        HealthCare[col] = HealthCare[col].fillna(round(global_median))

In [28]:
HealthCare['medication_count'] = HealthCare['medication_count'].fillna(0.0)

In [29]:
HealthCare.isnull().sum()

patient_id                      0
age                             0
gender                          0
ethnicity                       0
region                          0
insurance_type                  0
income_bracket                  0
height_cm                       0
weight_kg                       0
bmi                             0
systolic_bp                     0
diastolic_bp                    0
heart_rate                      0
cholesterol_total               0
ldl                             0
hdl                             0
glucose_fasting                 0
hba1c                           0
smoking_status                  0
alcohol_consumption             0
physical_activity_level         0
family_history_diabetes         0
family_history_heart_disease    0
white_blood_cell_count          0
red_blood_cell_count            0
platelet_count                  0
crp_level                       0
vitamin_d_level                 0
gene_marker_score               0
biomarker_a                     0
biomarker_b                     0
num_chronic_conditions          0
num_prior_hospital_visits       0
medication_count                0
admission_type                  0
department                      0
treatment_type                  0
had_surgery                     0
length_of_stay_days             0
admission_date                  0
discharge_date                  0
readmitted_30days               0
total_healthcare_cost           0
dtype: int64

In [30]:
HealthCare.shape

(355253, 43)

In [31]:
HealthCare.head(15)

,patient_id,age,gender,ethnicity,region,insurance_type,income_bracket,height_cm,weight_kg,bmi,systolic_bp,diastolic_bp,heart_rate,cholesterol_total,ldl,hdl,glucose_fasting,hba1c,smoking_status,alcohol_consumption,physical_activity_level,family_history_diabetes,family_history_heart_disease,white_blood_cell_count,red_blood_cell_count,platelet_count,crp_level,vitamin_d_level,gene_marker_score,biomarker_a,biomarker_b,num_chronic_conditions,num_prior_hospital_visits,medication_count,admission_type,department,treatment_type,had_surgery,length_of_stay_days,admission_date,discharge_date,readmitted_30days,total_healthcare_cost
0,158790,39.9,f,Other,West,MEDICARE,Undisclosed,152.80000,90.3,38.675955,133.0,70.0,80.0,212.0,106.0,59.0,125.0,5.982578,Never,Moderate,Light,0,0,7.055,3.20,190.0,2.79,26.95,32.92,1.70,38.11,1,2,1.0,Emergency,Emergency,Medication,0,3,2022-01-24,2022-01-27,1,2778.44
1,314295,17.7,M,Other,Northeast,medicare,100k-150k,172.90000,88.3,29.500000,114.0,71.0,66.0,219.0,131.0,68.0,98.0,5.041812,Unknown,Unknown,Sedentary,1,0,6.950,5.11,281.0,8.84,27.00,29.68,5.00,44.00,0,1,0.0,Elective,Orthopedics,Combination,0,2,2022-02-20,2022-02-22,0,2102.12
2,173610,55.5,FEMALE,Hispanic,South,PRIVATE,25k-50k,173.00000,69.0,23.100000,113.0,65.0,66.0,193.0,112.0,75.0,112.0,5.529617,Current,Unknown,Moderate,1,0,7.610,5.76,295.0,4.49,35.90,31.48,4.00,48.00,0,2,2.0,Newborn,Pediatrics,Medication,0,0,2023-10-14,2023-10-14,0,1452.31
3,296884,32.4,Male,Hispanic,Northeast,Uninsured,50k-75k,173.80000,95.3,31.500000,118.0,64.0,70.0,210.0,118.0,56.0,95.0,4.937282,Never,Heavy,Light,0,0,7.120,4.97,286.0,4.49,29.10,21.80,5.33,54.51,1,0,1.0,Emergency,Emergency,Therapy,0,0,2022-12-11,2022-12-11,0,2005.37
5,223935,49.5,MALE,Unknown,Midwest,private,25k-50k,182.90000,78.4,23.400000,138.0,78.0,74.0,208.0,119.0,67.0,103.0,5.216028,Former,Light,Active,0,1,7.830,4.35,276.0,11.84,11.10,43.75,1.36,58.40,0,2,0.0,Emergency,General Medicine,Medication,0,4,2020-05-06,2020-05-10,1,2207.07
6,332159,52.3,F,White,Midwest,uninsured,25k-50k,166.90000,64.6,23.200000,126.0,71.0,76.0,246.0,127.0,66.0,112.0,5.529617,Former,Light,Moderate,0,1,7.690,3.35,287.0,8.36,39.30,41.02,7.02,54.00,0,1,0.0,Emergency,Oncology,Therapy,0,1,2020-02-09,2020-02-10,0,1805.02
7,14143,6.9,F,Black,Midwest,Medicaid,100k-150k,172.80000,71.2,23.800000,111.0,77.0,83.0,215.0,140.0,54.0,104.0,5.250871,never,Light,Light,0,1,8.270,4.55,175.0,6.50,30.90,19.73,2.39,51.00,0,0,0.0,Urgent,Oncology,Medication,0,2,2020-08-20,2020-08-22,0,2217.61
8,26611,22.0,female,Asian,Northeast,Medicare,25k-50k,163.10000,67.8,25.500000,114.0,61.0,84.0,243.0,129.0,56.0,112.0,5.529617,Former,Light,Light,1,0,8.120,5.78,158.0,7.36,22.25,48.13,5.47,50.00,1,4,0.0,Emergency,Emergency,Medication,0,0,2022-01-30,2022-01-30,0,2205.64
9,115623,42.5,F,Asian,Northeast,Uninsured,Undisclosed,171.60000,96.9,32.900000,134.0,90.0,82.0,275.0,119.0,54.0,134.0,6.296167,Never,Light,Moderate,0,0,5.450,4.46,293.0,8.46,30.50,53.93,1.67,51.03,2,6,0.0,Emergency,Oncology,Surgery,1,3,2023-11-21,2023-11-24,1,5191.19
10,222889,32.4,f,Hispanic,Midwest,Medicare,50k-75k,155.90000,69.2,28.500000,139.0,66.0,63.0,158.0,103.0,68.0,91.0,4.797909,Never,Unknown,Light,1,0,7.300,4.69,289.0,4.79,29.10,42.09,2.17,42.55,1,6,1.0,Elective,Surgery,Medication,0,1,2024-11-29,2024-11-30,1,2728.30
11,109095,51.6,Non-binary,Hispanic,Northeast,medicaid,<25k,169.23978,67.4,27.100000,140.0,80.0,74.0,217.0,109.0,56.0,96.0,4.972125,Never,Moderate,Sedentary,1,1,7.390,5.16,236.0,4.49,28.80,50.30,3.21,34.32,2,5,0.0,Elective,Oncology,Surgery,1,2,2021-02-21,2021-02-23,0,2712.79
12,264612,28.3,F,White,Midwest,Priv.,50k-75k,152.80000,65.8,28.200000,108.0,84.0,83.0,195.0,124.0,67.0,85.0,4.588850,Current,Unknown,Unknown,0,0,6.200,5.47,201.0,1.89,27.10,24.60,0.69,51.09,0,1,1.0,Elective,Emergency,Medication,0,3,2024-08-16,2024-08-19,0,2516.84
13,345858,55.9,male,Hispanic,West,VA,25k-50k,167.00000,98.1,35.200000,138.0,86.0,86.0,214.0,209.0,65.0,115.0,5.634146,Current,Light,Sedentary,0,1,4.760,5.26,249.0,2.42,27.50,38.04,4.45,41.95,5,2,3.0,Urgent,Surgery,Surgery,1,5,2024-01-03,2024-01-08,1,6843.19
14,101714,67.2,male,Asian,West,medicaid,50k-75k,189.10000,64.6,18.100000,143.0,85.0,78.0,237.0,148.0,56.0,123.0,5.912892,Never,Unknown,Sedentary,1,0,4.830,5.22,150.0,8.52,18.40,37.58,5.00,59.94,5,6,3.0,Emergency,Pediatrics,Medication,0,3,2022-12-30,2023-01-02,0,3623.08
15,193475,72.3,FEMALE,White,South,Uninsured,50k-75k,161.30000,72.5,27.900000,141.0,85.0,87.0,177.0,110.0,54.0,93.0,4.867596,Never,Light,Light,1,0,7.150,4.80,307.0,4.49,29.10,41.41,5.33,56.00,2,7,3.0,Urgent,Cardiology,Medication,0,0,2020-01-25,2020-01-25,0,2523.95

## Analysis of each column individually

In [32]:
# 1. Calculate the standard Quartiles
Q1 = HealthCare['age'].quantile(0.25)
Q3 = HealthCare['age'].quantile(0.75)
IQR = Q3 - Q1

# 2. Define the standard statistical fences
lower_fence = Q1 - 1.5 * IQR
upper_fence = Q3 + 1.5 * IQR

print(f"Statistical bounds for Age: {lower_fence} to {upper_fence}")

# 3. Separate your clean rows from your outlier rows
age_outliers = HealthCare[(HealthCare['age'] < lower_fence) | (HealthCare['age'] > upper_fence)]
print(f"Number of rows flagged as age outliers: {len(age_outliers)}")

Statistical bounds for Age: 3.4499999999999957 to 100.65
Number of rows flagged as age outliers: 3510

In [33]:
# Safe Alternative: Cap extreme ages at a maximum logical threshold of 110 rather than deleting patients
HealthCare['age'] = HealthCare['age'].clip(lower=0, upper=110)

In [34]:
HealthCare['age'].describe()

count    355253.000000
mean         52.041027
std          18.164139
min           0.000000
25%          39.900000
50%          52.000000
75%          64.200000
max         110.000000
Name: age, dtype: float64

In [35]:
HealthCare['gender'] = HealthCare['gender'].str.upper()

In [36]:
HealthCare['gender'] = HealthCare['gender'].replace('FEMALE', 'F')

In [37]:
HealthCare['gender'] = HealthCare['gender'].replace('MALE', 'M')

In [38]:
HealthCare['gender'] = HealthCare['gender'].replace(['OTHER', 'O'], 'Other')

In [39]:
HealthCare['gender'].value_counts()

gender
F             172393
M             168846
Other          11464
NON-BINARY      2550
Name: count, dtype: int64

In [40]:
HealthCare['gender'].describe()

count     355253
unique         4
top            F
freq      172393
Name: gender, dtype: object

In [41]:
HealthCare['ethnicity'] = HealthCare['ethnicity'].str.capitalize()

In [42]:
HealthCare['ethnicity'] = HealthCare['ethnicity'].str.strip()

In [43]:
HealthCare['ethnicity'] = HealthCare['ethnicity'].replace('UNKNOWN', 'OTHER')

In [44]:
HealthCare['ethnicity'].value_counts()

ethnicity
White              133735
Hispanic            66726
Black               60290
Asian               40018
Other               31248
Native american      9954
Unknown              9874
white                1329
hispanic              709
black                 628
asian                 429
other                 127
native american       106
unknown                80
Name: count, dtype: int64

In [45]:
HealthCare['insurance_type'] = HealthCare['insurance_type'].str.capitalize()

In [46]:
HealthCare['insurance_type'] = HealthCare['insurance_type'].replace('Priv.', 'Private')

In [47]:
HealthCare['insurance_type'].value_counts()

insurance_type
Private        155006
Medicare        86176
Medicaid        62056
Uninsured       38196
Military         4666
Va               4590
Va/military      4563
Name: count, dtype: int64

In [48]:
HealthCare['smoking_status'] = HealthCare['smoking_status'].str.capitalize()

In [49]:
HealthCare['smoking_status'] = HealthCare['smoking_status'].str.strip()

In [50]:
HealthCare['smoking_status'].value_counts()

smoking_status
Never      179762
Former      81692
Current     65542
Unknown     24837
never        1914
former        845
current       661
Name: count, dtype: int64

In [51]:
HealthCare['department'] = HealthCare['department'].str.strip()

In [52]:
HealthCare['department'] = HealthCare['department'].str.capitalize()

In [53]:
HealthCare['department'].value_counts()

department
General medicine    70687
Cardiology          49621
Emergency           46193
Orthopedics         42513
Oncology            35479
Neurology           32105
Surgery             28882
Endocrinology       28576
Pediatrics          21197
Name: count, dtype: int64

In [54]:
HealthCare['length_of_stay_days'].value_counts()

length_of_stay_days
 2      78843
 3      67660
 1      65635
 4      47626
 0      30566
 5      29656
 6      17108
 7       9072
 8       4553
 9       2191
 10       965
 11       407
-1        360
 500      357
 12       154
 13        62
 14        24
 15         8
 16         5
 17         1
Name: count, dtype: int64

In [55]:
# Step 1: Drop impossible administrative data entry typos (negative days)
HealthCare = HealthCare[HealthCare['length_of_stay_days'] >= 0]

# Step 2: NOW run the log transformation safely
log_los = np.log1p(HealthCare['length_of_stay_days'])

# Step 3: Calculate IQR on the log scale
q1 = log_los.quantile(0.25)
q3 = log_los.quantile(0.75)
iqr = q3 - q1

# Step 4: Calculate the upper fence and convert it back to raw days
log_upper_fence = q3 + (1.5 * iqr)
raw_upper_fence = np.expm1(log_upper_fence)

print(f"Any stay longer than {raw_upper_fence:.1f} days is a statistical outlier.")

# Step 5: Filter out rows above this logical threshold
HealthCare = HealthCare[HealthCare['length_of_stay_days'] <= raw_upper_fence]

Any stay longer than 18.8 days is a statistical outlier.

In [60]:
HealthCare = HealthCare[HealthCare['admission_date'] <= HealthCare['discharge_date']].copy()

In [61]:
date_cols = ['admission_date', 'discharge_date']
HealthCare[date_cols] = HealthCare[date_cols].apply(pd.to_datetime)

In [62]:
HealthCare['length_of_stay_days'] = (HealthCare['discharge_date'] - HealthCare['admission_date']).dt.days

In [63]:
HealthCare[['admission_date', 'discharge_date']].dtypes

admission_date    datetime64[ns]
discharge_date    datetime64[ns]
dtype: object

In [65]:
HealthCare.reset_index(drop=True, inplace=True)

In [66]:
HealthCare.head()

,patient_id,age,gender,ethnicity,region,insurance_type,income_bracket,height_cm,weight_kg,bmi,systolic_bp,diastolic_bp,heart_rate,cholesterol_total,ldl,hdl,glucose_fasting,hba1c,smoking_status,alcohol_consumption,physical_activity_level,family_history_diabetes,family_history_heart_disease,white_blood_cell_count,red_blood_cell_count,platelet_count,crp_level,vitamin_d_level,gene_marker_score,biomarker_a,biomarker_b,num_chronic_conditions,num_prior_hospital_visits,medication_count,admission_type,department,treatment_type,had_surgery,length_of_stay_days,admission_date,discharge_date,readmitted_30days,total_healthcare_cost
0,158790,39.9,F,Other,West,Medicare,Undisclosed,152.8,90.3,38.675955,133.0,70.0,80.0,212.0,106.0,59.0,125.0,5.982578,Never,Moderate,Light,0,0,7.055,3.20,190.0,2.79,26.95,32.92,1.70,38.11,1,2,1.0,Emergency,Emergency,Medication,0,3,2022-01-24,2022-01-27,1,2778.44
1,314295,17.7,M,Other,Northeast,Medicare,100k-150k,172.9,88.3,29.500000,114.0,71.0,66.0,219.0,131.0,68.0,98.0,5.041812,Unknown,Unknown,Sedentary,1,0,6.950,5.11,281.0,8.84,27.00,29.68,5.00,44.00,0,1,0.0,Elective,Orthopedics,Combination,0,2,2022-02-20,2022-02-22,0,2102.12
2,173610,55.5,F,Hispanic,South,Private,25k-50k,173.0,69.0,23.100000,113.0,65.0,66.0,193.0,112.0,75.0,112.0,5.529617,Current,Unknown,Moderate,1,0,7.610,5.76,295.0,4.49,35.90,31.48,4.00,48.00,0,2,2.0,Newborn,Pediatrics,Medication,0,0,2023-10-14,2023-10-14,0,1452.31
3,296884,32.4,M,Hispanic,Northeast,Uninsured,50k-75k,173.8,95.3,31.500000,118.0,64.0,70.0,210.0,118.0,56.0,95.0,4.937282,Never,Heavy,Light,0,0,7.120,4.97,286.0,4.49,29.10,21.80,5.33,54.51,1,0,1.0,Emergency,Emergency,Therapy,0,0,2022-12-11,2022-12-11,0,2005.37
4,223935,49.5,M,Unknown,Midwest,Private,25k-50k,182.9,78.4,23.400000,138.0,78.0,74.0,208.0,119.0,67.0,103.0,5.216028,Former,Light,Active,0,1,7.830,4.35,276.0,11.84,11.10,43.75,1.36,58.40,0,2,0.0,Emergency,General medicine,Medication,0,4,2020-05-06,2020-05-10,1,2207.07

In [80]:
HealthCare['heart_rate'].describe()

count    353443.000000
mean         75.988748
std          11.979094
min          30.000000
25%          68.000000
50%          76.000000
75%          84.000000
max         129.000000
Name: heart_rate, dtype: float64

In [79]:
# Keep only physiologically possible heart rates (30 to 220 bpm)
HealthCare = HealthCare[(HealthCare['heart_rate'] >= 30) & (HealthCare['heart_rate'] <= 220)]

# Reset index immediately after dropping rows to keep it consistent
HealthCare.reset_index(drop=True, inplace=True)

In [87]:
HealthCare['white_blood_cell_count'].describe()

count    353443.000000
mean          6.994921
std           1.892067
min          -2.110000
25%           5.830000
50%           6.995000
75%           8.160000
max          15.630000
Name: white_blood_cell_count, dtype: float64

In [98]:
HealthCare['white_blood_cell_count'].value_counts()

white_blood_cell_count
6.980     1978
12.000    1969
2.000     1957
6.960     1764
6.990     1692
          ...
7.505        1
7.050        1
6.615        1
8.105        1
7.285        1
Name: count, Length: 1119, dtype: int64

In [94]:
Q1 = HealthCare['white_blood_cell_count'].quantile(0.25)
Q3 = HealthCare['white_blood_cell_count'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - IQR * 1.5
upper = Q3 + IQR * 1.5

print(f'lower to upper : {lower} - {upper}')

lower to upper : 2.335 - 11.655000000000001

In [97]:
HealthCare['white_blood_cell_count'] = HealthCare['white_blood_cell_count'].clip(lower=2, upper=12)

In [106]:
HealthCare['platelet_count'].describe()

count    353443.000000
mean        249.883439
std          55.009478
min         114.000000
25%         216.000000
50%         250.000000
75%         284.000000
max         386.000000
Name: platelet_count, dtype: float64

In [104]:
Q1 = HealthCare['platelet_count'].quantile(0.25)
Q3 = HealthCare['platelet_count'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 *IQR

print(f'Lower to Upper: {lower} - {upper}')

Lower to Upper: 114.0 - 386.0

In [105]:
HealthCare['platelet_count'] = HealthCare['platelet_count'].clip(lower=114, upper=386)

In [114]:
HealthCare['vitamin_d_level'].describe()

count    353443.000000
mean         28.008556
std           8.175466
min          10.000000
25%          23.500000
50%          28.000000
75%          32.500000
max          46.000000
Name: vitamin_d_level, dtype: float64

In [110]:
Q1 = HealthCare['vitamin_d_level'].quantile(0.25)
Q3 = HealthCare['vitamin_d_level'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 *IQR

print(f'Lower to Upper: {lower} - {upper}')

Lower to Upper: 10.0 - 46.0

In [113]:
HealthCare['vitamin_d_level'] = HealthCare['vitamin_d_level'].clip(lower=10, upper=46)

In [119]:
HealthCare['biomarker_b'].describe()

count    353443.000000
mean         49.970317
std          11.690346
min          25.000000
25%          43.790000
50%          50.000000
75%          56.200000
max          75.000000
Name: biomarker_b, dtype: float64

In [117]:
Q1 = HealthCare['biomarker_b'].quantile(0.25)
Q3 = HealthCare['biomarker_b'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 *IQR

print(f'Lower to Upper: {lower} - {upper}')

Lower to Upper: 25.174999999999994 - 74.81500000000001

In [118]:
HealthCare['biomarker_b'] = HealthCare['biomarker_b'].clip(lower=25, upper=75)

In [123]:
HealthCare.head(15)

,patient_id,age,gender,ethnicity,region,insurance_type,income_bracket,height_cm,weight_kg,bmi,systolic_bp,diastolic_bp,heart_rate,cholesterol_total,ldl,hdl,glucose_fasting,hba1c,smoking_status,alcohol_consumption,physical_activity_level,family_history_diabetes,family_history_heart_disease,white_blood_cell_count,red_blood_cell_count,platelet_count,crp_level,vitamin_d_level,gene_marker_score,biomarker_a,biomarker_b,num_chronic_conditions,num_prior_hospital_visits,medication_count,admission_type,department,treatment_type,had_surgery,length_of_stay_days,admission_date,discharge_date,readmitted_30days,total_healthcare_cost
0,158790,39.9,F,Other,West,Medicare,Undisclosed,152.80000,90.3,38.675955,133.0,70.0,80.0,212.0,106.0,59.0,125.0,5.982578,Never,Moderate,Light,0,0,7.055,3.20,190.0,2.79,26.95,32.92,1.70,38.11,1,2,1.0,Emergency,Emergency,Medication,0,3,2022-01-24,2022-01-27,1,2778.44
1,314295,17.7,M,Other,Northeast,Medicare,100k-150k,172.90000,88.3,29.500000,114.0,71.0,66.0,219.0,131.0,68.0,98.0,5.041812,Unknown,Unknown,Sedentary,1,0,6.950,5.11,281.0,8.84,27.00,29.68,5.00,44.00,0,1,0.0,Elective,Orthopedics,Combination,0,2,2022-02-20,2022-02-22,0,2102.12
2,173610,55.5,F,Hispanic,South,Private,25k-50k,173.00000,69.0,23.100000,113.0,65.0,66.0,193.0,112.0,75.0,112.0,5.529617,Current,Unknown,Moderate,1,0,7.610,5.76,295.0,4.49,35.90,31.48,4.00,48.00,0,2,2.0,Newborn,Pediatrics,Medication,0,0,2023-10-14,2023-10-14,0,1452.31
3,296884,32.4,M,Hispanic,Northeast,Uninsured,50k-75k,173.80000,95.3,31.500000,118.0,64.0,70.0,210.0,118.0,56.0,95.0,4.937282,Never,Heavy,Light,0,0,7.120,4.97,286.0,4.49,29.10,21.80,5.33,54.51,1,0,1.0,Emergency,Emergency,Therapy,0,0,2022-12-11,2022-12-11,0,2005.37
4,223935,49.5,M,Unknown,Midwest,Private,25k-50k,182.90000,78.4,23.400000,138.0,78.0,74.0,208.0,119.0,67.0,103.0,5.216028,Former,Light,Active,0,1,7.830,4.35,276.0,11.84,11.10,43.75,1.36,58.40,0,2,0.0,Emergency,General medicine,Medication,0,4,2020-05-06,2020-05-10,1,2207.07
5,332159,52.3,F,White,Midwest,Uninsured,25k-50k,166.90000,64.6,23.200000,126.0,71.0,76.0,246.0,127.0,66.0,112.0,5.529617,Former,Light,Moderate,0,1,7.690,3.35,287.0,8.36,39.30,41.02,7.02,54.00,0,1,0.0,Emergency,Oncology,Therapy,0,1,2020-02-09,2020-02-10,0,1805.02
6,14143,6.9,F,Black,Midwest,Medicaid,100k-150k,172.80000,71.2,23.800000,111.0,77.0,83.0,215.0,140.0,54.0,104.0,5.250871,Never,Light,Light,0,1,8.270,4.55,175.0,6.50,30.90,19.73,2.39,51.00,0,0,0.0,Urgent,Oncology,Medication,0,2,2020-08-20,2020-08-22,0,2217.61
7,26611,22.0,F,Asian,Northeast,Medicare,25k-50k,163.10000,67.8,25.500000,114.0,61.0,84.0,243.0,129.0,56.0,112.0,5.529617,Former,Light,Light,1,0,8.120,5.78,158.0,7.36,22.25,48.13,5.47,50.00,1,4,0.0,Emergency,Emergency,Medication,0,0,2022-01-30,2022-01-30,0,2205.64
8,115623,42.5,F,Asian,Northeast,Uninsured,Undisclosed,171.60000,96.9,32.900000,134.0,90.0,82.0,275.0,119.0,54.0,134.0,6.296167,Never,Light,Moderate,0,0,5.450,4.46,293.0,8.46,30.50,53.93,1.67,51.03,2,6,0.0,Emergency,Oncology,Surgery,1,3,2023-11-21,2023-11-24,1,5191.19
9,222889,32.4,F,Hispanic,Midwest,Medicare,50k-75k,155.90000,69.2,28.500000,139.0,66.0,63.0,158.0,103.0,68.0,91.0,4.797909,Never,Unknown,Light,1,0,7.300,4.69,289.0,4.79,29.10,42.09,2.17,42.55,1,6,1.0,Elective,Surgery,Medication,0,1,2024-11-29,2024-11-30,1,2728.30
10,109095,51.6,NON-BINARY,Hispanic,Northeast,Medicaid,<25k,169.23978,67.4,27.100000,140.0,80.0,74.0,217.0,109.0,56.0,96.0,4.972125,Never,Moderate,Sedentary,1,1,7.390,5.16,236.0,4.49,28.80,50.30,3.21,34.32,2,5,0.0,Elective,Oncology,Surgery,1,2,2021-02-21,2021-02-23,0,2712.79
11,264612,28.3,F,White,Midwest,Private,50k-75k,152.80000,65.8,28.200000,108.0,84.0,83.0,195.0,124.0,67.0,85.0,4.588850,Current,Unknown,Unknown,0,0,6.200,5.47,201.0,1.89,27.10,24.60,0.69,51.09,0,1,1.0,Elective,Emergency,Medication,0,3,2024-08-16,2024-08-19,0,2516.84
12,345858,55.9,M,Hispanic,West,Va,25k-50k,167.00000,98.1,35.200000,138.0,86.0,86.0,214.0,209.0,65.0,115.0,5.634146,Current,Light,Sedentary,0,1,4.760,5.26,249.0,2.42,27.50,38.04,4.45,41.95,5,2,3.0,Urgent,Surgery,Surgery,1,5,2024-01-03,2024-01-08,1,6843.19
13,101714,67.2,M,Asian,West,Medicaid,50k-75k,189.10000,64.6,18.100000,143.0,85.0,78.0,237.0,148.0,56.0,123.0,5.912892,Never,Unknown,Sedentary,1,0,4.830,5.22,150.0,8.52,18.40,37.58,5.00,59.94,5,6,3.0,Emergency,Pediatrics,Medication,0,3,2022-12-30,2023-01-02,0,3623.08
14,193475,72.3,F,White,South,Uninsured,50k-75k,161.30000,72.5,27.900000,141.0,85.0,87.0,177.0,110.0,54.0,93.0,4.867596,Never,Light,Light,1,0,7.150,4.80,307.0,4.49,29.10,41.41,5.33,56.00,2,7,3.0,Urgent,Cardiology,Medication,0,0,2020-01-25,2020-01-25,0,2523.95

In [ ]:
HealthCare.to_csv('../data/cleaned/Healt')