In [2]:
import pandas as pd
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 500)

In [5]:
Laptops_df = pd.read_csv('../data/raw/Laptops_Dataset.csv')
Laptops_df.head(10)

,Unnamed: 0,Name,Discounted Price,Actual Price,Saving,Rating,Reviews,Brand,Core,SSD,Model
0,0,Apple MacBook Air 13 M1 MGN63 (8GB-256GB),203499.0,258000.0,21% OFF,5.0,2.0,Apple,M1,NaN,MacBook Air 13 M1 MGN63
1,1,Apple Macbook Air 13 MW123 M4 Chip,281999.0,350000.0,19% OFF,4.3,5.0,Apple,M4,NaN,Macbook Air 13 MW123 M4 Chip
2,2,ASUS Zenbook 14 UX3405CA Intel Core Ultra 7 25...,285999.0,330000.0,13% OFF,NaN,NaN,ASUS,Ultra 7,16GB-512GB SSD,Zenbook 14 UX3405CA Intel Core Ultra 7 255H
3,3,Lenovo ThinkPad E16 Gen 2 - Intel Core Ultra 7...,287999.0,340000.0,15% OFF,NaN,NaN,Lenovo,Ultra 7,NaN,ThinkPad E16 Gen 2 - Intel Core Ultra 7
4,4,Lenovo IdeaPad Slim 3 Ryzen 7 (8GB-512GB),146999.0,175000.0,16% OFF,NaN,NaN,Lenovo,Ryzen 7,NaN,IdeaPad Slim 3 Ryzen 7
5,5,HP 250 G10 Ci3 N305 (8GB-512GB SSD),115999.0,144999.0,20% OFF,NaN,NaN,HP,NaN,8GB-512GB SSD,250 G10 Ci3 N305
6,6,Dell Latitude 3540 Ci5-1335U (8GB-256GB SSD) 1...,169999.0,249999.0,32% OFF,5.0,1.0,Dell,NaN,8GB-256GB SSD,Latitude 3540 Ci5-1335U 15.6 FHD
7,7,Dell Latitude 15 5540 15.6 Inches 13th Gen Cor...,343999.0,415000.0,17% OFF,NaN,NaN,Dell,Core i7,NaN,Latitude 15 5540 15.6 Inches 13th Gen Core i7 DOS
8,8,Dell Latitude 15 3540 15.6 Inches 13th Gen Cor...,251999.0,320000.0,21% OFF,NaN,NaN,Dell,Core i7,NaN,Latitude 15 3540 15.6 Inches 13th Gen Core i7 DOS
9,9,Lenovo IdeaPad Slim 3 Core i5 13th Gen,134999.0,174999.0,23% OFF,5.0,2.0,Lenovo,Core i5,NaN,IdeaPad Slim 3 Core i5 13th Gen

In [6]:
Laptops_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306 entries, 0 to 305
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        306 non-null    int64
 1   Name              306 non-null    object
 2   Discounted Price  306 non-null    float64
 3   Actual Price      291 non-null    float64
 4   Saving            291 non-null    object
 5   Rating            26 non-null     float64
 6   Reviews           26 non-null     float64
 7   Brand             306 non-null    object
 8   Core              219 non-null    object
 9   SSD               92 non-null     object
 10  Model             306 non-null    object
dtypes: float64(4), int64(1), object(6)
memory usage: 26.4+ KB

In [7]:
Laptops_df.describe()

       Unnamed: 0  Discounted Price  Actual Price     Rating    Reviews
count  306.000000      3.060000e+02  2.910000e+02  26.000000  26.000000
mean   152.500000      2.775879e+05  3.212616e+05   4.753846   1.615385
std     88.478811      1.708020e+05  1.802598e+05   0.572874   1.134087
min      0.000000      8.599900e+04  1.119990e+05   3.000000   1.000000
25%     76.250000      1.742490e+05  2.000000e+05   5.000000   1.000000
50%    152.500000      2.344990e+05  2.800000e+05   5.000000   1.000000
75%    228.750000      3.449998e+05  3.800000e+05   5.000000   2.000000
max    305.000000      1.552999e+06  1.599900e+06   5.000000   5.000000

In [8]:
for column in Laptops_df.columns :
    print(f'....Describing column {column}')
    print(Laptops_df[column].describe())
    print('\n')

....Describing column Unnamed: 0
count    306.000000
mean     152.500000
std       88.478811
min        0.000000
25%       76.250000
50%      152.500000
75%      228.750000
max      305.000000
Name: Unnamed: 0, dtype: float64


....Describing column Name
count                                           306
unique                                          306
top       Apple MacBook Air 13 M1 MGN63 (8GB-256GB)
freq                                              1
Name: Name, dtype: object


....Describing column Discounted Price
count    3.060000e+02
mean     2.775879e+05
std      1.708020e+05
min      8.599900e+04
25%      1.742490e+05
50%      2.344990e+05
75%      3.449998e+05
max      1.552999e+06
Name: Discounted Price, dtype: float64


....Describing column Actual Price
count    2.910000e+02
mean     3.212616e+05
std      1.802598e+05
min      1.119990e+05
25%      2.000000e+05
50%      2.800000e+05
75%      3.800000e+05
max      1.599900e+06
Name: Actual Price, dtype: float64


....Describing column Saving
count         291
unique         36
top       10% OFF
freq           21
Name: Saving, dtype: object


....Describing column Rating
count    26.000000
mean      4.753846
std       0.572874
min       3.000000
25%       5.000000
50%       5.000000
75%       5.000000
max       5.000000
Name: Rating, dtype: float64


....Describing column Reviews
count    26.000000
mean      1.615385
std       1.134087
min       1.000000
25%       1.000000
50%       1.000000
75%       2.000000
max       5.000000
Name: Reviews, dtype: float64


....Describing column Brand
count     306
unique     11
top        HP
freq      110
Name: Brand, dtype: object


....Describing column Core
count         219
unique         17
top       Core i7
freq           50
Name: Core, dtype: object


....Describing column SSD
count                 92
unique                11
top       16GB-512GB SSD
freq                  34
Name: SSD, dtype: object


....Describing column Model
count                                                  306
unique                                                 303
top       Thinkbook 15 G2 15.6 Inches 11th Gen Core i7 DOS
freq                                                     2
Name: Model, dtype: object

In [9]:
for column in Laptops_df.columns :
    print(f'....Counting unique values of column {column}')
    print(Laptops_df[column].value_counts())
    print('\n')

....Counting unique values of column Unnamed: 0
Unnamed: 0
0      1
201    1
208    1
207    1
206    1
205    1
204    1
203    1
202    1
200    1
229    1
199    1
198    1
197    1
196    1
195    1
194    1
193    1
209    1
210    1
211    1
212    1
227    1
226    1
225    1
224    1
223    1
222    1
221    1
220    1
219    1
218    1
217    1
216    1
215    1
214    1
213    1
192    1
191    1
190    1
171    1
169    1
168    1
167    1
166    1
165    1
164    1
163    1
162    1
161    1
160    1
159    1
158    1
157    1
156    1
155    1
170    1
172    1
189    1
173    1
188    1
187    1
186    1
185    1
184    1
183    1
182    1
181    1
180    1
179    1
178    1
177    1
176    1
175    1
174    1
228    1
230    1
1      1
278    1
285    1
284    1
283    1
282    1
281    1
280    1
279    1
277    1
231    1
276    1
275    1
274    1
273    1
272    1
271    1
270    1
286    1
287    1
288    1
289    1
304    1
303    1
302    1
301    1
300    1
299    1
298    1
297    1
296    1
295    1
294    1
293    1
292    1
291    1
290    1
269    1
268    1
267    1
248    1
246    1
245    1
244    1
243    1
242    1
241    1
240    1
239    1
238    1
237    1
236    1
235    1
234    1
233    1
232    1
247    1
249    1
266    1
250    1
265    1
264    1
263    1
262    1
261    1
260    1
259    1
258    1
257    1
256    1
255    1
254    1
253    1
252    1
251    1
154    1
153    1
152    1
48     1
55     1
54     1
53     1
52     1
51     1
50     1
49     1
47     1
151    1
46     1
45     1
44     1
43     1
42     1
41     1
40     1
56     1
57     1
58     1
59     1
74     1
73     1
72     1
71     1
70     1
69     1
68     1
67     1
66     1
65     1
64     1
63     1
62     1
61     1
60     1
39     1
38     1
37     1
18     1
16     1
15     1
14     1
13     1
12     1
11     1
10     1
9      1
8      1
7      1
6      1
5      1
4      1
3      1
2      1
17     1
19     1
36     1
20     1
35     1
34     1
33     1
32     1
31     1
30     1
29     1
28     1
27     1
26     1
25     1
24     1
23     1
22     1
21     1
75     1
76     1
77     1
133    1
131    1
130    1
129    1
128    1
127    1
126    1
125    1
124    1
123    1
122    1
121    1
120    1
119    1
118    1
117    1
132    1
134    1
115    1
135    1
150    1
149    1
148    1
147    1
146    1
145    1
144    1
143    1
142    1
141    1
140    1
139    1
138    1
137    1
136    1
116    1
114    1
78     1
95     1
93     1
92     1
91     1
90     1
89     1
88     1
87     1
86     1
85     1
84     1
83     1
82     1
81     1
80     1
79     1
94     1
96     1
113    1
97     1
112    1
111    1
110    1
109    1
108    1
107    1
106    1
105    1
104    1
103    1
102    1
101    1
100    1
99     1
98     1
305    1
Name: count, dtype: int64


....Counting unique values of column Name
Name
Apple MacBook Air 13 M1 MGN63 (8GB-256GB)                                                  1
LENOVO THINKPAD E14 G6 14TH Intel Core Ultra 7 155H (16GB-512GB SSD)                       1
LENOVO LOQ 15 Ci5 13450HX                                                                  1
Dell Latitude 3550 Raptor Lake 13th Gen Core i5 1335U (8GB-512GB SSD)                      1
Apple MacBook Air 15 MW1K3 M4 Chip                                                         1
Lenovo loq 15 13th Core i5 13450hx (24GB-512GB) DOS                                        1
HP OMNIBOOK 14 FP0013DX Core 5 120U (8GB-512GB)                                            1
LENOVO THINKPAD T14 14TH GEN Intel Core Ultra 7 155U (32GB-512GB SSD)                      1
LENOVO THINKPAD T14 14TH GEN Intel Core Ultra 7 155U (16GB-512GB SSD)                      1
Dell Latitude 5440 13TH GEN CORE i7 1355U (8GB-512GB SSD)                                  1
Apple MacBook Air 15.3 M2 MQKX3 (8GB-512GB)                                                1
Acer Nitro V16 14th Gen Core i7 14650HX (16GB-512GB SSD)                                   1
Acer Nitro V15 13th Gen Core i9 13900H (16GB-512GB SSD) RTX 4060 8GB Graphics              1
Acer Nitro V15 - Ci5-13420H (16GB-512GB) RTX 4050 6GB                                      1
Apple MacBook Air MXCV3 M3 8-Core Chip                                                     1
HP Elitebook 660 G11 Ultra 5 125U                                                          1
ASUS EXPERTBOOK B1403CVA Ci7-1355U (16GB -512GB SSD)                                       1
HP Elitebook 650 G10 13th Gen Core I5 1335U                                                1
HP OmniBook Ultra Flip 14-FH0030CA Core Ultra 7 256V (16GB 1TB SSD)                        1
Lenovo ThinkPad X1 Carbon G13 Ultra 7 256V (32GB-512GB SSD)                                1
HP VICTUS 15-FA2013DX Ci5-13420H (8GB 512GB SSD) RTX 3050 6GB                              1
HP VICTUS 15-FA2701WM Ci5-13420H (16GB-512GB SSD) RTX 4050 6GB                             1
HP 15s FQ5098TU 15.6 Inches 12th Gen Core i5 Win 11 (8GB - 512GB)                          1
Apple MacBook Pro A2289 13 Inches Core i5 (8GB-512GB)                                      1
Infinix INBook X2 1065G7 14 Inches Core i7 (8GB RAM - 512GB SSD)                           1
Dell Inspiron 3515 15.6 inches AMD Ryzen 5 3450U (8GB - 256GB)                             1
Apple Macbook Air 13 MW0Y3 M4                                                              1
HP Victus 15-FA2317TX Ci7-13620H (16GB-512GB SSD) RTX 4050 6GB                             1
HP OmniBook 5 16-AF1067ST Ultra 7-255U (16GB-1TB SSD)                                      1
Dell Alienware 16 Aurora Core 7-240H (32GB-1TB SSD) RTX 5060 8GB                           1
Asus VivoBook 16 M1605YA Ryzen 7-7730U (8GB-512GB SSD)                                     1
Dell Latitude 3550 Ultra 5-125U (8GB-512GB SSD)                                            1
Dell Alienware Aurora 16 Core 7 240H (16GB-512GB SSD) RTX 5050 8GB                         1
Lenovo ThinkPad E16 G3 Ultra 5 225U (8GB-512GB SSD)                                        1
Lenovo ThinkPad E14 G8 U7-255H (16GB-512GB SSD)                                            1
ASUS EXPERTBOOK B1403CVA Ci5 1334U (16GB-512GB SSD)                                        1
ACER PREDATOR HELIOS 16 AI Core Ultra 9 275HX (32GB-1TB SSD) RTX 5070Ti 12GB               1
HP 15-FD0229NIA Ci7-1355U (8GB-512GB SSD) 15.6 FHD                                         1
HP 250 G9 12th Gen Core i7 DOS                                                             1
LENOVO LEGION PRO 5 Ci7-14650HX (16GB-1TB) RTX-4060-8GB                                    1
Lenovo V15 G3 15. 6 Inches 12th Gen Core i3 DOS (4GB - 256GB SSD)                          1
Apple MacBook Air MC6T4 M4 Chip                                                            1
Dell 15 DC15250 Ci5-1334U (8GB-512GB SSD)                                                  1
HP Victus 16-R0042NE Ci7-13700H (16GB-1TB SSD) RTX™ 4060 8GB                               1
HP Victus 15-FB3093DX AMD Ryzen 7-7445H (16GB-512GB SSD) RTX 4050 6GB                      1
Lenovo Legion Pro 7 Ultra 9 275HX (64GB-2TB SSD) RTX 5090 24GB 240Hz                       1
Lenovo Legion Pro 7 Ultra 9 275HX (64GB-2TB SSD) RTX 5080 16GB 240Hz                       1
Lenovo Yoga 9 Intel Core Ultra 7 (16GB-1TB SSD)                                            1
ASUS ExpertBook B1502CV 13th Gen Core i5 1355U (8GB-512GB SSD)                             1
Lenovo IdeaPad Slim 5 Core i7 13620H DOS (16GB-512GB SSD)                                  1
Lenovo IdeaPad Slim 3 Ryzen 3 7320U DOS (8GB-256GB SSD)                                    1
Apple Macbook Pro M3 A2918 (8GB-512GB SSD)                                                 1
Acer Nitro V15 13th Gen Core i9 13900H (16GB-512GB SSD)                                    1
Lenovo ThinkPad E14 G6 Intel Core Ultra 5 125U (8GB-512GB SSD)                             1
Lenovo Thinkbook 16 G7 14TH GEN Core Ultra 5 125U (8GB-512GB SSD)                          1
Lenovo Thinkbook 14 G7 14TH GEN Core Ultra 7 155H (8GB-512GB SSD)                          1
Lenovo LOQ 15 Ryzen 5 7235HS (12GB-512GB SSD) RTX 4050 6GB                                 1
Lenovo ThinkPad E14 G4 14 Inches 12th Gen Core i5 DOS (8GB - 512GB)                        1
HP Elitebook 660 G11 U7 | Intel® Core™ Ultra 7 155U (8GB-512GB)                            1
Lenovo V15 G3 15.6 Inches 12th Gen Core i7 DOS (8GB - 512GB)                               1
HP EliteBook 640 G11 14 Ultra 7 155U (8GB-512GB)                                           1
HP ProBook 460 G11 Intel Core Ultra 5 125U (8GB-512GB)                                     1
HP ProBook 460 G11 Ultra 7 155U                                                            1
HP VICTUS 15-FA2701WM Ci5-13420H (16GB -512GB) RTX-4050-6GB                                1
HP 250 G10 13th Gen Core i3 DOS                                                            1
Lenovo V15 G4 Core i7 13th Gen (8GB-512GB)                                                 1
LENOVO THINBOOK 16 13TH CI5 8GB/256GB 16INCH                                               1
Lenovo V15 G4 Core i3 13th Gen                                                             1
HP Pavilion x360 14 EK1056TU  Core i7 (16GB-1TB)                                           1
HP 250 G10 Raptor Lake 13th Gen Core i7 (8GB-512GB)                                        1
Apple Macbook Pro 14 MTL73 (8GB-512GB)                                                     1
Apple MacBook Pro 14.2” MTL83 (8GB-1TB)                                                    1
Apple Macbook Pro MRX33 M3 Pro 14.2 (18GB-512GB)                                           1
HP ProBook 440 G10 Core i7 (8GB-512GB NVMe SSD)                                            1
Lenovo V15 G3 15.6 Inches 12th Gen Core i5 DOS (4GB - 256GB)                               1
Dell Inspiron 3520 Core i7 12th Gen (8GB-512GBSSD)                                         1
HP 15 FD0336nia 13th Gen Core i3 (4GB-256GB)                                               1
Apple Macbook Air 13 MW123 M4 Chip                                                         1
HP 15s FQ5099TU 15.6 Inches 12th Gen Core i7 Win 11 (8GB - 512GB)                          1
HP Pavilion 15 EH3050au - AMD Ryzen 7 7730U Octa Core (16GB-1TB)                           1
Apple MACBOOK AIR 13” M3 CHIP MRXV3 8-256                                                  1
ASUS Expertbook B1402CVA 13th Gen Core i7 (16GB-512GB)                                     1
DELL Vostro 15 3520 Laptop 12th Gen Core i5                                                1
HP 250 G9 15.6 Inches 12th Gen core i5 DOS (8GB - 512GB)                                   1
Lenovo Ideapad 3 15.6 Inches 11th Gen Core i7 DOS (8GB - 1TB)                              1
Lenovo Ideapad 5 15.6 Inches 11th Gen Core i5 DOS (8GB - 512GB)                            1
Lenovo IdeaPad Slim 5 Core i5 13420H DOS (16GB-512GB SSD)                                  1
Lenovo IdeaPad 5 Core i7 12th Gen (16GB-512GB)                                             1
Acer Predator Helios Neo PHN14-51-97X1 Intel Core Ultra 9-185H (32GB-1TB SSD)              1
Apple MacBook Air 15 Inches With M3 Chip (MXD43)                                           1
Asus Zenbook 14 Q425MA Core Ultra 7 155H                                                   1
HP Envy x360 2 in 1 14 FC0023DX Core Ultra 7 Laptop                                        1
HP Envy 16-H1053DX 13th Gen Core i7-13700H (16GB-1TB)                                      1
HP 15s EQ2174AU 15.6 Inches Ryzen 5 (8GB-512GB)                                            1
HP 15-FB1000CA Ryzen 5 15.6 inches (16GB-1TB)                                              1
HP Envy 2 in 1 16 AC0023dx Intel Core Ultra 7 155U Processor (16GB-1tb)                    1
HP 15s FD0110TU - Raptor Lake - 13th Gen Core i7 (16GB-512GB)                              1
Lenovo ThinkPad E14 Gen 4 Ryzen 5 DOS                                                      1
Apple MacBook Air MRXN3 M3 8-Core Chip                                                     1
ASUS TUF FX507ZC4-HN129 12th Gen Core i5 (8GB-512GB)                                       1
ASUS Expertbook B1500CBA 12th Gen Core i7 (16GB-512GB)                                     1
Infinix GT BOOK Core i9 13900H (32GB - 1TB)                                                1
ASUS TUF FX507ZV4-LP349 12th Gen Core i7 (16GB-512GB)                                      1
ASUS TUF FX507ZC4-HN153 12th Gen Core i7 (16GB-512GB)                                      1
ASUS Expertbook B1402CBA 12th Gen Core i5 (8GB-512GB)                                      1
Lenovo Thinkpad E15 15.6 Inches Core i5 (8GB RAM - 512GB HDD)                              1
ASUS TUF FX507ZC4-HN096 12th Gen Core i5 (16GB-512GB)                                      1
ASUS Expertbook B3402FB 12th gen Core i7 (16GB-512GB)                                      1
Lenovo ThinkPad E15 15.6 Inches AMD Ryzen 7 (08GB RAM - 512GB SSD)                         1
ASUS ROG Zephyrus G14 GA403UM Ryzen 9-270 (16GB-1TB SSD) RTX 5060 8GB                      1
Acer Predator Helios Neo PH16-72-97T1 Intel Core i9-14900HX (32GB-1TB SSD)                 1
Acer Predator Helios Neo PH16-72-99PA Intel Core i9-14900HX (32GB-1TB SSD)                 1
Dell Inspiron 3535 AMD Ryzen 7-7730U (16GB-512GB SSD)                                      1
Dell Inspiron 15 3530 13th Gen Core i7 1355U (16GB-512GB SSD)                              1
HP 15S-FQ5340TU Core i3 12th Gen (8GB-256GB)                                               1
DELL Vostro 15 3520 Laptop 12th Gen Core i3                                                1
HP Laptop 15S FQ5276NIA i3 12th Gen (4GB-256GB)                                            1
HP 15 FD0240TU 13th Gen Core i5 1334u (8GB-512GB)                                          1
HP Envy 14-ES0013DX 13th Gen Core i5-1335U (8GB DDR4-512GB SSD)                            1
HP 15-DY5131WM Laptop 12thGen Core i3 (8GB RAM, 256GB SSD)                                 1
HP 15s FD0107TU 15.6 Inches 13th Gen Core i5 1335u Win 11 (8GB - 512GB)                    1
HP Pavilion 15 EH2032au 15.6 Inches AMD Ryzen 5 5625U Win 11 (16GB - 512GB)                1
HP Pavilion 15 EH2033au 15.6 Inches AMD Ryzen 7 5825U Win 11 (16GB - 1TB)                  1
Dell 15 DC15250 Core 3-100U (8GB-512GB SSD)                                                1
HP EliteBook 840 G11 Ultra 7-155U vPro (16GB-512GB SSD)                                    1
HP OmniBook 5 16-AF1095CL Core Ultra 9 285H (32GB 1TB)                                     1
Acer Nitro V16 AMD RYZEN 7 8845HS (16GB-512GB SSD)                                         1
Acer Nitro V15 13th Gen Core i7-13620H (16GB-512GB SSD) RTX 4060 8GB Graphics              1
Apple Macbook Air 15 MC7C4 M4 Chip                                                         1
Dell Vostro 3530 Ci3-1305U (8GB-512GB SSD)                                                 1
Apple MacBook Air 15 Inches With M3 Chip (MRYV3)                                           1
ASUS ExpertBook B1 502CB 12th Ci5 235U                                                     1
HP VICTUS 16-R0003NIA Ci7-13700H (32GB -1TB SSD) RTX 4060 8GB                              1
Dell Vostro 3520 12th Gen Core i3 15.6 inches (8GB-512GB)                                  1
HP Envy 16 AC0013DX Ultra 5 125U                                                           1
Infinix INBook Y1 Plus Laptop Core i3 (8GB-256GB SSD) International                        1
ASUS ZenBook 14 Q415MA Core Ultra 5 125H                                                   1
HP DU3572TU 15.6 Inches Core i5 11thGen (8GB RAM - 512GBSSD)                               1
HP Victus 15-FB2146AX R7-8845HS (16GB-512GB SSD) RTX 4060 8GB                              1
Acer Predator Helios Neo PH16-72-903U Intel Core i9-14900HX (32GB-1TB SSD)                 1
HP Spectre x360 14-EF2051TU 13th Gen 1355U                                                 1
HP VICTUS 15-FB2082WM R5-8645HS (8GB-512GB SSD) RTX-4050-6GB                               1
HP 15S-EQ2315AU Laptop AMD Ryzen 7-5700U 8GB-512GB                                         1
HP Victus 15-FA0212TX Gaming Laptop 12th Gen Core i7-12650H (16GB-512GB)                   1
Dell Vostro 3520 12th Gen Core i5 15.6 inches (8GB-512GB)                                  1
HP 15s EQ2174AU AMD Ryzen 5 5500U (8GB 512GB)                                              1
HP 15S-FQ5299NIA Laptop 12th Gen Core i7 (8GB-512GB SSD)                                   1
HP 15S-FQ5317TU Laptop 12th Gen Core i5 (8GB-512GB)                                        1
HP 15s FQ5096TU 15.6 Inches 12th Gen Core i3 Win 11 (4GB - 256GB)                          1
Infinix INBook X2 1035G1 14 Inches Core i5 (8GB RAM - 512GB SSD)                           1
LENOVO LOQ 15 Ci5 12450HX                                                                  1
Dell Inspiron 16 5640 Core i5-1334U (16GB-512GB SSD)                                       1
Lenovo Thinkbook 14 G7 14th Gen Core Ultra 5 125U (8GB DDR5 512GB SSD)                     1
Dell Inspiron 16 5640 Intel Core 7-150U (16GB-1TB SSD)                                     1
Infinix GTBOOK 13th Generation Core i9 13900H 1TB-32GB                                     1
HP Envy 16 H1008TX 16 Inches 13th Gen Core i5 Win 11 (16GB - 512GB)                        1
Lenovo ThinkPad E14 G5 13th Gen Core i7 1355U (8GB-512GB)                                  1
HP ENVY 14-ES1013DX 14th Gen Core 5 120U (8GB-512GB SSD) x360 Touch                        1
HP ProBook 440 G10 13th Gen Core i5 14 inches (8GB-512GB)                                  1
HP Spectre 14-EU0008NI Ultra 7 (16GB 1TB) Oled Plus HP PEN                                 1
Lenovo ThinkBook16 - Ci5-1335U (8GB 512GB)                                                 1
Apple MACBOOK AIR 13.6” M2 CHIP MLY43 8-512GB                                              1
Apple Macbook Pro MRX33 M3 Pro 14 (18GB-512GB) Black                                       1
HP Pavilion 15 EG3002TX 15.6 Inches 13th Gen Core i5 Win 11 (8GB - 512GB)                  1
Apple MacBook Air MRXW3 M3 Chip                                                            1
HP Pavilion X360 14 EK1055TU 14 Inches 13th Gen Core i5 Win 11 Home (8GB - 512GB)          1
HP Probook 450 G9 15.6 Inches 12th Gen Core i7 DOS (8GB - 512GB) Local                     1
Lenovo ThinkPad E15 G4 15.6 Inches 12th Gen Core i7 Backlit Keyboard DOS (8GB - 512GB)     1
HP Laptop EQ2180AU 15.6 Inches AMD Ryzen 5 (8GB RAM - 512GBSSD)                            1
HP OMNIBOOK ULTRA FLIP 14-FH0033DX ULTRA 9-288V (32GB-2TB SSD)                             1
HP 15-FD0647TU Ci5-1334U (8GB-512GB SSD)                                                   1
Lenovo Legion 5 16IAX10 Core Ultra 9-275HX (32GB-1TB SSD) RTX 5060 8GB                     1
HP Spectre 2-in-1 X360 16-F2013DX 13th Gen Core i7                                         1
Dell Vostro 15 3530 13th Gen Core i5 1334u                                                 1
Lenovo ThinkPad E16 Gen 2 - Intel Core Ultra 5 (8GB-512GB)                                 1
Lenovo Thinkpad  T14 13th Gen Core I7 DOS                                                  1
ASUS TUF GAMING A14 FA-401WU RYZEN AI 9 HX370 (32GB-1TB SSD) RTX 4050 6GB                  1
ASUS TUF GAMING F15-FX507VV Ci7-13620H (16GB-512GB SSD) RTX 4060 8GB                       1
Lenovo Legion Pro 5 Ultra 9-275HX (32GB-1TB SSD) RTX 5070 8GB                              1
Lenovo Legion 5 Ci7-14650HX (16GB-1TB SSD) RTX 4050 6GB                                    1
HP 15S-FQ5000NIA Ci3-1215U (4GB, 256GB SSD)                                                1
LENOVO LOQ 15 Core i7 14650HX                                                              1
LENOVO LOQ 15 Ci7 13650HX                                                                  1
HP Laptop 15-FD0532NIA Intel Core i3-1315U 13th Gen (4GB-256GB)                            1

In [10]:
Laptops_df.isnull().sum()

Unnamed: 0            0
Name                  0
Discounted Price      0
Actual Price         15
Saving               15
Rating              280
Reviews             280
Brand                 0
Core                 87
SSD                 214
Model                 0
dtype: int64

In [11]:
Laptops_df.duplicated().sum()

0