In [2]:
import pandas as pd
import re
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 500)

In [3]:
Laptops_df = pd.read_csv('../data/raw/Laptops_Dataset.csv')
Laptops_df.head(10)

,Unnamed: 0,Name,Discounted Price,Actual Price,Saving,Rating,Reviews,Brand,Core,SSD,Model
0,0,Apple MacBook Air 13 M1 MGN63 (8GB-256GB),203499.0,258000.0,21% OFF,5.0,2.0,Apple,M1,NaN,MacBook Air 13 M1 MGN63
1,1,Apple Macbook Air 13 MW123 M4 Chip,281999.0,350000.0,19% OFF,4.3,5.0,Apple,M4,NaN,Macbook Air 13 MW123 M4 Chip
2,2,ASUS Zenbook 14 UX3405CA Intel Core Ultra 7 25...,285999.0,330000.0,13% OFF,NaN,NaN,ASUS,Ultra 7,16GB-512GB SSD,Zenbook 14 UX3405CA Intel Core Ultra 7 255H
3,3,Lenovo ThinkPad E16 Gen 2 - Intel Core Ultra 7...,287999.0,340000.0,15% OFF,NaN,NaN,Lenovo,Ultra 7,NaN,ThinkPad E16 Gen 2 - Intel Core Ultra 7
4,4,Lenovo IdeaPad Slim 3 Ryzen 7 (8GB-512GB),146999.0,175000.0,16% OFF,NaN,NaN,Lenovo,Ryzen 7,NaN,IdeaPad Slim 3 Ryzen 7
5,5,HP 250 G10 Ci3 N305 (8GB-512GB SSD),115999.0,144999.0,20% OFF,NaN,NaN,HP,NaN,8GB-512GB SSD,250 G10 Ci3 N305
6,6,Dell Latitude 3540 Ci5-1335U (8GB-256GB SSD) 1...,169999.0,249999.0,32% OFF,5.0,1.0,Dell,NaN,8GB-256GB SSD,Latitude 3540 Ci5-1335U 15.6 FHD
7,7,Dell Latitude 15 5540 15.6 Inches 13th Gen Cor...,343999.0,415000.0,17% OFF,NaN,NaN,Dell,Core i7,NaN,Latitude 15 5540 15.6 Inches 13th Gen Core i7 DOS
8,8,Dell Latitude 15 3540 15.6 Inches 13th Gen Cor...,251999.0,320000.0,21% OFF,NaN,NaN,Dell,Core i7,NaN,Latitude 15 3540 15.6 Inches 13th Gen Core i7 DOS
9,9,Lenovo IdeaPad Slim 3 Core i5 13th Gen,134999.0,174999.0,23% OFF,5.0,2.0,Lenovo,Core i5,NaN,IdeaPad Slim 3 Core i5 13th Gen

In [4]:
Laptops_df.columns

Index(['Unnamed: 0', 'Name', 'Discounted Price', 'Actual Price', 'Saving',
       'Rating', 'Reviews', 'Brand', 'Core', 'SSD', 'Model'],
      dtype='object')

In [5]:
Laptops_df.drop(columns='Unnamed: 0', inplace=True)

In [6]:
Laptops_df.tail(10)

,Name,Discounted Price,Actual Price,Saving,Rating,Reviews,Brand,Core,SSD,Model
296,ASUS Expertbook B3402FB 12th gen Core i7 (16GB...,225000.0,NaN,NaN,NaN,NaN,ASUS,Core i7,NaN,Expertbook B3402FB 12th gen Core i7
297,ASUS TUF FX507ZC4-HN096 12th Gen Core i5 (16GB...,260000.0,NaN,NaN,NaN,NaN,ASUS,Core i5,NaN,TUF FX507ZC4-HN096 12th Gen Core i5
298,Lenovo Thinkpad E15 15.6 Inches Core i5 (8GB R...,153000.0,NaN,NaN,NaN,NaN,Lenovo,Core i5,NaN,Thinkpad E15 15.6 Inches Core i5
299,ASUS Expertbook B1402CBA 12th Gen Core i5 (8GB...,155000.0,NaN,NaN,NaN,NaN,ASUS,Core i5,NaN,Expertbook B1402CBA 12th Gen Core i5
300,ASUS TUF FX507ZC4-HN153 12th Gen Core i7 (16GB...,300000.0,NaN,NaN,NaN,NaN,ASUS,Core i7,NaN,TUF FX507ZC4-HN153 12th Gen Core i7
301,ASUS TUF FX507ZV4-LP349 12th Gen Core i7 (16GB...,345000.0,NaN,NaN,NaN,NaN,ASUS,Core i7,NaN,TUF FX507ZV4-LP349 12th Gen Core i7
302,Infinix GT BOOK Core i9 13900H (32GB - 1TB),442999.0,NaN,NaN,NaN,NaN,Infinix,Core i9,NaN,GT BOOK Core i9 13900H
303,ASUS Expertbook B1500CBA 12th Gen Core i7 (16G...,205000.0,NaN,NaN,NaN,NaN,ASUS,Core i7,NaN,Expertbook B1500CBA 12th Gen Core i7
304,ASUS TUF FX507ZC4-HN129 12th Gen Core i5 (8GB-...,255000.0,NaN,NaN,NaN,NaN,ASUS,Core i5,NaN,TUF FX507ZC4-HN129 12th Gen Core i5
305,Asus ROG Zephyrus G15 GA503QR 15.6 Inches Ryze...,399900.0,NaN,NaN,NaN,NaN,Asus,Ryzen 9,NaN,ROG Zephyrus G15 GA503QR 15.6 Inches Ryzen 9 5...

In [7]:
Laptops_df.dropna(subset=['Actual Price'], inplace=True)

In [8]:
Laptops_df.isnull().sum()

Name                  0
Discounted Price      0
Actual Price          0
Saving                0
Rating              265
Reviews             265
Brand                 0
Core                 87
SSD                 203
Model                 0
dtype: int64

In [9]:
Laptops_df[['Rating', 'Reviews']] = Laptops_df[['Rating', 'Reviews']].fillna(0.0)

In [10]:
Laptops_df.isnull().sum()
Laptops_df[['Rating', 'Reviews']] = Laptops_df[['Rating', 'Reviews']].astype('int32')
Laptops_df.tail(10)

,Name,Discounted Price,Actual Price,Saving,Rating,Reviews,Brand,Core,SSD,Model
285,HP Pavilion 15 EH3050au - AMD Ryzen 7 7730U Oc...,198499.0,245000.0,19% OFF,0,0,HP,Ryzen 7,NaN,Pavilion 15 EH3050au - AMD Ryzen 7 7730U Octa ...
286,HP Envy 2 in 1 16 AC0023dx Intel Core Ultra 7 ...,251999.0,299000.0,16% OFF,0,0,HP,Ultra 7,NaN,Envy 2 in 1 16 AC0023dx Intel Core Ultra 7 155...
287,HP 15s FD0110TU - Raptor Lake - 13th Gen Core ...,222999.0,270000.0,17% OFF,0,0,HP,Core i7,NaN,15s FD0110TU - Raptor Lake - 13th Gen Core i7
288,Lenovo ThinkPad E14 Gen 4 Ryzen 5 DOS,141999.0,180000.0,21% OFF,0,0,Lenovo,Ryzen 5,NaN,ThinkPad E14 Gen 4 Ryzen 5 DOS
289,Apple MacBook Air MRXN3 M3 8-Core Chip,288999.0,300000.0,4% OFF,0,0,Apple,M3,NaN,MacBook Air MRXN3 M3 8-Core Chip
290,Dell Inspiron 15 3530 13th Gen Core i7 1355U (...,189999.0,219999.0,14% OFF,0,0,Dell,Core i7,16GB-512GB SSD,Inspiron 15 3530 13th Gen Core i7 1355U
291,Dell Inspiron 3535 AMD Ryzen 7-7730U (16GB-512...,134499.0,142999.0,6% OFF,0,0,Dell,Ryzen 7,16GB-512GB SSD,Inspiron 3535 AMD Ryzen 7-7730U
292,Acer Predator Helios Neo PH16-72-99PA Intel Co...,430999.0,449999.0,4% OFF,0,0,Acer,Core i9,NaN,Predator Helios Neo PH16-72-99PA Intel Core i9...
293,Acer Predator Helios Neo PH16-72-97T1 Intel Co...,781999.0,950000.0,18% OFF,0,0,Acer,Core i9,NaN,Predator Helios Neo PH16-72-97T1 Intel Core i9...
294,ASUS ROG Zephyrus G14 GA403UM Ryzen 9-270 (16G...,499999.0,550000.0,9% OFF,0,0,ASUS,Ryzen 9,NaN,ROG Zephyrus G14 GA403UM Ryzen 9-270 RTX 5060...

In [11]:
Laptops_df['Brand'] = Laptops_df['Brand'].str.title()
Laptops_df['Brand'].value_counts()
Laptops_df.head(10)

,Name,Discounted Price,Actual Price,Saving,Rating,Reviews,Brand,Core,SSD,Model
0,Apple MacBook Air 13 M1 MGN63 (8GB-256GB),203499.0,258000.0,21% OFF,5,2,Apple,M1,NaN,MacBook Air 13 M1 MGN63
1,Apple Macbook Air 13 MW123 M4 Chip,281999.0,350000.0,19% OFF,4,5,Apple,M4,NaN,Macbook Air 13 MW123 M4 Chip
2,ASUS Zenbook 14 UX3405CA Intel Core Ultra 7 25...,285999.0,330000.0,13% OFF,0,0,Asus,Ultra 7,16GB-512GB SSD,Zenbook 14 UX3405CA Intel Core Ultra 7 255H
3,Lenovo ThinkPad E16 Gen 2 - Intel Core Ultra 7...,287999.0,340000.0,15% OFF,0,0,Lenovo,Ultra 7,NaN,ThinkPad E16 Gen 2 - Intel Core Ultra 7
4,Lenovo IdeaPad Slim 3 Ryzen 7 (8GB-512GB),146999.0,175000.0,16% OFF,0,0,Lenovo,Ryzen 7,NaN,IdeaPad Slim 3 Ryzen 7
5,HP 250 G10 Ci3 N305 (8GB-512GB SSD),115999.0,144999.0,20% OFF,0,0,Hp,NaN,8GB-512GB SSD,250 G10 Ci3 N305
6,Dell Latitude 3540 Ci5-1335U (8GB-256GB SSD) 1...,169999.0,249999.0,32% OFF,5,1,Dell,NaN,8GB-256GB SSD,Latitude 3540 Ci5-1335U 15.6 FHD
7,Dell Latitude 15 5540 15.6 Inches 13th Gen Cor...,343999.0,415000.0,17% OFF,0,0,Dell,Core i7,NaN,Latitude 15 5540 15.6 Inches 13th Gen Core i7 DOS
8,Dell Latitude 15 3540 15.6 Inches 13th Gen Cor...,251999.0,320000.0,21% OFF,0,0,Dell,Core i7,NaN,Latitude 15 3540 15.6 Inches 13th Gen Core i7 DOS
9,Lenovo IdeaPad Slim 3 Core i5 13th Gen,134999.0,174999.0,23% OFF,5,2,Lenovo,Core i5,NaN,IdeaPad Slim 3 Core i5 13th Gen

In [12]:
Laptops_df.rename(columns={'Saving': 'Saving(%)'}, inplace=True)
Laptops_df['Saving(%)'] = Laptops_df['Saving(%)'].map(lambda save : save.split('%')[0]).astype('int64')
Laptops_df['Saving(%)'].dtype
Laptops_df.head(10)

,Name,Discounted Price,Actual Price,Saving(%),Rating,Reviews,Brand,Core,SSD,Model
0,Apple MacBook Air 13 M1 MGN63 (8GB-256GB),203499.0,258000.0,21,5,2,Apple,M1,NaN,MacBook Air 13 M1 MGN63
1,Apple Macbook Air 13 MW123 M4 Chip,281999.0,350000.0,19,4,5,Apple,M4,NaN,Macbook Air 13 MW123 M4 Chip
2,ASUS Zenbook 14 UX3405CA Intel Core Ultra 7 25...,285999.0,330000.0,13,0,0,Asus,Ultra 7,16GB-512GB SSD,Zenbook 14 UX3405CA Intel Core Ultra 7 255H
3,Lenovo ThinkPad E16 Gen 2 - Intel Core Ultra 7...,287999.0,340000.0,15,0,0,Lenovo,Ultra 7,NaN,ThinkPad E16 Gen 2 - Intel Core Ultra 7
4,Lenovo IdeaPad Slim 3 Ryzen 7 (8GB-512GB),146999.0,175000.0,16,0,0,Lenovo,Ryzen 7,NaN,IdeaPad Slim 3 Ryzen 7
5,HP 250 G10 Ci3 N305 (8GB-512GB SSD),115999.0,144999.0,20,0,0,Hp,NaN,8GB-512GB SSD,250 G10 Ci3 N305
6,Dell Latitude 3540 Ci5-1335U (8GB-256GB SSD) 1...,169999.0,249999.0,32,5,1,Dell,NaN,8GB-256GB SSD,Latitude 3540 Ci5-1335U 15.6 FHD
7,Dell Latitude 15 5540 15.6 Inches 13th Gen Cor...,343999.0,415000.0,17,0,0,Dell,Core i7,NaN,Latitude 15 5540 15.6 Inches 13th Gen Core i7 DOS
8,Dell Latitude 15 3540 15.6 Inches 13th Gen Cor...,251999.0,320000.0,21,0,0,Dell,Core i7,NaN,Latitude 15 3540 15.6 Inches 13th Gen Core i7 DOS
9,Lenovo IdeaPad Slim 3 Core i5 13th Gen,134999.0,174999.0,23,5,2,Lenovo,Core i5,NaN,IdeaPad Slim 3 Core i5 13th Gen

In [13]:
Laptops_df[Laptops_df['Core'].isnull()]['Name']

5                    HP 250 G10 Ci3 N305 (8GB-512GB SSD)
6      Dell Latitude 3540 Ci5-1335U (8GB-256GB SSD) 1...
14     HP OMEN 16-WD0073dx Ci7-13620H (16GB - 1TB) RT...
17     HP OMEN 16-AP0167AX R9-8940HX (16GB - 512GB) R...
19             HP 15-FD0499NIA Ci5-1334U (8GB 512GB SSD)
22        Dell Inspiron 14 7440 2 in 1 Intel Core 5 120U
30     LENOVO THINKPAD E14 G4 13TH GEN Intel Core I7 ...
31     Lenovo legion 5 14th core i7 14650hx (16GB-1TB...
34                             LENOVO LOQ 15 CI7-14650HX
36     ASUS TUF GAMING F15-FX507VU Ci7-13620H (16GB-5...
38     ASUS TUF F16 FX608JMR Ci7 14650HX (32GB-1TB SS...
41              HP 15-FD0647TU Ci5-1334U (8GB-512GB SSD)
42     HP OMNIBOOK ULTRA FLIP 14-FH0033DX ULTRA 9-288...
51            Lenovo ThinkBook16 - Ci5-1335U (8GB 512GB)
54     HP ENVY 14-ES1013DX 14th Gen Core 5 120U (8GB-...
59             Lenovo Thinkpad  T14 13th Gen Core I7 DOS
62     HP VICTUS 15-FB3093DX  R7-7445HS (16GB 512GB) ...
63      HP OMNIBOOK 14 FP0023DX Core 7 150U (16GB-512GB)
68                             LENOVO LOQ 15 Ci7 13650HX
70           HP 15S-FQ5000NIA Ci3-1215U (4GB, 256GB SSD)
71     Lenovo Legion 5 Ci7-14650HX (16GB-1TB SSD) RTX...
73     ASUS TUF GAMING F15-FX507VV Ci7-13620H (16GB-5...
74     ASUS TUF GAMING A14 FA-401WU RYZEN AI 9 HX370 ...
75     ASUS EXPERTBOOK B3402FBA Ci5 1235U (8GB-512GB ...
76     Asus ExpertBook B3402FVA Ci7 1355U (16GB-512GB...
79     HP 15 FD0647TU 13th Generation Ci5-1334U (8GB-...
80     HP OMNIBOOK X FLIP 16-AS0043DX ULTRA 9-288V (3...
87                Lenovo V15 G3-Ci5 12th (8GB 512GB SSD)
90         Lenovo ThinkBook 16 Ci3-1305U (8GB-512GB SSD)
92         Lenovo Thinkbook 14 14th Gen Core 7 8GB/512GB
99     HP ENVY x360 14 ES1023dx 14th Gen Core 7 (16GB...
100     HP Laptop 15-fd0356nia  Core™ i5 DOS (8GB-512GB)
102         Dell Latitude 3540 Ci5-1335U (8GB-256GB SSD)
103                     Dell Inspiron 14-7440 CORE7 150U
104    ASUS EXPERTBOOK B1503CVA Ci7 1355U (16GB-512GB...
107    HP OMEN 16-AE0073CL Ci7-14650HX (32GB - 1TB) R...
108    ASUS ROG STRIX G614J 13TH CI7 13650HX (32GB-1T...
115    LENOVO LEGION PRO 5 Ci9-14900HX (32GB-1TB SSD)...
117    ASUS TUF GAMING F17 FX707VU Ci7-13620H (16GB-5...
119    ASUS ROG STRIX G16 G615JMR Ci7 14650HX (16GB-1...
120    Asus Expertbook B1403CVA Ci7 13620H (16GB-1TB ...
121       Lenovo ThinkPad E14 G8 U5-225H (8GB-512GB SSD)
123    Acer Predator Helios Neo 16 AI PHN16-73-97SP G...
125    Asus VivoBook 15 x1504VA Ci5 1335U (8GB-512GB ...
126    Lenovo Legion 5 Ci9-14900HX (32GB-1TB SSD) RTX...
128    HP Victus 15-FA2209TX Ci7 14650HX (16GB-512GB ...
134    HP VICTUS 15-FA2093DX Ci7-13620H (16GB-1TB SSD...
136    ASUS EXPERTBOOK B1503CVA Ci5-1334U (16GB -512G...
137    ASUS TUF FX507VV-Ci7-13620H (16GB 1TB) RTX 406...
138      Lenovo Thinkbook 16 14th Core 7 (8GB-512GB SSD)
142             HP 15-FD0336TU Ci5-1334U (8GB-512GB SSD)
143    Dell Vostro 15 3530 Laptop Core™ i7-1355U (16G...
145                Lenovo Ideapad 5 13th Gen Core I7 DOS
146           Lenovo Thinkbook 15G2 11th Gen Core I7 D0S
153    Dell Inspiron 16 5640 Intel Core 7-150U (16GB-...
167    HP Victus 16-R0042NE Ci7-13700H (16GB-1TB SSD)...
168            Dell 15 DC15250 Ci5-1334U (8GB-512GB SSD)
177              Apple MacBook Pro 14.2” MTL83 (8GB-1TB)
178               Apple Macbook Pro 14 MTL73 (8GB-512GB)
182         LENOVO THINBOOK 16 13TH CI5 8GB/256GB 16INCH
185    HP VICTUS 15-FA2701WM Ci5-13420H (16GB -512GB)...
190    LENOVO LEGION PRO 5 Ci7-14650HX (16GB-1TB) RTX...
192    HP 15-FD0229NIA Ci7-1355U (8GB-512GB SSD) 15.6...
193          HP Elitebook 650 G10 13th Gen Core I5 1335U
194    ASUS EXPERTBOOK B1403CVA Ci7-1355U (16GB -512G...
197    Acer Nitro V15 - Ci5-13420H (16GB-512GB) RTX 4...
200    Dell Latitude 5440 13TH GEN CORE i7 1355U (8GB...
204      HP OMNIBOOK 14 FP0013DX Core 5 120U (8GB-512GB)
208                            LENOVO LOQ 15 Ci5 13450HX
211    HP VICTUS 15-FA2013DX Ci5-13420H (8GB 512GB SS...
212    HP VICTUS 15-FA2701WM Ci5-13420H (16GB-512GB S...
214    ASUS EXPERTBOOK B1403CVA Ci5 1334U (16GB-512GB...
215      Lenovo ThinkPad E14 G8 U7-255H (16GB-512GB SSD)
217    Dell Alienware Aurora 16 Core 7 240H (16GB-512...
220    Dell Alienware 16 Aurora Core 7-240H (32GB-1TB...
222    HP Victus 15-FA2317TX Ci7-13620H (16GB-512GB S...
232    HP VICTUS 16-R0003NIA Ci7-13700H (32GB -1TB SS...
233               ASUS ExpertBook B1 502CB 12th Ci5 235U
235           Dell Vostro 3530 Ci3-1305U (8GB-512GB SSD)
238    Acer Nitro V16 AMD RYZEN 7 8845HS (16GB-512GB ...
241          Dell 15 DC15250 Core 3-100U (8GB-512GB SSD)
252                            LENOVO LOQ 15 Ci5 12450HX
261    HP VICTUS 15-FB2082WM R5-8645HS (8GB-512GB SSD...
262           HP Spectre x360 14-EF2051TU 13th Gen 1355U
264    HP Victus 15-FB2146AX R7-8845HS (16GB-512GB SS...
267      HP Laptop 15S FQ5276NIA i3 12th Gen (4GB-256GB)
281    HP 250 G9 15.6 Inches 12th Gen core i5 DOS (8G...
Name: Name, dtype: object

In [14]:
# Known bare CPU model numbers that don't carry an explicit "i3/i5/i7/i9" or
# "Ci#" prefix in the listing title. Extend this table as new cases surface.
KNOWN_MODEL_MAP = {
    '1355U': 'Core i7',
}
 
# Apple internal model codes that appear in the title instead of "M1"-"M4"
# text (e.g. "MacBook Pro 14.2 MTL83"). Confirm against Apple's official
# model-number list before relying on this for reporting - these are the
# 2023 MacBook Pro 14" M3-family codes.
APPLE_MODEL_CODE_MAP = {
    'MTL73': 'M3',
    'MTL83': 'M3',
}
 
def extract_core(name: str):
    """
    Parse a CPU tier out of the Name column, formatted to match the existing
    Core column style exactly: 'Core i5', 'Ultra 7', 'Ryzen 9', 'M3', etc.
    (no 'Intel'/'AMD' prefix, no Apple Pro/Max/Ultra suffix).
    Returns None if no pattern is found.
    """
    if not isinstance(name, str):
        return None
    n = name.upper()
 
    # --- Apple Silicon -> 'M1'...'M4' (strip Pro/Max suffix to match style) ---
    if 'APPLE' in n or 'MACBOOK' in n:
        m = re.search(r'\bM([1-4])\b', n)
        if m:
            return f"M{m.group(1)}"
        for code, tier in APPLE_MODEL_CODE_MAP.items():
            if code in n:
                return tier
        return None
 
    # --- Intel Core Ultra: 'ULTRA 9-288V', 'U5-225H', 'U7-255H' -> 'Ultra 5/7/9' ---
    m = re.search(r'ULTRA\s*([579])', n)
    if m:
        return f"Ultra {m.group(1)}"
    m = re.search(r'\bU([579])-\d{3}[A-Z]\b', n)
    if m:
        return f"Ultra {m.group(1)}"
 
    # --- AMD Ryzen: 'R5-8645HS', 'RYZEN 7', 'RYZEN AI 9', 'R9-8940HX' -> 'Ryzen 3/5/7/9' ---
    m = re.search(r'RYZEN\s*(AI\s*)?([3579])', n)
    if m:
        ai = "AI " if m.group(1) else ""
        return f"Ryzen {ai}{m.group(2)}"
    m = re.search(r'\bR([3579])-\d{3,4}[A-Z]{1,3}\b', n)
    if m:
        return f"Ryzen {m.group(1)}"
 
    # --- Classic Intel Core i3/i5/i7/i9: 'Ci5-1335U', 'Core i7', 'I7' -> 'Core i3/5/7/9' ---
    m = re.search(r'\bC?I([3579])\b', n)
    if m:
        return f"Core i{m.group(1)}"
    m = re.search(r'CORE\s*[™]?\s*I([3579])', n)
    if m:
        return f"Core i{m.group(1)}"
 
    # --- New Intel 'Core 3/5/7' naming (post-2023 rebrand, no 'i') -> 'Core 3/5/7' ---
    m = re.search(r'CORE\s*[™]?\s*([357])\b', n)
    if m:
        return f"Core {m.group(1)}"
 
    # --- Bare known CPU model numbers (e.g. '1355U') with no prefix ---
    for code, tier in KNOWN_MODEL_MAP.items():
        if code in n:
            return tier
 
    return None
 
# Only fill where Core is currently null; never touch existing values or Name.
null_mask = Laptops_df['Core'].isna()
Laptops_df['Core_filled'] = Laptops_df['Core']
Laptops_df.loc[null_mask, 'Core_filled'] = Laptops_df.loc[null_mask, 'Name'].apply(extract_core)
 
filled_count = Laptops_df.loc[null_mask, 'Core_filled'].notna().sum()
still_null = Laptops_df.loc[null_mask, 'Core_filled'].isna().sum()
print(f"Filled: {filled_count} / {null_mask.sum()}")
print(f"Still null (manual review needed): {still_null}")
print()
print(Laptops_df.loc[null_mask & Laptops_df['Core_filled'].isna(), ['Name']].to_string())
print()
print("Value counts after fill:")
print(Laptops_df['Core_filled'].value_counts(dropna=False))

Filled: 86 / 87
Still null (manual review needed): 1

                                                                            Name
123  Acer Predator Helios Neo 16 AI PHN16-73-97SP Gaming Notebook (16GB-1TB SSD)

Value counts after fill:
Core_filled
Core i7         77
Core i5         63
Ultra 7         33
Core i3         18
Ultra 5         17
Ultra 9         14
Ryzen 5         12
M3              11
Ryzen 7          9
Core 7           8
Core i9          7
M4               6
Core 5           3
M2               2
M1               2
M0               2
Ryzen 9          2
Ryzen AI 9       1
Core i513420     1
None             1
Ryzen 3          1
Core 3           1
Name: count, dtype: int64

In [15]:
# Inspect rows with invalid core names to see their actual laptop names
invalid_cores = Laptops_df[Laptops_df['Core_filled'].isin(['M0', 'None'])]
invalid_cores[['Name', 'Brand', 'Core_filled']]

                                                 Name Brand Core_filled
33  HP OmniBook 14 FM0013DX Core Ultra 5 226V (16G...    Hp          M0
35  HP OmniBook X Flip 14-FM0023DX Core Ultra 7 25...    Hp          M0

In [16]:
# Specifically target the incorrect 'M0' extractions by index or name
Laptops_df.loc[33, 'Core_filled'] = 'Ultra 5'
Laptops_df.loc[35, 'Core_filled'] = 'Ultra 7'

# Map other generic incorrect values
core_mapping = {
    'Core i513420': 'Core i5',
    'None': None
}

Laptops_df['Core_filled'] = Laptops_df['Core_filled'].replace(core_mapping)

# Re-verify value counts
print(Laptops_df['Core_filled'].value_counts(dropna=False))

Core_filled
Core i7       77
Core i5       64
Ultra 7       34
Core i3       18
Ultra 5       18
Ultra 9       14
Ryzen 5       12
M3            11
Ryzen 7        9
Core 7         8
Core i9        7
M4             6
Core 5         3
M1             2
M2             2
Ryzen 9        2
Ryzen AI 9     1
None           1
Ryzen 3        1
Core 3         1
Name: count, dtype: int64

In [17]:
Laptops_df.head()

,Name,Discounted Price,Actual Price,Saving(%),Rating,Reviews,Brand,Core,SSD,Model,Core_filled
0,Apple MacBook Air 13 M1 MGN63 (8GB-256GB),203499.0,258000.0,21,5,2,Apple,M1,NaN,MacBook Air 13 M1 MGN63,M1
1,Apple Macbook Air 13 MW123 M4 Chip,281999.0,350000.0,19,4,5,Apple,M4,NaN,Macbook Air 13 MW123 M4 Chip,M4
2,ASUS Zenbook 14 UX3405CA Intel Core Ultra 7 25...,285999.0,330000.0,13,0,0,Asus,Ultra 7,16GB-512GB SSD,Zenbook 14 UX3405CA Intel Core Ultra 7 255H,Ultra 7
3,Lenovo ThinkPad E16 Gen 2 - Intel Core Ultra 7...,287999.0,340000.0,15,0,0,Lenovo,Ultra 7,NaN,ThinkPad E16 Gen 2 - Intel Core Ultra 7,Ultra 7
4,Lenovo IdeaPad Slim 3 Ryzen 7 (8GB-512GB),146999.0,175000.0,16,0,0,Lenovo,Ryzen 7,NaN,IdeaPad Slim 3 Ryzen 7,Ryzen 7

In [18]:
Laptops_df.isna().sum()

Name                  0
Discounted Price      0
Actual Price          0
Saving(%)             0
Rating                0
Reviews               0
Brand                 0
Core                 87
SSD                 203
Model                 0
Core_filled           1
dtype: int64

In [19]:
# 1. Manually resolve remaining null at index 123 (Acer Predator Helios Neo 16 AI has an Intel Core Ultra 9 275HX)
Laptops_df.loc[123, 'Core_filled'] = 'Ultra 9'

# 2. Correct the 'M0' extractions on HP OmniBook models
Laptops_df.loc[33, 'Core_filled'] = 'Ultra 5'
Laptops_df.loc[35, 'Core_filled'] = 'Ultra 7'

# 3. Clean remaining string typos
core_mapping = {
    'Core i513420': 'Core i5',
    'None': None
}
Laptops_df['Core_filled'] = Laptops_df['Core_filled'].replace(core_mapping)

# 4. Copy cleaned results to 'Core' and drop the temporary helper column
Laptops_df['Core'] = Laptops_df['Core_filled']
Laptops_df.drop(columns=['Core_filled'], inplace=True)

# 5. Verify there are zero nulls left in Core and check value counts
print("Null values remaining in Core:", Laptops_df['Core'].isna().sum())
print("\nFinal verified real-world Core counts:")
print(Laptops_df['Core'].value_counts(dropna=False))

Null values remaining in Core: 0

Final verified real-world Core counts:
Core
Core i7       77
Core i5       64
Ultra 7       34
Core i3       18
Ultra 5       18
Ultra 9       15
Ryzen 5       12
M3            11
Ryzen 7        9
Core 7         8
Core i9        7
M4             6
Core 5         3
M1             2
M2             2
Ryzen 9        2
Ryzen AI 9     1
Ryzen 3        1
Core 3         1
Name: count, dtype: int64

In [20]:
Laptops_df.isna().sum()

Name                  0
Discounted Price      0
Actual Price          0
Saving(%)             0
Rating                0
Reviews               0
Brand                 0
Core                  0
SSD                 203
Model                 0
dtype: int64

In [24]:
import re

def extract_ssd(name):
    if not isinstance(name, str):
        return None
    
    n = name.upper()
    
    # 1. Look for explicit TB patterns, e.g., '1TB' or '2TB'
    m_tb = re.search(r'\b([1-2])\s*TB\b', n)
    if m_tb:
        return f"{m_tb.group(1)}TB"
    
    # 2. Look for standard GB storage patterns (excluding RAM sizes like 4GB, 8GB, 16GB, 32GB)
    # Most SSD sizes are 128GB, 256GB, or 512GB
    m_gb = re.search(r'\b(128|256|512)\s*GB\b', n)
    if m_gb:
        return f"{m_gb.group(1)}GB"
    
    # 3. Handle cases where SSD sizes are written in a range format inside parentheses, e.g., (8GB-256GB)
    m_range = re.search(r'-\s*(128|256|512|1|2)\s*(GB|TB)', n)
    if m_range:
        return f"{m_range.group(1)}{m_range.group(2)}"
        
    return None

# Keep current values and fill missing ones using the Name column
null_mask = Laptops_df['SSD'].isna()
Laptops_df['SSD_filled'] = Laptops_df['SSD']
Laptops_df.loc[null_mask, 'SSD_filled'] = Laptops_df.loc[null_mask, 'Name'].apply(extract_ssd)

# Clean up any messy SSD formats that were already there (like '16GB-512GB SSD' -> '512GB')
def standard_ssd_clean(val):
    if not isinstance(val, str):
        return val
    val_upper = val.upper()
    if '1TB' in val_upper:
        return '1TB'
    if '512GB' in val_upper:
        return '512GB'
    if '256GB' in val_upper:
        return '256GB'
    if '128GB' in val_upper:
        return '128GB'
    return val

Laptops_df['SSD_filled'] = Laptops_df['SSD_filled'].apply(standard_ssd_clean)

# Print progress
filled_count = Laptops_df.loc[null_mask, 'SSD_filled'].notna().sum()
still_null = Laptops_df.loc[null_mask, 'SSD_filled'].isna().sum()
print(f"Filled: {filled_count} / {null_mask.sum()}")
print(f"Still null (manual review needed): {still_null}\n")

if still_null > 0:
    print(Laptops_df.loc[null_mask & Laptops_df['SSD_filled'].isna(), ['Name']])

Filled: 148 / 203
Still null (manual review needed): 55

                                                  Name
1                   Apple Macbook Air 13 MW123 M4 Chip
9               Lenovo IdeaPad Slim 3 Core i5 13th Gen
10           HP Probook 450 G10 Core i5 13th Gen 1335U
20           HP Probook 440 G10 13th Gen Core i5-1335U
21                 HP Envy 16 H1010TX Gen 13th Core i7
22      Dell Inspiron 14 7440 2 in 1 Intel Core 5 120U
23                   HP Elitebook 640 G11 Ultra 5 125U
34                           LENOVO LOQ 15 CI7-14650HX
56   HP Spectre 2-in-1 X360 16-F2013DX 13th Gen Cor...
57          Dell Vostro 15 3530 13th Gen Core i5 1334u
59           Lenovo Thinkpad  T14 13th Gen Core I7 DOS
60                     HP Probook 440 G11 Ultra 7 155u
68                           LENOVO LOQ 15 Ci7 13650HX
69                       LENOVO LOQ 15 Core i7 14650HX
83   HP ProBook 450 G9 15.6 Inches 12th Gen Core i5...
91                    Lenovo ThinkbooK 14 13th Core i5
93               Lenovo V15 G4 Core i5 13th Generation
103                   Dell Inspiron 14-7440 CORE7 150U
105                    HP PROBOOK 440 G11 Ultra 5 125u
112         HP 15S FC0298AU Notebook AMD Ryzen 5 7430U
129                      Apple Macbook Air 13 MW0W3 M4
135         Lenovo Ideapad Slim 3 13th Gen Core i3 DOS
145              Lenovo Ideapad 5 13th Gen Core I7 DOS
146         Lenovo Thinkbook 15G2 11th Gen Core I7 D0S
147             HP Probook 450 G9 12th Gen Core i7 DOS
148            HP Probook 440 G10 13th Gen Core i7 DOS
149       Dell Inspiron 15 3530 13th Gen Core i5 1334u
150              LENOVO LOQ 15 15IRX9 Core i5 13th Gen
151                    Apple MacBook Air MRXW3 M3 Chip
169                    Apple MacBook Air MC6T4 M4 Chip
181                     Lenovo V15 G4 Core i3 13th Gen
184                    HP 250 G10 13th Gen Core i3 DOS
186                    HP ProBook 460 G11 Ultra 7 155U
191                     HP 250 G9 12th Gen Core i7 DOS
193        HP Elitebook 650 G10 13th Gen Core I5 1335U
195                  HP Elitebook 660 G11 Ultra 5 125U
196             Apple MacBook Air MXCV3 M3 8-Core Chip
206                 Apple MacBook Air 15 MW1K3 M4 Chip
208                          LENOVO LOQ 15 Ci5 13450HX
223                      Apple Macbook Air 13 MW0Y3 M4
233             ASUS ExpertBook B1 502CB 12th Ci5 235U
234   Apple MacBook Air 15 Inches With M3 Chip (MRYV3)
236                 Apple Macbook Air 15 MC7C4 M4 Chip
249                   HP Envy 16 AC0013DX Ultra 5 125U
250           ASUS ZenBook 14 Q415MA Core Ultra 5 125H
252                          LENOVO LOQ 15 Ci5 12450HX
262         HP Spectre x360 14-EF2051TU 13th Gen 1355U
268        DELL Vostro 15 3520 Laptop 12th Gen Core i3
273  HP Envy x360 2 in 1 14 FC0023DX Core Ultra 7 L...
274           Asus Zenbook 14 Q425MA Core Ultra 7 155H
275   Apple MacBook Air 15 Inches With M3 Chip (MXD43)
282        DELL Vostro 15 3520 Laptop 12th Gen Core i5
284          Apple MACBOOK AIR 13” M3 CHIP MRXV3 8-256
288              Lenovo ThinkPad E14 Gen 4 Ryzen 5 DOS
289             Apple MacBook Air MRXN3 M3 8-Core Chip

In [23]:
# Run this ONLY if you have remaining nulls to manually set their capacities, e.g.:
Laptops_df.loc[1, 'SSD_filled'] = '512GB'

In [25]:
import re

def extract_ssd(name):
    if not isinstance(name, str):
        return None
    
    n = name.upper()
    
    # 1. Look for explicit SSD capacities in the laptop name (e.g., '1TB', '512GB', '256GB')
    m_tb = re.search(r'\b([1-2])\s*TB\b', n)
    if m_tb:
        return f"{m_tb.group(1)}TB"
        
    m_gb = re.search(r'\b(128|256|512)\s*GB\b', n)
    if m_gb:
        return f"{m_gb.group(1)}GB"
    
    # 2. Handle standard parenthetical configuration ranges (e.g., '(8-256)' or '(16GB-512GB)')
    m_range = re.search(r'-\s*(128|256|512|1|2)\s*(GB|TB)?', n)
    if m_range:
        num = m_range.group(1)
        unit = m_range.group(2) if m_range.group(2) else ("TB" if num in ['1', '2'] else "GB")
        return f"{num}{unit}"
        
    return None

# Only extract where SSD is currently NaN
null_mask = Laptops_df['SSD'].isna()
Laptops_df['SSD_filled'] = Laptops_df['SSD']
Laptops_df.loc[null_mask, 'SSD_filled'] = Laptops_df.loc[null_mask, 'Name'].apply(extract_ssd)

# 3. Clean and standardize format (e.g., '16GB-512GB SSD' -> '512GB')
def standard_ssd_clean(val):
    if not isinstance(val, str):
        return val
    v_upper = val.upper()
    if '1TB' in v_upper: return '1TB'
    if '2TB' in v_upper: return '2TB'
    if '512GB' in v_upper: return '512GB'
    if '256GB' in v_upper: return '256GB'
    if '128GB' in v_upper: return '128GB'
    return val

Laptops_df['SSD_filled'] = Laptops_df['SSD_filled'].apply(standard_ssd_clean)

# 4. Map the remaining specific indices to real-world base standards
# 256GB Base Models (Particularly 13-inch base Apple MacBooks)
base_256_indices = [1, 129, 151, 169, 223, 284]
Laptops_df.loc[base_256_indices, 'SSD_filled'] = '256GB'

# 512GB Base Models (Standard for modern Core i5/i7, Ultra 5/7, and 15-inch M4 MacBooks)
# Find any remaining null rows in our SSD helper and baseline them to standard 512GB
remaining_null_mask = Laptops_df['SSD_filled'].isna()
Laptops_df.loc[remaining_null_mask, 'SSD_filled'] = '512GB'

# 5. Overwrite back into the original column and clean up the helper
Laptops_df['SSD'] = Laptops_df['SSD_filled']
Laptops_df.drop(columns=['SSD_filled'], inplace=True)

# Final Verification
print("Missing SSD values remaining:", Laptops_df['SSD'].isna().sum())
print("\nFinal clean real-world SSD counts:")
print(Laptops_df['SSD'].value_counts())

Missing SSD values remaining: 0

Final clean real-world SSD counts:
SSD
512GB    206
1TB       55
256GB     24
2TB        6
Name: count, dtype: int64

In [26]:
Laptops_df.isna().sum()

Name                0
Discounted Price    0
Actual Price        0
Saving(%)           0
Rating              0
Reviews             0
Brand               0
Core                0
SSD                 0
Model               0
dtype: int64

In [27]:
Laptops_df.head(10)

,Name,Discounted Price,Actual Price,Saving(%),Rating,Reviews,Brand,Core,SSD,Model
0,Apple MacBook Air 13 M1 MGN63 (8GB-256GB),203499.0,258000.0,21,5,2,Apple,M1,256GB,MacBook Air 13 M1 MGN63
1,Apple Macbook Air 13 MW123 M4 Chip,281999.0,350000.0,19,4,5,Apple,M4,256GB,Macbook Air 13 MW123 M4 Chip
2,ASUS Zenbook 14 UX3405CA Intel Core Ultra 7 25...,285999.0,330000.0,13,0,0,Asus,Ultra 7,512GB,Zenbook 14 UX3405CA Intel Core Ultra 7 255H
3,Lenovo ThinkPad E16 Gen 2 - Intel Core Ultra 7...,287999.0,340000.0,15,0,0,Lenovo,Ultra 7,512GB,ThinkPad E16 Gen 2 - Intel Core Ultra 7
4,Lenovo IdeaPad Slim 3 Ryzen 7 (8GB-512GB),146999.0,175000.0,16,0,0,Lenovo,Ryzen 7,512GB,IdeaPad Slim 3 Ryzen 7
5,HP 250 G10 Ci3 N305 (8GB-512GB SSD),115999.0,144999.0,20,0,0,Hp,Core i3,512GB,250 G10 Ci3 N305
6,Dell Latitude 3540 Ci5-1335U (8GB-256GB SSD) 1...,169999.0,249999.0,32,5,1,Dell,Core i5,256GB,Latitude 3540 Ci5-1335U 15.6 FHD
7,Dell Latitude 15 5540 15.6 Inches 13th Gen Cor...,343999.0,415000.0,17,0,0,Dell,Core i7,512GB,Latitude 15 5540 15.6 Inches 13th Gen Core i7 DOS
8,Dell Latitude 15 3540 15.6 Inches 13th Gen Cor...,251999.0,320000.0,21,0,0,Dell,Core i7,512GB,Latitude 15 3540 15.6 Inches 13th Gen Core i7 DOS
9,Lenovo IdeaPad Slim 3 Core i5 13th Gen,134999.0,174999.0,23,5,2,Lenovo,Core i5,512GB,IdeaPad Slim 3 Core i5 13th Gen

In [29]:
for column in Laptops_df.columns :
    print(f'.....Value Counts in {column} :')
    print(Laptops_df[column].value_counts())
    print('\n')

.....Value Counts in Name :
Name
Apple MacBook Air 13 M1 MGN63 (8GB-256GB)                                                 1
HP OmniBook 5 16-AF1067ST Ultra 7-255U (16GB-1TB SSD)                                     1
LENOVO THINKPAD E14 G6 14TH Intel Core Ultra 7 155H (16GB-512GB SSD)                      1
Dell Latitude 5440 13TH GEN CORE i7 1355U (8GB-512GB SSD)                                 1
Acer Nitro V16 14th Gen Core i7 14650HX (16GB-512GB SSD)                                  1
Acer Nitro V15 - Ci5-13420H (16GB-512GB) RTX 4050 6GB                                     1
Apple MacBook Air MXCV3 M3 8-Core Chip                                                    1
HP Elitebook 660 G11 Ultra 5 125U                                                         1
ASUS EXPERTBOOK B1403CVA Ci7-1355U (16GB -512GB SSD)                                      1
HP Elitebook 650 G10 13th Gen Core I5 1335U                                               1
HP 15-FD0229NIA Ci7-1355U (8GB-512GB SSD) 15.6 FHD                                        1
HP 250 G9 12th Gen Core i7 DOS                                                            1
LENOVO LEGION PRO 5 Ci7-14650HX (16GB-1TB) RTX-4060-8GB                                   1
HP Elitebook 660 G11 U7 | Intel® Core™ Ultra 7 155U (8GB-512GB)                           1
HP EliteBook 640 G11 14 Ultra 7 155U (8GB-512GB)                                          1
HP ProBook 460 G11 Intel Core Ultra 5 125U (8GB-512GB)                                    1
HP ProBook 460 G11 Ultra 7 155U                                                           1
LENOVO THINKPAD T14 14TH GEN Intel Core Ultra 7 155U (16GB-512GB SSD)                     1
LENOVO THINKPAD T14 14TH GEN Intel Core Ultra 7 155U (32GB-512GB SSD)                     1
HP OMNIBOOK 14 FP0013DX Core 5 120U (8GB-512GB)                                           1
ACER PREDATOR HELIOS 16 AI Core Ultra 9 275HX (32GB-1TB SSD) RTX 5070Ti 12GB              1
Asus VivoBook 16 M1605YA Ryzen 7-7730U (8GB-512GB SSD)                                    1
Dell Latitude 3550 Ultra 5-125U (8GB-512GB SSD)                                           1
Dell Alienware Aurora 16 Core 7 240H (16GB-512GB SSD) RTX 5050 8GB                        1
Lenovo ThinkPad E16 G3 Ultra 5 225U (8GB-512GB SSD)                                       1
Lenovo ThinkPad E14 G8 U7-255H (16GB-512GB SSD)                                           1
ASUS EXPERTBOOK B1403CVA Ci5 1334U (16GB-512GB SSD)                                       1
HP VICTUS 15-FA2701WM Ci5-13420H (16GB-512GB SSD) RTX 4050 6GB                            1
Lenovo loq 15 13th Core i5 13450hx (24GB-512GB) DOS                                       1
HP VICTUS 15-FA2013DX Ci5-13420H (8GB 512GB SSD) RTX 3050 6GB                             1
Lenovo ThinkPad X1 Carbon G13 Ultra 7 256V (32GB-512GB SSD)                               1
HP OmniBook Ultra Flip 14-FH0030CA Core Ultra 7 256V (16GB 1TB SSD)                       1
LENOVO LOQ 15 Ci5 13450HX                                                                 1
Dell Latitude 3550 Raptor Lake 13th Gen Core i5 1335U (8GB-512GB SSD)                     1
Apple MacBook Air 15 MW1K3 M4 Chip                                                        1
HP VICTUS 15-FA2701WM Ci5-13420H (16GB -512GB) RTX-4050-6GB                               1
HP 250 G10 13th Gen Core i3 DOS                                                           1
Lenovo V15 G4 Core i7 13th Gen (8GB-512GB)                                                1
Lenovo ThinkPad E14 G6 Intel Core Ultra 5 125U (8GB-512GB SSD)                            1
Lenovo Yoga 9 Intel Core Ultra 7 (16GB-1TB SSD)                                           1
ASUS ExpertBook B1502CV 13th Gen Core i5 1355U (8GB-512GB SSD)                            1
Lenovo IdeaPad Slim 5 Core i7 13620H DOS (16GB-512GB SSD)                                 1
Lenovo IdeaPad Slim 3 Ryzen 3 7320U DOS (8GB-256GB SSD)                                   1
Apple Macbook Pro M3 A2918 (8GB-512GB SSD)                                                1
Acer Nitro V15 13th Gen Core i9 13900H (16GB-512GB SSD)                                   1
Lenovo Thinkbook 14 G7 14TH GEN Core Ultra 7 155H (8GB-512GB SSD)                         1
Lenovo Legion Pro 7 Ultra 9 275HX (64GB-2TB SSD) RTX 5090 24GB 240Hz                      1
Lenovo Thinkbook 14 G7 14th Gen Core Ultra 5 125U (8GB DDR5 512GB SSD)                    1
Dell Inspiron 16 5640 Intel Core 7-150U (16GB-1TB SSD)                                    1
Infinix GTBOOK 13th Generation Core i9 13900H 1TB-32GB                                    1
Apple MacBook Air MRXW3 M3 Chip                                                           1
LENOVO LOQ 15 15IRX9 Core i5 13th Gen                                                     1
Dell Inspiron 15 3530 13th Gen Core i5 1334u                                              1
Lenovo Legion Pro 7 Ultra 9 275HX (64GB-2TB SSD) RTX 5080 16GB 240Hz                      1
HP Victus 15-FB3093DX AMD Ryzen 7-7445H (16GB-512GB SSD) RTX 4050 6GB                     1
LENOVO THINBOOK 16 13TH CI5 8GB/256GB 16INCH                                              1
HP ProBook 440 G10 Core i7 (8GB-512GB NVMe SSD)                                           1
Lenovo V15 G4 Core i3 13th Gen                                                            1
HP Pavilion x360 14 EK1056TU  Core i7 (16GB-1TB)                                          1
HP 250 G10 Raptor Lake 13th Gen Core i7 (8GB-512GB)                                       1
Apple Macbook Pro 14 MTL73 (8GB-512GB)                                                    1
Apple MacBook Pro 14.2” MTL83 (8GB-1TB)                                                   1
Apple Macbook Pro MRX33 M3 Pro 14.2 (18GB-512GB)                                          1
Lenovo V15 G3 15.6 Inches 12th Gen Core i5 DOS (4GB - 256GB)                              1
HP Victus 16-R0042NE Ci7-13700H (16GB-1TB SSD) RTX™ 4060 8GB                              1
Lenovo V15 G3 15.6 Inches 12th Gen Core i7 DOS (8GB - 512GB)                              1
Lenovo ThinkPad E14 G4 14 Inches 12th Gen Core i5 DOS (8GB - 512GB)                       1
Lenovo V15 G3 15. 6 Inches 12th Gen Core i3 DOS (4GB - 256GB SSD)                         1
Lenovo LOQ 15 Ryzen 5 7235HS (12GB-512GB SSD) RTX 4050 6GB                                1
Apple MacBook Air MC6T4 M4 Chip                                                           1
Dell 15 DC15250 Ci5-1334U (8GB-512GB SSD)                                                 1
Dell Alienware 16 Aurora Core 7-240H (32GB-1TB SSD) RTX 5060 8GB                          1
HP Victus 15-FA2317TX Ci7-13620H (16GB-512GB SSD) RTX 4050 6GB                            1
HP Probook 450 G9 12th Gen Core i7 DOS                                                    1
Apple Macbook Air 13 MW0Y3 M4                                                             1
Apple MacBook Air 15 Inches With M3 Chip (MXD43)                                          1
Asus Zenbook 14 Q425MA Core Ultra 7 155H                                                  1
HP Envy x360 2 in 1 14 FC0023DX Core Ultra 7 Laptop                                       1
HP Envy 16-H1053DX 13th Gen Core i7-13700H (16GB-1TB)                                     1
HP 15s EQ2174AU 15.6 Inches Ryzen 5 (8GB-512GB)                                           1
HP 15-FB1000CA Ryzen 5 15.6 inches (16GB-1TB)                                             1
HP 15S-FQ5340TU Core i3 12th Gen (8GB-256GB)                                              1
DELL Vostro 15 3520 Laptop 12th Gen Core i3                                               1
HP Laptop 15S FQ5276NIA i3 12th Gen (4GB-256GB)                                           1
Infinix INBook Y1 Plus Laptop Core i3 (8GB-256GB SSD) International                       1
HP Victus 15-FB2146AX R7-8845HS (16GB-512GB SSD) RTX 4060 8GB                             1
Acer Predator Helios Neo PH16-72-903U Intel Core i9-14900HX (32GB-1TB SSD)                1
HP Spectre x360 14-EF2051TU 13th Gen 1355U                                                1
HP VICTUS 15-FB2082WM R5-8645HS (8GB-512GB SSD) RTX-4050-6GB                              1
HP 15S-EQ2315AU Laptop AMD Ryzen 7-5700U 8GB-512GB                                        1
Acer Predator Helios Neo PHN14-51-97X1 Intel Core Ultra 9-185H (32GB-1TB SSD)             1
Lenovo IdeaPad Slim 5 Core i5 13420H DOS (16GB-512GB SSD)                                 1
HP 15s FQ5099TU 15.6 Inches 12th Gen Core i7 Win 11 (8GB - 512GB)                         1
HP 15s FD0110TU - Raptor Lake - 13th Gen Core i7 (16GB-512GB)                             1
Acer Predator Helios Neo PH16-72-97T1 Intel Core i9-14900HX (32GB-1TB SSD)                1
Acer Predator Helios Neo PH16-72-99PA Intel Core i9-14900HX (32GB-1TB SSD)                1
Dell Inspiron 3535 AMD Ryzen 7-7730U (16GB-512GB SSD)                                     1
Dell Inspiron 15 3530 13th Gen Core i7 1355U (16GB-512GB SSD)                             1
Apple MacBook Air MRXN3 M3 8-Core Chip                                                    1
Lenovo ThinkPad E14 Gen 4 Ryzen 5 DOS                                                     1
HP Envy 2 in 1 16 AC0023dx Intel Core Ultra 7 155U Processor (16GB-1tb)                   1
Lenovo Ideapad 5 15.6 Inches 11th Gen Core i5 DOS (8GB - 512GB)                           1
HP Pavilion 15 EH3050au - AMD Ryzen 7 7730U Octa Core (16GB-1TB)                          1
Apple MACBOOK AIR 13” M3 CHIP MRXV3 8-256                                                 1
ASUS Expertbook B1402CVA 13th Gen Core i7 (16GB-512GB)                                    1
DELL Vostro 15 3520 Laptop 12th Gen Core i5                                               1
HP 250 G9 15.6 Inches 12th Gen core i5 DOS (8GB - 512GB)                                  1
Lenovo Ideapad 3 15.6 Inches 11th Gen Core i7 DOS (8GB - 1TB)                             1
HP Victus 15-FA0212TX Gaming Laptop 12th Gen Core i7-12650H (16GB-512GB)                  1
Dell Vostro 3520 12th Gen Core i5 15.6 inches (8GB-512GB)                                 1
HP 15s EQ2174AU AMD Ryzen 5 5500U (8GB 512GB)                                             1
Lenovo IdeaPad 5 Core i7 12th Gen (16GB-512GB)                                            1
Acer Nitro V15 13th Gen Core i7-13620H (16GB-512GB SSD) RTX 4060 8GB Graphics             1
Apple Macbook Air 15 MC7C4 M4 Chip                                                        1
Dell Vostro 3530 Ci3-1305U (8GB-512GB SSD)                                                1
Apple MacBook Air 15 Inches With M3 Chip (MRYV3)                                          1
ASUS ExpertBook B1 502CB 12th Ci5 235U                                                    1
HP VICTUS 16-R0003NIA Ci7-13700H (32GB -1TB SSD) RTX 4060 8GB                             1
HP 15 FD0336nia 13th Gen Core i3 (4GB-256GB)                                              1
HP OmniBook 5 16-AF1095CL Core Ultra 9 285H (32GB 1TB)                                    1
Apple MacBook Air 15.3 M2 MQKX3 (8GB-512GB)                                               1
Dell Inspiron 3520 Core i7 12th Gen (8GB-512GBSSD)                                        1
HP 15s FQ5098TU 15.6 Inches 12th Gen Core i5 Win 11 (8GB - 512GB)                         1
Apple MacBook Pro A2289 13 Inches Core i5 (8GB-512GB)                                     1
Infinix INBook X2 1065G7 14 Inches Core i7 (8GB RAM - 512GB SSD)                          1
Dell Inspiron 3515 15.6 inches AMD Ryzen 5 3450U (8GB - 256GB)                            1
Acer Nitro V16 AMD RYZEN 7 8845HS (16GB-512GB SSD)                                        1
HP EliteBook 840 G11 Ultra 7-155U vPro (16GB-512GB SSD)                                   1
HP 15S-FQ5299NIA Laptop 12th Gen Core i7 (8GB-512GB SSD)                                  1
HP Envy 16 AC0013DX Ultra 5 125U                                                          1
HP 15S-FQ5317TU Laptop 12th Gen Core i5 (8GB-512GB)                                       1
HP 15s FQ5096TU 15.6 Inches 12th Gen Core i3 Win 11 (4GB - 256GB)                         1
Infinix INBook X2 1035G1 14 Inches Core i5 (8GB RAM - 512GB SSD)                          1
LENOVO LOQ 15 Ci5 12450HX                                                                 1
Dell Inspiron 16 5640 Core i5-1334U (16GB-512GB SSD)                                      1
ASUS ZenBook 14 Q415MA Core Ultra 5 125H                                                  1
HP 15 FD0240TU 13th Gen Core i5 1334u (8GB-512GB)                                         1
Dell 15 DC15250 Core 3-100U (8GB-512GB SSD)                                               1
Dell Vostro 3520 12th Gen Core i3 15.6 inches (8GB-512GB)                                 1
HP Envy 14-ES0013DX 13th Gen Core i5-1335U (8GB DDR4-512GB SSD)                           1
HP 15-DY5131WM Laptop 12thGen Core i3 (8GB RAM, 256GB SSD)                                1
HP 15s FD0107TU 15.6 Inches 13th Gen Core i5 1335u Win 11 (8GB - 512GB)                   1
HP Pavilion 15 EH2032au 15.6 Inches AMD Ryzen 5 5625U Win 11 (16GB - 512GB)               1
HP Pavilion 15 EH2033au 15.6 Inches AMD Ryzen 7 5825U Win 11 (16GB - 1TB)                 1
HP Probook 440 G10 13th Gen Core i7 DOS                                                   1
Lenovo Thinkbook 15G2 11th Gen Core I7 D0S                                                1
Apple Macbook Air 13 MW123 M4 Chip                                                        1
ASUS TUF GAMING F15-FX507VV Ci7-13620H (16GB-512GB SSD) RTX 4060 8GB                      1
HP ProBook 440 G10 13th Gen Core i5 14 inches (8GB-512GB)                                 1
HP Spectre 14-EU0008NI Ultra 7 (16GB 1TB) Oled Plus HP PEN                                1
Lenovo ThinkBook16 - Ci5-1335U (8GB 512GB)                                                1
Apple MACBOOK AIR 13.6” M2 CHIP MLY43 8-512GB                                             1
Apple Macbook Pro MRX33 M3 Pro 14 (18GB-512GB) Black                                      1
HP Envy 16 H1008TX 16 Inches 13th Gen Core i5 Win 11 (16GB - 512GB)                       1
HP Pavilion 15 EG3002TX 15.6 Inches 13th Gen Core i5 Win 11 (8GB - 512GB)                 1
HP Pavilion X360 14 EK1055TU 14 Inches 13th Gen Core i5 Win 11 Home (8GB - 512GB)         1
HP Probook 450 G9 15.6 Inches 12th Gen Core i7 DOS (8GB - 512GB) Local                    1
Lenovo ThinkPad E15 G4 15.6 Inches 12th Gen Core i7 Backlit Keyboard DOS (8GB - 512GB)    1
HP Laptop EQ2180AU 15.6 Inches AMD Ryzen 5 (8GB RAM - 512GBSSD)                           1
HP OMNIBOOK ULTRA FLIP 14-FH0033DX ULTRA 9-288V (32GB-2TB SSD)                            1
HP 15-FD0647TU Ci5-1334U (8GB-512GB SSD)                                                  1
Lenovo Legion 5 16IAX10 Core Ultra 9-275HX (32GB-1TB SSD) RTX 5060 8GB                    1
Lenovo ThinkBook 16 G7 Ryzen 5-7533HS (16GB-512GB SSD)                                    1
HP ENVY 14-ES1013DX 14th Gen Core 5 120U (8GB-512GB SSD) x360 Touch                       1
Lenovo ThinkPad E14 G5 13th Gen Core i7 1355U (8GB-512GB)                                 1
HP Spectre 2-in-1 X360 16-F2013DX 13th Gen Core i7                                        1
Lenovo IdeaPad Slim 5 Ultra 7 155H (16GB-512GB) DOS                                       1
Lenovo Legion 5 Ci7-14650HX (16GB-1TB SSD) RTX 4050 6GB                                   1
HP 15S-FQ5000NIA Ci3-1215U (4GB, 256GB SSD)                                               1
LENOVO LOQ 15 Core i7 14650HX                                                             1
LENOVO LOQ 15 Ci7 13650HX                                                                 1
HP Laptop 15-FD0532NIA Intel Core i3-1315U 13th Gen (4GB-256GB)                           1
Lenovo loq 15 13th Core i7 13650hx (24GB-512GB) DOS                                       1
Lenovo IdeaPad Slim 5 Ultra 5 125H (16GB-512GB) DOS                                       1
Dell Vostro 15 3530 13th Gen Core i5 1334u                                                1
HP OMNIBOOK 14 FP0023DX Core 7 150U (16GB-512GB)                                          1
HP VICTUS 15-FB3093DX  R7-7445HS (16GB 512GB) RTX-4050-6GB                                1
Infinix INBOOK Y3H Plus (YL513H) Core i5 12450H (16GB - 512GB)                            1
HP Probook 440 G11 Ultra 7 155u                                                           1
Lenovo Thinkpad  T14 13th Gen Core I7 DOS                                                 1
Lenovo ThinkPad E16 Gen 2 - Intel Core Ultra 5 (8GB-512GB)                                1
ASUS TUF F16 FX608JMR Ci7 14650HX (32GB-1TB SSD) RTX 5060 8GB                             1
Lenovo Legion Pro 7 Ultra 9-275HX (32GB-2TB SSD) RTX 5070Ti 12GB 240Hz                    1
ASUS TUF GAMING F15-FX507VU Ci7-13620H (16GB-512GB SSD) RTX 4050 6GB                      1
Lenovo IdeaPad Slim 3 Core i5 13th Gen                                                    1
HP Spectre 16-AA0013dx Ultra 7 155U (16GB 1TB) 16WQXGA                                    1
HP OMEN 16-WD0073dx Ci7-13620H (16GB - 1TB) RTX-4060-8GB                                  1
HP 15s FQ2653TU 11th Gen  Core i7 (8GB-512GB)                                             1
Lenovo LOQ 15  Inches 13th Gen Core i7 (16GB - 512GB)                                     1
Lenovo ThinkPad E16 G1 14 Inches 13th Gen Core i7 (8GB - 512GB)                           1
HP Probook 450 G10 Core i5 13th Gen 1335U                                                 1
Dell Latitude 15 3540 15.6 Inches 13th Gen Core i7 DOS (8GB - 512GB)                      1
HP OMEN 16-AP0167AX R9-8940HX (16GB - 512GB) RTX-5060-8GB                                 1
Dell Latitude 15 5540 15.6 Inches 13th Gen Core i7 DOS (8GB - 512GB)                      1
Dell Latitude 3540 Ci5-1335U (8GB-256GB SSD) 15.6 FHD                                     1
HP 250 G10 Ci3 N305 (8GB-512GB SSD)                                                       1
Lenovo IdeaPad Slim 3 Ryzen 7 (8GB-512GB)                                                 1
Lenovo ThinkPad E16 Gen 2 - Intel Core Ultra 7 (16GB-512GB)                               1
ASUS Zenbook 14 UX3405CA Intel Core Ultra 7 255H (16GB-512GB SSD)                         1
HP ProBook 460 G11 Notebook PC | Intel® Core™ Ultra 7 Processor 155U (8GB-512GB)          1
Lenovo ThinkPad E14 Intel Core Ultra 5 (8GB-512GB)                                        1
HP OmniBook X Flip 14-FM0023DX Core Ultra 7 256V (16GB-1TB SSD)                           1
Acer Nitro V15 13th Gen Core i7-13620H (16GB-512GB SSD)                                   1
LENOVO LOQ 15 CI7-14650HX                                                                 1
HP OmniBook 14 FM0013DX Core Ultra 5 226V (16GB-512GB SSD)                                1
Dell Latitude 3550 Raptor Lake 13th Gen Core i7 1355U (8GB-512GB SSD)                     1
Lenovo legion 5 14th core i7 14650hx (16GB-1TB) DOS                                       1
LENOVO THINKPAD E14 G4 13TH GEN Intel Core I7 1355U (8GB-512GB SSD)                       1
DELL LATTITUDE 5550 14TH GEN Core Ultra 7 155U (8GB-512GB SSD)                            1
HP Probook 450 G10 Raptor Lake 13th Gen Core i5 1334U 8GB-512GB SSD                       1
HP 15-FD0499NIA Ci5-1334U (8GB 512GB SSD)                                                 1
Infinix INBOOK Air (XL442) Core i3 1215U (8GB - 256GB)                                    1
HP Spectre 14-EU0000 Ultra 7 (32GB, 2TB SSD) OLED Plus HP PEN                             1
HP Elitebook 640 G11 Ultra 5 125U                                                         1
Dell Inspiron 14 7440 2 in 1 Intel Core 5 120U                                            1
HP Envy 16 H1010TX Gen 13th Core i7                                                       1
HP Probook 440 G10 13th Gen Core i5-1335U                                                 1

In [30]:
for column in Laptops_df.columns :
    print(f'.....Describing {column} :')
    print(Laptops_df[column].describe())
    print('\n')

.....Describing Name :
count                                           291
unique                                          291
top       Apple MacBook Air 13 M1 MGN63 (8GB-256GB)
freq                                              1
Name: Name, dtype: object


.....Describing Discounted Price :
count    2.910000e+02
mean     2.789416e+05
std      1.737528e+05
min      8.599900e+04
25%      1.744990e+05
50%      2.349990e+05
75%      3.459990e+05
max      1.552999e+06
Name: Discounted Price, dtype: float64


.....Describing Actual Price :
count    2.910000e+02
mean     3.212616e+05
std      1.802598e+05
min      1.119990e+05
25%      2.000000e+05
50%      2.800000e+05
75%      3.800000e+05
max      1.599900e+06
Name: Actual Price, dtype: float64


.....Describing Saving(%) :
count    291.000000
mean      14.587629
std        8.008727
min        2.000000
25%        8.000000
50%       14.000000
75%       20.000000
max       45.000000
Name: Saving(%), dtype: float64


.....Describing Rating :
count    291.000000
mean       0.419244
std        1.352969
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        5.000000
Name: Rating, dtype: float64


.....Describing Reviews :
count    291.000000
mean       0.144330
std        0.569144
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        5.000000
Name: Reviews, dtype: float64


.....Describing Brand :
count     291
unique      7
top        Hp
freq      108
Name: Brand, dtype: object


.....Describing Core :
count         291
unique         19
top       Core i7
freq           77
Name: Core, dtype: object


.....Describing SSD :
count       291
unique        4
top       512GB
freq        206
Name: SSD, dtype: object


.....Describing Model :
count                                                  291
unique                                                 288
top       Thinkbook 15 G2 15.6 Inches 11th Gen Core i7 DOS
freq                                                     2
Name: Model, dtype: object

In [33]:
Laptops_df.to_csv('../data/interim/Laptops_Cleaned.csv', index=False)