In [2]:
import pandas as pd
pd.set_option('display.max_columns', 300)
pd.set_option('display.max_rows', 300)

In [4]:
Laptops_df = pd.read_csv('../data/interim/Laptops_Cleaned.csv')
Laptops_df.head(10)

,Name,Discounted Price,Actual Price,Saving(%),Rating,Reviews,Brand,Core,SSD,Model
0,Apple MacBook Air 13 M1 MGN63 (8GB-256GB),203499.0,258000.0,21,5,2,Apple,M1,256GB,MacBook Air 13 M1 MGN63
1,Apple Macbook Air 13 MW123 M4 Chip,281999.0,350000.0,19,4,5,Apple,M4,256GB,Macbook Air 13 MW123 M4 Chip
2,ASUS Zenbook 14 UX3405CA Intel Core Ultra 7 25...,285999.0,330000.0,13,0,0,Asus,Ultra 7,512GB,Zenbook 14 UX3405CA Intel Core Ultra 7 255H
3,Lenovo ThinkPad E16 Gen 2 - Intel Core Ultra 7...,287999.0,340000.0,15,0,0,Lenovo,Ultra 7,512GB,ThinkPad E16 Gen 2 - Intel Core Ultra 7
4,Lenovo IdeaPad Slim 3 Ryzen 7 (8GB-512GB),146999.0,175000.0,16,0,0,Lenovo,Ryzen 7,512GB,IdeaPad Slim 3 Ryzen 7
5,HP 250 G10 Ci3 N305 (8GB-512GB SSD),115999.0,144999.0,20,0,0,Hp,Core i3,512GB,250 G10 Ci3 N305
6,Dell Latitude 3540 Ci5-1335U (8GB-256GB SSD) 1...,169999.0,249999.0,32,5,1,Dell,Core i5,256GB,Latitude 3540 Ci5-1335U 15.6 FHD
7,Dell Latitude 15 5540 15.6 Inches 13th Gen Cor...,343999.0,415000.0,17,0,0,Dell,Core i7,512GB,Latitude 15 5540 15.6 Inches 13th Gen Core i7 DOS
8,Dell Latitude 15 3540 15.6 Inches 13th Gen Cor...,251999.0,320000.0,21,0,0,Dell,Core i7,512GB,Latitude 15 3540 15.6 Inches 13th Gen Core i7 DOS
9,Lenovo IdeaPad Slim 3 Core i5 13th Gen,134999.0,174999.0,23,5,2,Lenovo,Core i5,512GB,IdeaPad Slim 3 Core i5 13th Gen

In [41]:
# Laptops_df['Discounted Price'].value_counts()
# for value in Laptops_df['Discounted Price'] :
#     if value <= 150000.0:
#         print(f'{value} : <150K')
#         Laptops_df[['Price Band']] = '<150K'
#     elif 150000.0 <= value < 300000.0 : 
#         print(f'{value} : 150K - 300K')
#         Laptops_df['Price Band'] = '150K - 300K'
#     elif 300000.0 <= value <= 500000.0 : 
#         print(f'{value} : 300K - 500K')
#         Laptops_df['Price Band'] = '300K - 500K'
#     else : 
#         print(f'{value} : 500K+')
#         Laptops_df['Price Band'] = '500K+'

# Define the bin edges and the corresponding category labels
bins = [0, 150000, 300000, 500000, float('inf')]
labels = ['<150K', '150K - 300K', '300K - 500K', '500K+']

# Create the new column
Laptops_df['Price Band'] = pd.cut(Laptops_df['Actual Price'], bins=bins, labels=labels, right=False)

In [42]:
Laptops_df.head(10)

,Name,Discounted Price,Actual Price,Saving(%),Rating,Reviews,Brand,Core,SSD,Model,Price Band,Discount Amount,Processor Brand
0,Apple MacBook Air 13 M1 MGN63 (8GB-256GB),203499.0,258000.0,21,5,2,Apple,M1,256GB,MacBook Air 13 M1 MGN63,150K - 300K,54501.0,Apple
1,Apple Macbook Air 13 MW123 M4 Chip,281999.0,350000.0,19,4,5,Apple,M4,256GB,Macbook Air 13 MW123 M4 Chip,300K - 500K,68001.0,Apple
2,ASUS Zenbook 14 UX3405CA Intel Core Ultra 7 25...,285999.0,330000.0,13,0,0,Asus,Ultra 7,512GB,Zenbook 14 UX3405CA Intel Core Ultra 7 255H,300K - 500K,44001.0,Intel
3,Lenovo ThinkPad E16 Gen 2 - Intel Core Ultra 7...,287999.0,340000.0,15,0,0,Lenovo,Ultra 7,512GB,ThinkPad E16 Gen 2 - Intel Core Ultra 7,300K - 500K,52001.0,Intel
4,Lenovo IdeaPad Slim 3 Ryzen 7 (8GB-512GB),146999.0,175000.0,16,0,0,Lenovo,Ryzen 7,512GB,IdeaPad Slim 3 Ryzen 7,150K - 300K,28001.0,AMD
5,HP 250 G10 Ci3 N305 (8GB-512GB SSD),115999.0,144999.0,20,0,0,Hp,Core i3,512GB,250 G10 Ci3 N305,<150K,29000.0,Intel
6,Dell Latitude 3540 Ci5-1335U (8GB-256GB SSD) 1...,169999.0,249999.0,32,5,1,Dell,Core i5,256GB,Latitude 3540 Ci5-1335U 15.6 FHD,150K - 300K,80000.0,Intel
7,Dell Latitude 15 5540 15.6 Inches 13th Gen Cor...,343999.0,415000.0,17,0,0,Dell,Core i7,512GB,Latitude 15 5540 15.6 Inches 13th Gen Core i7 DOS,300K - 500K,71001.0,Intel
8,Dell Latitude 15 3540 15.6 Inches 13th Gen Cor...,251999.0,320000.0,21,0,0,Dell,Core i7,512GB,Latitude 15 3540 15.6 Inches 13th Gen Core i7 DOS,300K - 500K,68001.0,Intel
9,Lenovo IdeaPad Slim 3 Core i5 13th Gen,134999.0,174999.0,23,5,2,Lenovo,Core i5,512GB,IdeaPad Slim 3 Core i5 13th Gen,150K - 300K,40000.0,Intel

In [43]:
Laptops_df['Discount Amount'] = Laptops_df['Actual Price'] - Laptops_df['Discounted Price']
Laptops_df.head(10)

,Name,Discounted Price,Actual Price,Saving(%),Rating,Reviews,Brand,Core,SSD,Model,Price Band,Discount Amount,Processor Brand
0,Apple MacBook Air 13 M1 MGN63 (8GB-256GB),203499.0,258000.0,21,5,2,Apple,M1,256GB,MacBook Air 13 M1 MGN63,150K - 300K,54501.0,Apple
1,Apple Macbook Air 13 MW123 M4 Chip,281999.0,350000.0,19,4,5,Apple,M4,256GB,Macbook Air 13 MW123 M4 Chip,300K - 500K,68001.0,Apple
2,ASUS Zenbook 14 UX3405CA Intel Core Ultra 7 25...,285999.0,330000.0,13,0,0,Asus,Ultra 7,512GB,Zenbook 14 UX3405CA Intel Core Ultra 7 255H,300K - 500K,44001.0,Intel
3,Lenovo ThinkPad E16 Gen 2 - Intel Core Ultra 7...,287999.0,340000.0,15,0,0,Lenovo,Ultra 7,512GB,ThinkPad E16 Gen 2 - Intel Core Ultra 7,300K - 500K,52001.0,Intel
4,Lenovo IdeaPad Slim 3 Ryzen 7 (8GB-512GB),146999.0,175000.0,16,0,0,Lenovo,Ryzen 7,512GB,IdeaPad Slim 3 Ryzen 7,150K - 300K,28001.0,AMD
5,HP 250 G10 Ci3 N305 (8GB-512GB SSD),115999.0,144999.0,20,0,0,Hp,Core i3,512GB,250 G10 Ci3 N305,<150K,29000.0,Intel
6,Dell Latitude 3540 Ci5-1335U (8GB-256GB SSD) 1...,169999.0,249999.0,32,5,1,Dell,Core i5,256GB,Latitude 3540 Ci5-1335U 15.6 FHD,150K - 300K,80000.0,Intel
7,Dell Latitude 15 5540 15.6 Inches 13th Gen Cor...,343999.0,415000.0,17,0,0,Dell,Core i7,512GB,Latitude 15 5540 15.6 Inches 13th Gen Core i7 DOS,300K - 500K,71001.0,Intel
8,Dell Latitude 15 3540 15.6 Inches 13th Gen Cor...,251999.0,320000.0,21,0,0,Dell,Core i7,512GB,Latitude 15 3540 15.6 Inches 13th Gen Core i7 DOS,300K - 500K,68001.0,Intel
9,Lenovo IdeaPad Slim 3 Core i5 13th Gen,134999.0,174999.0,23,5,2,Lenovo,Core i5,512GB,IdeaPad Slim 3 Core i5 13th Gen,150K - 300K,40000.0,Intel

In [44]:
Laptops_df.loc[Laptops_df['Saving(%)'] == 0]

Empty DataFrame
Columns: [Name, Discounted Price, Actual Price, Saving(%), Rating, Reviews, Brand, Core, SSD, Model, Price Band, Discount Amount, Processor Brand]
Index: []

In [45]:
import numpy as np

Laptops_df['Processor Brand'] = 
    np.where(Laptops_df['Core'].str.contains('Ryzen', case=False, na=False), 'AMD',
    np.where(Laptops_df['Core'].str.contains('Core|Intel|Ultra', case=False, na=False), 'Intel',
    np.where(Laptops_df['Core'].str.contains('M1|M2|M3|M4', case=False, na=False), 'Apple', 'Other'))
)

In [46]:
Laptops_df.head(10)

,Name,Discounted Price,Actual Price,Saving(%),Rating,Reviews,Brand,Core,SSD,Model,Price Band,Discount Amount,Processor Brand
0,Apple MacBook Air 13 M1 MGN63 (8GB-256GB),203499.0,258000.0,21,5,2,Apple,M1,256GB,MacBook Air 13 M1 MGN63,150K - 300K,54501.0,Apple
1,Apple Macbook Air 13 MW123 M4 Chip,281999.0,350000.0,19,4,5,Apple,M4,256GB,Macbook Air 13 MW123 M4 Chip,300K - 500K,68001.0,Apple
2,ASUS Zenbook 14 UX3405CA Intel Core Ultra 7 25...,285999.0,330000.0,13,0,0,Asus,Ultra 7,512GB,Zenbook 14 UX3405CA Intel Core Ultra 7 255H,300K - 500K,44001.0,Intel
3,Lenovo ThinkPad E16 Gen 2 - Intel Core Ultra 7...,287999.0,340000.0,15,0,0,Lenovo,Ultra 7,512GB,ThinkPad E16 Gen 2 - Intel Core Ultra 7,300K - 500K,52001.0,Intel
4,Lenovo IdeaPad Slim 3 Ryzen 7 (8GB-512GB),146999.0,175000.0,16,0,0,Lenovo,Ryzen 7,512GB,IdeaPad Slim 3 Ryzen 7,150K - 300K,28001.0,AMD
5,HP 250 G10 Ci3 N305 (8GB-512GB SSD),115999.0,144999.0,20,0,0,Hp,Core i3,512GB,250 G10 Ci3 N305,<150K,29000.0,Intel
6,Dell Latitude 3540 Ci5-1335U (8GB-256GB SSD) 1...,169999.0,249999.0,32,5,1,Dell,Core i5,256GB,Latitude 3540 Ci5-1335U 15.6 FHD,150K - 300K,80000.0,Intel
7,Dell Latitude 15 5540 15.6 Inches 13th Gen Cor...,343999.0,415000.0,17,0,0,Dell,Core i7,512GB,Latitude 15 5540 15.6 Inches 13th Gen Core i7 DOS,300K - 500K,71001.0,Intel
8,Dell Latitude 15 3540 15.6 Inches 13th Gen Cor...,251999.0,320000.0,21,0,0,Dell,Core i7,512GB,Latitude 15 3540 15.6 Inches 13th Gen Core i7 DOS,300K - 500K,68001.0,Intel
9,Lenovo IdeaPad Slim 3 Core i5 13th Gen,134999.0,174999.0,23,5,2,Lenovo,Core i5,512GB,IdeaPad Slim 3 Core i5 13th Gen,150K - 300K,40000.0,Intel

In [47]:
Laptops_df.tail(10)

,Name,Discounted Price,Actual Price,Saving(%),Rating,Reviews,Brand,Core,SSD,Model,Price Band,Discount Amount,Processor Brand
281,HP Pavilion 15 EH3050au - AMD Ryzen 7 7730U Oc...,198499.0,245000.0,19,0,0,Hp,Ryzen 7,1TB,Pavilion 15 EH3050au - AMD Ryzen 7 7730U Octa ...,150K - 300K,46501.0,AMD
282,HP Envy 2 in 1 16 AC0023dx Intel Core Ultra 7 ...,251999.0,299000.0,16,0,0,Hp,Ultra 7,1TB,Envy 2 in 1 16 AC0023dx Intel Core Ultra 7 155...,150K - 300K,47001.0,Intel
283,HP 15s FD0110TU - Raptor Lake - 13th Gen Core ...,222999.0,270000.0,17,0,0,Hp,Core i7,512GB,15s FD0110TU - Raptor Lake - 13th Gen Core i7,150K - 300K,47001.0,Intel
284,Lenovo ThinkPad E14 Gen 4 Ryzen 5 DOS,141999.0,180000.0,21,0,0,Lenovo,Ryzen 5,512GB,ThinkPad E14 Gen 4 Ryzen 5 DOS,150K - 300K,38001.0,AMD
285,Apple MacBook Air MRXN3 M3 8-Core Chip,288999.0,300000.0,4,0,0,Apple,M3,512GB,MacBook Air MRXN3 M3 8-Core Chip,300K - 500K,11001.0,Apple
286,Dell Inspiron 15 3530 13th Gen Core i7 1355U (...,189999.0,219999.0,14,0,0,Dell,Core i7,512GB,Inspiron 15 3530 13th Gen Core i7 1355U,150K - 300K,30000.0,Intel
287,Dell Inspiron 3535 AMD Ryzen 7-7730U (16GB-512...,134499.0,142999.0,6,0,0,Dell,Ryzen 7,512GB,Inspiron 3535 AMD Ryzen 7-7730U,<150K,8500.0,AMD
288,Acer Predator Helios Neo PH16-72-99PA Intel Co...,430999.0,449999.0,4,0,0,Acer,Core i9,1TB,Predator Helios Neo PH16-72-99PA Intel Core i9...,300K - 500K,19000.0,Intel
289,Acer Predator Helios Neo PH16-72-97T1 Intel Co...,781999.0,950000.0,18,0,0,Acer,Core i9,1TB,Predator Helios Neo PH16-72-97T1 Intel Core i9...,500K+,168001.0,Intel
290,ASUS ROG Zephyrus G14 GA403UM Ryzen 9-270 (16G...,499999.0,550000.0,9,0,0,Asus,Ryzen 9,1TB,ROG Zephyrus G14 GA403UM Ryzen 9-270 RTX 5060...,500K+,50001.0,AMD

In [48]:
Laptops_df.to_csv('../data/processed/Final_Laptops_df.csv', index=False)