In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('../data/raw/students.csv', index_col='student_id')
df

,first_name,last_name,gender,email,department_id,cgpa
student_id,,,,,,
STU00000,Danielle,Johnson,Female,john21@example.net,DEP001,1.97
STU00001,Joy,Gardner,NaN,fjohnson@example.org,DEP002,2.58
STU00002,Jesse,Guzman,F,jennifermiles@example.com,DEP001,3.02
STU00003,Jeffrey,Lawrence,F,blakeerik@example.com,DEP002,2.59
STU00004,Matthew,Moore,Female,curtis61@example.com,DEP003,3.55
...,...,...,...,...,...,...
STU00995,Destiny,Myers,male,jessicachapman@example.org,DEP002,2.87
STU00996,April,Byrd,F,lawrencesmith@example.org,DEP004,3.78
STU00997,Marie,Smith,male,NaN,DEP002,4.05
STU00998,Connor,Garcia,male,ubell@example.com,DEP004,3.19
STU00999,Johnathan,Johnson,F,brownbrooke@example.org,DEP003,2.80

In [6]:
df.head(10)

,first_name,last_name,gender,email,department_id,cgpa
student_id,,,,,,
STU00000,Danielle,Johnson,Female,john21@example.net,DEP001,1.97
STU00001,Joy,Gardner,NaN,fjohnson@example.org,DEP002,2.58
STU00002,Jesse,Guzman,F,jennifermiles@example.com,DEP001,3.02
STU00003,Jeffrey,Lawrence,F,blakeerik@example.com,DEP002,2.59
STU00004,Matthew,Moore,Female,curtis61@example.com,DEP003,3.55
STU00004,Matthew,Moore,Female,curtis61@example.com,DEP003,3.55
STU00006,Christian,Carter,M,barbara10@example.net,DEP004,1.17
STU00007,Jeremy,Roberts,F,NaN,DEP003,2.58
STU00008,Christopher,Hall,NaN,jamesshawn@example.com,DEP003,2.03
STU00009,Francisco,Kelly,Male,jacqueline19@example.net,DEP003,2.49

In [7]:
df.tail(10)

,first_name,last_name,gender,email,department_id,cgpa
student_id,,,,,,
STU00990,Dawn,Campos,M,williamssteven@example.com,DEP002,2.19
STU00991,Kevin,Reese,F,noahthornton@example.com,DEP001,3.09
STU00992,Jose,Moreno,M,zsmith@example.com,DEP001,2.70
STU00993,Patrick,Stewart,NaN,davisamanda@example.com,DEP005,1.99
STU00994,Stephanie,Reynolds,Female,matthew41@example.com,DEP003,1.94
STU00995,Destiny,Myers,male,jessicachapman@example.org,DEP002,2.87
STU00996,April,Byrd,F,lawrencesmith@example.org,DEP004,3.78
STU00997,Marie,Smith,male,NaN,DEP002,4.05
STU00998,Connor,Garcia,male,ubell@example.com,DEP004,3.19
STU00999,Johnathan,Johnson,F,brownbrooke@example.org,DEP003,2.80

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, STU00000 to STU00999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   first_name     1000 non-null   object
 1   last_name      1000 non-null   object
 2   gender         824 non-null    object
 3   email          923 non-null    object
 4   department_id  1000 non-null   object
 5   cgpa           1000 non-null   float64
dtypes: float64(1), object(5)
memory usage: 54.7+ KB

In [9]:
df.describe()

              cgpa
count  1000.000000
mean      3.005170
std       0.715777
min       0.610000
25%       2.510000
50%       3.020000
75%       3.500000
max       5.000000

In [12]:
attendance_df = pd.read_csv('../data/raw/attendance.csv', index_col='attendance_id')
attendance_df

              student_id course_id lecture_date   status
attendance_id
ATT000000       STU00784    CRS010   2026-06-25     Late
ATT000001       STU00888    CRS003   2026-05-28   Absent
ATT000002       STU00096    CRS015   2026-06-03   Absent
ATT000003       STU00173    CRS010   2026-04-11  Present
ATT000004       STU00069    CRS009   2026-06-17     Late
...                  ...       ...          ...      ...
ATT004995       STU00129    CRS013   2026-04-01  Present
ATT004996       STU00764    CRS004   2026-04-13  Present
ATT004997       STU00589    CRS008   2026-05-04     Late
ATT004998       STU00081    CRS001   2026-06-24  Present
ATT004999       STU00981    CRS018   2026-05-31  Present

[5000 rows x 4 columns]

In [13]:
attendance_df.head(10)

              student_id course_id lecture_date   status
attendance_id
ATT000000       STU00784    CRS010   2026-06-25     Late
ATT000001       STU00888    CRS003   2026-05-28   Absent
ATT000002       STU00096    CRS015   2026-06-03   Absent
ATT000003       STU00173    CRS010   2026-04-11  Present
ATT000004       STU00069    CRS009   2026-06-17     Late
ATT000005       STU00372    CRS012   2026-04-12  Present
ATT000006       STU00072    CRS006   2026-05-30     Late
ATT000007       STU00790    CRS015   2026-06-20   Absent
ATT000008       STU00484    CRS009   2026-05-21   Absent
ATT000009       STU00665    CRS005   2026-06-27  Present

In [14]:
attendance_df.tail(10)

              student_id course_id lecture_date   status
attendance_id
ATT004990       STU00212    CRS008   2026-06-15   Absent
ATT004991       STU00091    CRS011   2026-05-30     Late
ATT004992       STU00516    CRS018   2026-06-18  Present
ATT004993       STU00772    CRS015   2026-04-04     Late
ATT004994       STU00012    CRS011   2026-05-28  Present
ATT004995       STU00129    CRS013   2026-04-01  Present
ATT004996       STU00764    CRS004   2026-04-13  Present
ATT004997       STU00589    CRS008   2026-05-04     Late
ATT004998       STU00081    CRS001   2026-06-24  Present
ATT004999       STU00981    CRS018   2026-05-31  Present

In [15]:
attendance_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, ATT000000 to ATT004999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student_id    5000 non-null   object
 1   course_id     5000 non-null   object
 2   lecture_date  5000 non-null   object
 3   status        5000 non-null   object
dtypes: object(4)
memory usage: 195.3+ KB

In [17]:
attendance_df.describe()

       student_id course_id lecture_date   status
count        5000      5000         5000     5000
unique        995        20           90        3
top      STU00921    CRS018   2026-06-27  Present
freq           14       277           74     1712

In [19]:
courses_df = pd.read_csv('../data/raw/courses.csv', index_col='course_id')
courses_df

          department_id                course_name  credits
course_id
CRS001           DEP001  Computer Science Course 1        4
CRS002           DEP001  Computer Science Course 2        2
CRS003           DEP001  Computer Science Course 3        2
CRS004           DEP001  Computer Science Course 4        4
CRS005           DEP002                IT Course 1        3
CRS006           DEP002                IT Course 2        2
CRS007           DEP002                IT Course 3        2
CRS008           DEP002                IT Course 4        2
CRS009           DEP003          Business Course 1        4
CRS010           DEP003          Business Course 2        2
CRS011           DEP003          Business Course 3        4
CRS012           DEP003          Business Course 4        4
CRS013           DEP004       Engineering Course 1        4
CRS014           DEP004       Engineering Course 2        2
CRS015           DEP004       Engineering Course 3        4
CRS016           DEP004       Engineering Course 4        3
CRS017           DEP005         Education Course 1        2
CRS018           DEP005         Education Course 2        2
CRS019           DEP005         Education Course 3        2
CRS020           DEP005         Education Course 4        2

In [21]:
courses_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, CRS001 to CRS020
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  20 non-null     object
 1   course_name    20 non-null     object
 2   credits        20 non-null     int64
dtypes: int64(1), object(2)
memory usage: 640.0+ bytes

In [22]:
courses_df.describe()

         credits
count  20.000000
mean    2.800000
std     0.951453
min     2.000000
25%     2.000000
50%     2.000000
75%     4.000000
max     4.000000

In [24]:
departments_df = pd.read_csv('../data/raw/departments.csv', index_col='department_id')
departments_df

                department_name
department_id
DEP001         Computer Science
DEP002                       IT
DEP003                 Business
DEP004              Engineering
DEP005                Education

In [26]:
enrollments_df = pd.read_csv('../data/raw/enrollments.csv', index_col='enrollment_id')
enrollments_df

              student_id course_id  score
enrollment_id
ENR000000       STU00993    CRS009     -4
ENR000001       STU00519    CRS008     60
ENR000002       STU00658    CRS013     41
ENR000003       STU00836    CRS008      0
ENR000004       STU00470    CRS015     92
...                  ...       ...    ...
ENR002995       STU00912    CRS013     20
ENR002996       STU00213    CRS020     67
ENR002997       STU00076    CRS005     62
ENR002998       STU00642    CRS016      2
ENR002999       STU00824    CRS001      8

[3000 rows x 3 columns]

In [27]:
enrollments_df.head(10)

              student_id course_id  score
enrollment_id
ENR000000       STU00993    CRS009     -4
ENR000001       STU00519    CRS008     60
ENR000002       STU00658    CRS013     41
ENR000003       STU00836    CRS008      0
ENR000004       STU00470    CRS015     92
ENR000005       STU00586    CRS015      1
ENR000006       STU00877    CRS016     47
ENR000007       STU00323    CRS004     53
ENR000008       STU00763    CRS001      3
ENR000009       STU00413    CRS014     -6

In [28]:
enrollments_df.tail(10)

              student_id course_id  score
enrollment_id
ENR002990       STU00528    CRS020     73
ENR002991       STU00535    CRS011     47
ENR002992       STU00804    CRS005     33
ENR002993       STU00297    CRS012     69
ENR002994       STU00876    CRS014     -5
ENR002995       STU00912    CRS013     20
ENR002996       STU00213    CRS020     67
ENR002997       STU00076    CRS005     62
ENR002998       STU00642    CRS016      2
ENR002999       STU00824    CRS001      8

In [29]:
enrollments_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3000 entries, ENR000000 to ENR002999
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  3000 non-null   object
 1   course_id   3000 non-null   object
 2   score       3000 non-null   int64
dtypes: int64(1), object(2)
memory usage: 93.8+ KB

In [30]:
enrollments_df.describe()

             score
count  3000.000000
mean     49.638000
std      35.052007
min     -10.000000
25%      18.000000
50%      50.000000
75%      80.000000
max     110.000000