In [2]:
import pandas as pd

# Cleaning Students Dataset.

In [3]:
students_df = pd.read_csv('../data/raw/students.csv', index_col='student_id')
students_df.head(10)

,first_name,last_name,gender,email,department_id,cgpa
student_id,,,,,,
STU00000,Danielle,Johnson,Female,john21@example.net,DEP001,1.97
STU00001,Joy,Gardner,NaN,fjohnson@example.org,DEP002,2.58
STU00002,Jesse,Guzman,F,jennifermiles@example.com,DEP001,3.02
STU00003,Jeffrey,Lawrence,F,blakeerik@example.com,DEP002,2.59
STU00004,Matthew,Moore,Female,curtis61@example.com,DEP003,3.55
STU00004,Matthew,Moore,Female,curtis61@example.com,DEP003,3.55
STU00006,Christian,Carter,M,barbara10@example.net,DEP004,1.17
STU00007,Jeremy,Roberts,F,NaN,DEP003,2.58
STU00008,Christopher,Hall,NaN,jamesshawn@example.com,DEP003,2.03
STU00009,Francisco,Kelly,Male,jacqueline19@example.net,DEP003,2.49

In [4]:
students_df.isnull().sum()

first_name         0
last_name          0
gender           176
email             77
department_id      0
cgpa               0
dtype: int64

In [5]:
students = students_df.dropna()

In [6]:
students.head(10)

,first_name,last_name,gender,email,department_id,cgpa
student_id,,,,,,
STU00000,Danielle,Johnson,Female,john21@example.net,DEP001,1.97
STU00002,Jesse,Guzman,F,jennifermiles@example.com,DEP001,3.02
STU00003,Jeffrey,Lawrence,F,blakeerik@example.com,DEP002,2.59
STU00004,Matthew,Moore,Female,curtis61@example.com,DEP003,3.55
STU00004,Matthew,Moore,Female,curtis61@example.com,DEP003,3.55
STU00006,Christian,Carter,M,barbara10@example.net,DEP004,1.17
STU00009,Francisco,Kelly,Male,jacqueline19@example.net,DEP003,2.49
STU00010,George,Daniel,Male,stevennelson@example.net,DEP001,2.44
STU00011,Hailey,Robinson,M,megan03@example.org,DEP003,3.53
STU00012,Linda,Morales,Female,clarksherri@example.net,DEP001,2.67

In [7]:
students.tail(10)

,first_name,last_name,gender,email,department_id,cgpa
student_id,,,,,,
STU00988,Mary,Mullins,Female,ptownsend@example.net,DEP005,2.10
STU00989,Scott,Walsh,F,beckywilkinson@example.org,DEP004,3.10
STU00990,Dawn,Campos,M,williamssteven@example.com,DEP002,2.19
STU00991,Kevin,Reese,F,noahthornton@example.com,DEP001,3.09
STU00992,Jose,Moreno,M,zsmith@example.com,DEP001,2.70
STU00994,Stephanie,Reynolds,Female,matthew41@example.com,DEP003,1.94
STU00995,Destiny,Myers,male,jessicachapman@example.org,DEP002,2.87
STU00996,April,Byrd,F,lawrencesmith@example.org,DEP004,3.78
STU00998,Connor,Garcia,male,ubell@example.com,DEP004,3.19
STU00999,Johnathan,Johnson,F,brownbrooke@example.org,DEP003,2.80

In [8]:
students.isnull().sum()

first_name       0
last_name        0
gender           0
email            0
department_id    0
cgpa             0
dtype: int64

In [9]:
students[students.duplicated()]

,first_name,last_name,gender,email,department_id,cgpa
student_id,,,,,,
STU00004,Matthew,Moore,Female,curtis61@example.com,DEP003,3.55

In [10]:
students.drop_duplicates(inplace=True)

C:\Users\admin\AppData\Local\Temp\ipykernel_56500\2394516557.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students.drop_duplicates(inplace=True)

In [11]:
students.duplicated().sum()

0

In [12]:
students.head(10)

,first_name,last_name,gender,email,department_id,cgpa
student_id,,,,,,
STU00000,Danielle,Johnson,Female,john21@example.net,DEP001,1.97
STU00002,Jesse,Guzman,F,jennifermiles@example.com,DEP001,3.02
STU00003,Jeffrey,Lawrence,F,blakeerik@example.com,DEP002,2.59
STU00004,Matthew,Moore,Female,curtis61@example.com,DEP003,3.55
STU00006,Christian,Carter,M,barbara10@example.net,DEP004,1.17
STU00009,Francisco,Kelly,Male,jacqueline19@example.net,DEP003,2.49
STU00010,George,Daniel,Male,stevennelson@example.net,DEP001,2.44
STU00011,Hailey,Robinson,M,megan03@example.org,DEP003,3.53
STU00012,Linda,Morales,Female,clarksherri@example.net,DEP001,2.67
STU00014,Douglas,Taylor,F,julie69@example.com,DEP005,3.12

In [13]:
students[['first_name','last_name','email']] = students[['first_name','last_name','email']].map(lambda column: column.strip())

C:\Users\admin\AppData\Local\Temp\ipykernel_56500\3141586106.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students[['first_name','last_name','email']] = students[['first_name','last_name','email']].map(lambda column: column.strip())

In [14]:
students[['first_name','last_name','email']].head(10)

           first_name last_name                      email
student_id
STU00000     Danielle   Johnson         john21@example.net
STU00002        Jesse    Guzman  jennifermiles@example.com
STU00003      Jeffrey  Lawrence      blakeerik@example.com
STU00004      Matthew     Moore       curtis61@example.com
STU00006    Christian    Carter      barbara10@example.net
STU00009    Francisco     Kelly   jacqueline19@example.net
STU00010       George    Daniel   stevennelson@example.net
STU00011       Hailey  Robinson        megan03@example.org
STU00012        Linda   Morales    clarksherri@example.net
STU00014      Douglas    Taylor        julie69@example.com

In [15]:
students['gender'] = students['gender'].str.replace(r'^(Female|female|f)$', 'F', regex=True)
students['gender'] = students['gender'].str.replace(r'^(male|Male|m)$', 'M', regex=True)

C:\Users\admin\AppData\Local\Temp\ipykernel_56500\1679328303.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students['gender'] = students['gender'].str.replace(r'^(Female|female|f)$', 'F', regex=True)
C:\Users\admin\AppData\Local\Temp\ipykernel_56500\1679328303.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students['gender'] = students['gender'].str.replace(r'^(male|Male|m)$', 'M', regex=True)

In [16]:
students.head(10)

,first_name,last_name,gender,email,department_id,cgpa
student_id,,,,,,
STU00000,Danielle,Johnson,F,john21@example.net,DEP001,1.97
STU00002,Jesse,Guzman,F,jennifermiles@example.com,DEP001,3.02
STU00003,Jeffrey,Lawrence,F,blakeerik@example.com,DEP002,2.59
STU00004,Matthew,Moore,F,curtis61@example.com,DEP003,3.55
STU00006,Christian,Carter,M,barbara10@example.net,DEP004,1.17
STU00009,Francisco,Kelly,M,jacqueline19@example.net,DEP003,2.49
STU00010,George,Daniel,M,stevennelson@example.net,DEP001,2.44
STU00011,Hailey,Robinson,M,megan03@example.org,DEP003,3.53
STU00012,Linda,Morales,F,clarksherri@example.net,DEP001,2.67
STU00014,Douglas,Taylor,F,julie69@example.com,DEP005,3.12

In [17]:
students.tail(15)

,first_name,last_name,gender,email,department_id,cgpa
student_id,,,,,,
STU00979,Taylor,Hunt,M,vberry@example.com,DEP003,3.25
STU00983,Lisa,Weber,M,todd28@example.org,DEP001,3.59
STU00984,Melissa,Ramirez,M,christinahill@example.com,DEP002,3.53
STU00985,Alexis,Rodriguez,F,reneestevenson@example.net,DEP004,3.46
STU00987,Lauren,Atkins,M,tracey29@example.org,DEP001,1.99
STU00988,Mary,Mullins,F,ptownsend@example.net,DEP005,2.10
STU00989,Scott,Walsh,F,beckywilkinson@example.org,DEP004,3.10
STU00990,Dawn,Campos,M,williamssteven@example.com,DEP002,2.19
STU00991,Kevin,Reese,F,noahthornton@example.com,DEP001,3.09
STU00992,Jose,Moreno,M,zsmith@example.com,DEP001,2.70
STU00994,Stephanie,Reynolds,F,matthew41@example.com,DEP003,1.94
STU00995,Destiny,Myers,M,jessicachapman@example.org,DEP002,2.87
STU00996,April,Byrd,F,lawrencesmith@example.org,DEP004,3.78
STU00998,Connor,Garcia,M,ubell@example.com,DEP004,3.19
STU00999,Johnathan,Johnson,F,brownbrooke@example.org,DEP003,2.80

In [18]:
students.to_csv('../data/interim/students_cleaned.csv')

# Cleaning Attendance Dataset

In [19]:
attendance_df = pd.read_csv('../data/raw/attendance.csv', index_col='attendance_id')
attendance_df.head(10)

              student_id course_id lecture_date   status
attendance_id
ATT000000       STU00784    CRS010   2026-06-25     Late
ATT000001       STU00888    CRS003   2026-05-28   Absent
ATT000002       STU00096    CRS015   2026-06-03   Absent
ATT000003       STU00173    CRS010   2026-04-11  Present
ATT000004       STU00069    CRS009   2026-06-17     Late
ATT000005       STU00372    CRS012   2026-04-12  Present
ATT000006       STU00072    CRS006   2026-05-30     Late
ATT000007       STU00790    CRS015   2026-06-20   Absent
ATT000008       STU00484    CRS009   2026-05-21   Absent
ATT000009       STU00665    CRS005   2026-06-27  Present

In [20]:
attendance_df.tail(10)

              student_id course_id lecture_date   status
attendance_id
ATT004990       STU00212    CRS008   2026-06-15   Absent
ATT004991       STU00091    CRS011   2026-05-30     Late
ATT004992       STU00516    CRS018   2026-06-18  Present
ATT004993       STU00772    CRS015   2026-04-04     Late
ATT004994       STU00012    CRS011   2026-05-28  Present
ATT004995       STU00129    CRS013   2026-04-01  Present
ATT004996       STU00764    CRS004   2026-04-13  Present
ATT004997       STU00589    CRS008   2026-05-04     Late
ATT004998       STU00081    CRS001   2026-06-24  Present
ATT004999       STU00981    CRS018   2026-05-31  Present

In [21]:
attendance_df.duplicated().sum()
attendance_df[attendance_df.duplicated()]

              student_id course_id lecture_date   status
attendance_id
ATT003685       STU00698    CRS009   2026-04-08     Late
ATT004549       STU00255    CRS002   2026-06-22  Present
ATT004565       STU00747    CRS004   2026-06-21   Absent

In [22]:
attendance = attendance_df.drop_duplicates()
attendance.duplicated().sum()

0

In [23]:
attendance.isnull().sum()

student_id      0
course_id       0
lecture_date    0
status          0
dtype: int64

In [24]:
attendance['lecture_date'].dtype

dtype('O')

In [25]:
attendance.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4997 entries, ATT000000 to ATT004999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student_id    4997 non-null   object
 1   course_id     4997 non-null   object
 2   lecture_date  4997 non-null   object
 3   status        4997 non-null   object
dtypes: object(4)
memory usage: 195.2+ KB

In [26]:
attendance['lecture_date'] = pd.to_datetime(attendance['lecture_date'])

C:\Users\admin\AppData\Local\Temp\ipykernel_56500\2465351733.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance['lecture_date'] = pd.to_datetime(attendance['lecture_date'])

In [27]:
attendance['lecture_date'].dtype

dtype('<M8[ns]')

In [28]:
attendance.head(10)

              student_id course_id lecture_date   status
attendance_id
ATT000000       STU00784    CRS010   2026-06-25     Late
ATT000001       STU00888    CRS003   2026-05-28   Absent
ATT000002       STU00096    CRS015   2026-06-03   Absent
ATT000003       STU00173    CRS010   2026-04-11  Present
ATT000004       STU00069    CRS009   2026-06-17     Late
ATT000005       STU00372    CRS012   2026-04-12  Present
ATT000006       STU00072    CRS006   2026-05-30     Late
ATT000007       STU00790    CRS015   2026-06-20   Absent
ATT000008       STU00484    CRS009   2026-05-21   Absent
ATT000009       STU00665    CRS005   2026-06-27  Present

In [29]:
attendance['course_id'].nunique()

20

In [30]:
attendance['status'].nunique()

3

In [31]:
attendance['status'].isin(['Late','Absent','Present']).value_counts()

status
True    4997
Name: count, dtype: int64

In [32]:
attendance.to_csv('../data/interim/attendance_cleaned.csv')

# Cleaning Enrollments Dataset.

In [33]:
enrollments_df = pd.read_csv('../data/raw/enrollments.csv', index_col='enrollment_id')
enrollments_df.head(10)

              student_id course_id  score
enrollment_id
ENR000000       STU00993    CRS009     -4
ENR000001       STU00519    CRS008     60
ENR000002       STU00658    CRS013     41
ENR000003       STU00836    CRS008      0
ENR000004       STU00470    CRS015     92
ENR000005       STU00586    CRS015      1
ENR000006       STU00877    CRS016     47
ENR000007       STU00323    CRS004     53
ENR000008       STU00763    CRS001      3
ENR000009       STU00413    CRS014     -6

In [34]:
enrollments_df.isnull().sum()

student_id    0
course_id     0
score         0
dtype: int64

In [35]:
enrollments_df.duplicated().sum()
enrollments_df[enrollments_df.duplicated()]

              student_id course_id  score
enrollment_id
ENR002112       STU00149    CRS005     50
ENR002978       STU00364    CRS005     79

In [36]:
enrollment = enrollments_df.drop_duplicates()
enrollment.duplicated().sum()

0

In [37]:
enrollment['student_id'].nunique()

949

In [38]:
enrollment['course_id'].nunique()

20

In [47]:
invalid_rows = enrollment[(enrollment['score'] < 0) | (enrollment['score'] > 100)].index
enrollment = enrollment.drop(invalid_rows)

In [48]:
enrollment.head(10)

              student_id course_id  score
enrollment_id
ENR000001       STU00519    CRS008     60
ENR000002       STU00658    CRS013     41
ENR000003       STU00836    CRS008      0
ENR000004       STU00470    CRS015     92
ENR000005       STU00586    CRS015      1
ENR000006       STU00877    CRS016     47
ENR000007       STU00323    CRS004     53
ENR000008       STU00763    CRS001      3
ENR000011       STU00845    CRS003     91
ENR000012       STU00618    CRS020     71

In [49]:
enrollment.describe()

             score
count  2528.000000
mean     49.493275
std      29.689528
min       0.000000
25%      23.000000
50%      49.000000
75%      76.000000
max     100.000000

In [50]:
enrollment.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2528 entries, ENR000001 to ENR002999
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  2528 non-null   object
 1   course_id   2528 non-null   object
 2   score       2528 non-null   int64
dtypes: int64(1), object(2)
memory usage: 79.0+ KB

In [51]:
enrollment.tail(10)

              student_id course_id  score
enrollment_id
ENR002989       STU00735    CRS006     54
ENR002990       STU00528    CRS020     73
ENR002991       STU00535    CRS011     47
ENR002992       STU00804    CRS005     33
ENR002993       STU00297    CRS012     69
ENR002995       STU00912    CRS013     20
ENR002996       STU00213    CRS020     67
ENR002997       STU00076    CRS005     62
ENR002998       STU00642    CRS016      2
ENR002999       STU00824    CRS001      8

In [52]:
enrollment.to_csv('../data/interim/enrollments_cleaned.csv')

## Merging and joining datasets

In [53]:
enrollment.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2528 entries, ENR000001 to ENR002999
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  2528 non-null   object
 1   course_id   2528 non-null   object
 2   score       2528 non-null   int64
dtypes: int64(1), object(2)
memory usage: 79.0+ KB

In [55]:
attendance.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4997 entries, ATT000000 to ATT004999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student_id    4997 non-null   object
 1   course_id     4997 non-null   object
 2   lecture_date  4997 non-null   datetime64[ns]
 3   status        4997 non-null   object
dtypes: datetime64[ns](1), object(3)
memory usage: 195.2+ KB

In [56]:
attendance.describe()

                        lecture_date
count                           4997
mean   2026-05-15 12:58:21.300780544
min              2026-04-01 00:00:00
25%              2026-04-23 00:00:00
50%              2026-05-15 00:00:00
75%              2026-06-07 00:00:00
max              2026-06-29 00:00:00

In [57]:
students.info()

<class 'pandas.core.frame.DataFrame'>
Index: 754 entries, STU00000 to STU00999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   first_name     754 non-null    object
 1   last_name      754 non-null    object
 2   gender         754 non-null    object
 3   email          754 non-null    object
 4   department_id  754 non-null    object
 5   cgpa           754 non-null    float64
dtypes: float64(1), object(5)
memory usage: 41.2+ KB

In [58]:
students.describe()

             cgpa
count  754.000000
mean     2.979894
std      0.713584
min      0.610000
25%      2.500000
50%      3.000000
75%      3.470000
max      5.000000

In [60]:
courses_df = pd.read_csv('../data/raw/courses.csv', index_col='course_id')
courses_df

          department_id                course_name  credits
course_id
CRS001           DEP001  Computer Science Course 1        4
CRS002           DEP001  Computer Science Course 2        2
CRS003           DEP001  Computer Science Course 3        2
CRS004           DEP001  Computer Science Course 4        4
CRS005           DEP002                IT Course 1        3
CRS006           DEP002                IT Course 2        2
CRS007           DEP002                IT Course 3        2
CRS008           DEP002                IT Course 4        2
CRS009           DEP003          Business Course 1        4
CRS010           DEP003          Business Course 2        2
CRS011           DEP003          Business Course 3        4
CRS012           DEP003          Business Course 4        4
CRS013           DEP004       Engineering Course 1        4
CRS014           DEP004       Engineering Course 2        2
CRS015           DEP004       Engineering Course 3        4
CRS016           DEP004       Engineering Course 4        3
CRS017           DEP005         Education Course 1        2
CRS018           DEP005         Education Course 2        2
CRS019           DEP005         Education Course 3        2
CRS020           DEP005         Education Course 4        2

In [62]:
courses_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, CRS001 to CRS020
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  20 non-null     object
 1   course_name    20 non-null     object
 2   credits        20 non-null     int64
dtypes: int64(1), object(2)
memory usage: 640.0+ bytes

In [63]:
departments_df = pd.read_csv('../data/raw/departments.csv', index_col='department_id')
departments_df

                department_name
department_id
DEP001         Computer Science
DEP002                       IT
DEP003                 Business
DEP004              Engineering
DEP005                Education

In [87]:
courses_df.groupby('department_id').size()

department_id
DEP001    4
DEP002    4
DEP003    4
DEP004    4
DEP005    4
dtype: int64

## Merging Departments and the coursesthey have

In [83]:
course_departments = courses_df.merge(departments_df, on='department_id', how='outer')
course_departments.set_index(['department_id','department_name', 'course_name'], inplace=True)

In [84]:
course_departments

                                                          credits
department_id department_name  course_name
DEP001        Computer Science Computer Science Course 1        4
                               Computer Science Course 2        2
                               Computer Science Course 3        2
                               Computer Science Course 4        4
DEP002        IT               IT Course 1                      3
                               IT Course 2                      2
                               IT Course 3                      2
                               IT Course 4                      2
DEP003        Business         Business Course 1                4
                               Business Course 2                2
                               Business Course 3                4
                               Business Course 4                4
DEP004        Engineering      Engineering Course 1             4
                               Engineering Course 2             2
                               Engineering Course 3             4
                               Engineering Course 4             3
DEP005        Education        Education Course 1               2
                               Education Course 2               2
                               Education Course 3               2
                               Education Course 4               2

In [203]:
course_departments.to_excel('../data/interim/departments_courses.xlsx')

In [90]:
students.head(5)

,first_name,last_name,gender,email,department_id,cgpa
student_id,,,,,,
STU00000,Danielle,Johnson,F,john21@example.net,DEP001,1.97
STU00002,Jesse,Guzman,F,jennifermiles@example.com,DEP001,3.02
STU00003,Jeffrey,Lawrence,F,blakeerik@example.com,DEP002,2.59
STU00004,Matthew,Moore,F,curtis61@example.com,DEP003,3.55
STU00006,Christian,Carter,M,barbara10@example.net,DEP004,1.17

In [91]:
enrollment.head(5)

              student_id course_id  score
enrollment_id
ENR000001       STU00519    CRS008     60
ENR000002       STU00658    CRS013     41
ENR000003       STU00836    CRS008      0
ENR000004       STU00470    CRS015     92
ENR000005       STU00586    CRS015      1

In [92]:
attendance.head(5)

              student_id course_id lecture_date   status
attendance_id
ATT000000       STU00784    CRS010   2026-06-25     Late
ATT000001       STU00888    CRS003   2026-05-28   Absent
ATT000002       STU00096    CRS015   2026-06-03   Absent
ATT000003       STU00173    CRS010   2026-04-11  Present
ATT000004       STU00069    CRS009   2026-06-17     Late

In [182]:
students_attendance = students.merge(attendance, on='student_id', how='outer')
students_attendance.head(10)

,student_id,first_name,last_name,gender,email,department_id,cgpa,course_id,lecture_date,status
0,STU00000,Danielle,Johnson,F,john21@example.net,DEP001,1.97,CRS010,2026-05-26,Absent
1,STU00000,Danielle,Johnson,F,john21@example.net,DEP001,1.97,CRS017,2026-04-18,Present
2,STU00000,Danielle,Johnson,F,john21@example.net,DEP001,1.97,CRS007,2026-05-16,Present
3,STU00000,Danielle,Johnson,F,john21@example.net,DEP001,1.97,CRS014,2026-04-17,Late
4,STU00000,Danielle,Johnson,F,john21@example.net,DEP001,1.97,CRS002,2026-06-17,Absent
5,STU00000,Danielle,Johnson,F,john21@example.net,DEP001,1.97,CRS003,2026-05-12,Present
6,STU00001,NaN,NaN,NaN,NaN,NaN,NaN,CRS016,2026-06-03,Present
7,STU00001,NaN,NaN,NaN,NaN,NaN,NaN,CRS015,2026-05-05,Late
8,STU00001,NaN,NaN,NaN,NaN,NaN,NaN,CRS015,2026-04-29,Present
9,STU00001,NaN,NaN,NaN,NaN,NaN,NaN,CRS002,2026-05-16,Present

In [183]:
students_attendance.isnull().sum()

student_id          0
first_name       1219
last_name        1219
gender           1219
email            1219
department_id    1219
cgpa             1219
course_id           2
lecture_date        2
status              2
dtype: int64

In [184]:
students_attendance.dropna(inplace=True)
students_attendance.head(10)

,student_id,first_name,last_name,gender,email,department_id,cgpa,course_id,lecture_date,status
0,STU00000,Danielle,Johnson,F,john21@example.net,DEP001,1.97,CRS010,2026-05-26,Absent
1,STU00000,Danielle,Johnson,F,john21@example.net,DEP001,1.97,CRS017,2026-04-18,Present
2,STU00000,Danielle,Johnson,F,john21@example.net,DEP001,1.97,CRS007,2026-05-16,Present
3,STU00000,Danielle,Johnson,F,john21@example.net,DEP001,1.97,CRS014,2026-04-17,Late
4,STU00000,Danielle,Johnson,F,john21@example.net,DEP001,1.97,CRS002,2026-06-17,Absent
5,STU00000,Danielle,Johnson,F,john21@example.net,DEP001,1.97,CRS003,2026-05-12,Present
10,STU00002,Jesse,Guzman,F,jennifermiles@example.com,DEP001,3.02,CRS016,2026-05-04,Present
11,STU00002,Jesse,Guzman,F,jennifermiles@example.com,DEP001,3.02,CRS007,2026-04-20,Late
12,STU00002,Jesse,Guzman,F,jennifermiles@example.com,DEP001,3.02,CRS006,2026-06-02,Late
13,STU00002,Jesse,Guzman,F,jennifermiles@example.com,DEP001,3.02,CRS019,2026-04-18,Present

In [176]:
students_attendance.isnull().sum()

student_id       0
first_name       0
last_name        0
gender           0
email            0
department_id    0
cgpa             0
course_id        0
lecture_date     0
status           0
dtype: int64

In [185]:
students_attendance.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3778 entries, 0 to 4998
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   student_id     3778 non-null   object
 1   first_name     3778 non-null   object
 2   last_name      3778 non-null   object
 3   gender         3778 non-null   object
 4   email          3778 non-null   object
 5   department_id  3778 non-null   object
 6   cgpa           3778 non-null   float64
 7   course_id      3778 non-null   object
 8   lecture_date   3778 non-null   datetime64[ns]
 9   status         3778 non-null   object
dtypes: datetime64[ns](1), float64(1), object(8)
memory usage: 324.7+ KB

In [178]:
students_attendance.describe()

              cgpa                   lecture_date
count  3778.000000                           3778
mean      2.992255  2026-05-15 07:11:27.983059968
min       0.610000            2026-04-01 00:00:00
25%       2.530000            2026-04-23 00:00:00
50%       3.010000            2026-05-14 00:00:00
75%       3.480000            2026-06-07 00:00:00
max       5.000000            2026-06-29 00:00:00
std       0.725001                            NaN

In [186]:
students_attendance.set_index(['student_id','first_name','last_name','gender','email','department_id','cgpa','course_id'], inplace=True)

In [187]:
students_attendance.head(20)

                                                                                              lecture_date  \
student_id first_name last_name gender email                     department_id cgpa course_id
STU00000   Danielle   Johnson   F      john21@example.net        DEP001        1.97 CRS010      2026-05-26
                                                                                    CRS017      2026-04-18
                                                                                    CRS007      2026-05-16
                                                                                    CRS014      2026-04-17
                                                                                    CRS002      2026-06-17
                                                                                    CRS003      2026-05-12
STU00002   Jesse      Guzman    F      jennifermiles@example.com DEP001        3.02 CRS016      2026-05-04
                                                                                    CRS007      2026-04-20
                                                                                    CRS006      2026-06-02
                                                                                    CRS019      2026-04-18
                                                                                    CRS002      2026-06-04
                                                                                    CRS002      2026-05-22
STU00003   Jeffrey    Lawrence  F      blakeerik@example.com     DEP002        2.59 CRS004      2026-05-11
                                                                                    CRS005      2026-05-03
                                                                                    CRS011      2026-04-29
                                                                                    CRS007      2026-05-27
                                                                                    CRS012      2026-06-25
                                                                                    CRS009      2026-06-27
                                                                                    CRS018      2026-04-30
                                                                                    CRS008      2026-04-04

                                                                                                status
student_id first_name last_name gender email                     department_id cgpa course_id
STU00000   Danielle   Johnson   F      john21@example.net        DEP001        1.97 CRS010      Absent
                                                                                    CRS017     Present
                                                                                    CRS007     Present
                                                                                    CRS014        Late
                                                                                    CRS002      Absent
                                                                                    CRS003     Present
STU00002   Jesse      Guzman    F      jennifermiles@example.com DEP001        3.02 CRS016     Present
                                                                                    CRS007        Late
                                                                                    CRS006        Late
                                                                                    CRS019     Present
                                                                                    CRS002      Absent
                                                                                    CRS002     Present
STU00003   Jeffrey    Lawrence  F      blakeerik@example.com     DEP002        2.59 CRS004     Present
                                                                                    CRS005     Present
                                                                                    CRS011     Present
                                                                                    CRS007        Late
                                                                                    CRS012      Absent
                                                                                    CRS009      Absent
                                                                                    CRS018        Late
                                                                                    CRS008      Absent

In [188]:
students_attendance.tail(20)

                                                                                               lecture_date  \
student_id first_name last_name gender email                      department_id cgpa course_id
STU00994   Stephanie  Reynolds  F      matthew41@example.com      DEP003        1.94 CRS011      2026-04-26
STU00995   Destiny    Myers     M      jessicachapman@example.org DEP002        2.87 CRS019      2026-06-20
                                                                                     CRS004      2026-04-08
                                                                                     CRS012      2026-05-31
                                                                                     CRS010      2026-05-26
STU00996   April      Byrd      F      lawrencesmith@example.org  DEP004        3.78 CRS013      2026-04-04
                                                                                     CRS008      2026-04-28
                                                                                     CRS007      2026-04-08
                                                                                     CRS016      2026-04-14
STU00998   Connor     Garcia    M      ubell@example.com          DEP004        3.19 CRS015      2026-04-16
                                                                                     CRS014      2026-06-08
                                                                                     CRS015      2026-05-12
                                                                                     CRS009      2026-05-08
                                                                                     CRS020      2026-05-28
                                                                                     CRS001      2026-04-16
STU00999   Johnathan  Johnson   F      brownbrooke@example.org    DEP003        2.80 CRS012      2026-06-18
                                                                                     CRS012      2026-05-14
                                                                                     CRS004      2026-05-08
                                                                                     CRS015      2026-04-29
                                                                                     CRS010      2026-05-22

                                                                                                 status
student_id first_name last_name gender email                      department_id cgpa course_id
STU00994   Stephanie  Reynolds  F      matthew41@example.com      DEP003        1.94 CRS011     Present
STU00995   Destiny    Myers     M      jessicachapman@example.org DEP002        2.87 CRS019      Absent
                                                                                     CRS004        Late
                                                                                     CRS012        Late
                                                                                     CRS010     Present
STU00996   April      Byrd      F      lawrencesmith@example.org  DEP004        3.78 CRS013     Present
                                                                                     CRS008      Absent
                                                                                     CRS007        Late
                                                                                     CRS016     Present
STU00998   Connor     Garcia    M      ubell@example.com          DEP004        3.19 CRS015        Late
                                                                                     CRS014        Late
                                                                                     CRS015     Present
                                                                                     CRS009      Absent
                                                                                     CRS020        Late
                                                                                     CRS001        Late
STU00999   Johnathan  Johnson   F      brownbrooke@example.org    DEP003        2.80 CRS012     Present
                                                                                     CRS012      Absent
                                                                                     CRS004        Late
                                                                                     CRS015     Present
                                                                                     CRS010      Absent

In [197]:
students_attendance[students_attendance.duplicated()].tail(20)

                                                                                               lecture_date  \
student_id first_name last_name gender email                      department_id cgpa course_id
STU00994   Stephanie  Reynolds  F      matthew41@example.com      DEP003        1.94 CRS011      2026-04-26
STU00995   Destiny    Myers     M      jessicachapman@example.org DEP002        2.87 CRS019      2026-06-20
                                                                                     CRS004      2026-04-08
                                                                                     CRS012      2026-05-31
                                                                                     CRS010      2026-05-26
STU00996   April      Byrd      F      lawrencesmith@example.org  DEP004        3.78 CRS013      2026-04-04
                                                                                     CRS008      2026-04-28
                                                                                     CRS007      2026-04-08
                                                                                     CRS016      2026-04-14
STU00998   Connor     Garcia    M      ubell@example.com          DEP004        3.19 CRS015      2026-04-16
                                                                                     CRS014      2026-06-08
                                                                                     CRS015      2026-05-12
                                                                                     CRS009      2026-05-08
                                                                                     CRS020      2026-05-28
                                                                                     CRS001      2026-04-16
STU00999   Johnathan  Johnson   F      brownbrooke@example.org    DEP003        2.80 CRS012      2026-06-18
                                                                                     CRS012      2026-05-14
                                                                                     CRS004      2026-05-08
                                                                                     CRS015      2026-04-29
                                                                                     CRS010      2026-05-22

                                                                                                 status
student_id first_name last_name gender email                      department_id cgpa course_id
STU00994   Stephanie  Reynolds  F      matthew41@example.com      DEP003        1.94 CRS011     Present
STU00995   Destiny    Myers     M      jessicachapman@example.org DEP002        2.87 CRS019      Absent
                                                                                     CRS004        Late
                                                                                     CRS012        Late
                                                                                     CRS010     Present
STU00996   April      Byrd      F      lawrencesmith@example.org  DEP004        3.78 CRS013     Present
                                                                                     CRS008      Absent
                                                                                     CRS007        Late
                                                                                     CRS016     Present
STU00998   Connor     Garcia    M      ubell@example.com          DEP004        3.19 CRS015        Late
                                                                                     CRS014        Late
                                                                                     CRS015     Present
                                                                                     CRS009      Absent
                                                                                     CRS020        Late
                                                                                     CRS001        Late
STU00999   Johnathan  Johnson   F      brownbrooke@example.org    DEP003        2.80 CRS012     Present
                                                                                     CRS012      Absent
                                                                                     CRS004        Late
                                                                                     CRS015     Present
                                                                                     CRS010      Absent

In [202]:
students_attendance.to_excel('../data/interim/students_attendance.xlsx')

## Merging Students and Enrollment

In [214]:
students_enrollment = students.merge(enrollment, on='student_id', how='outer')
students_enrollment.head(10)

,student_id,first_name,last_name,gender,email,department_id,cgpa,course_id,score
0,STU00000,Danielle,Johnson,F,john21@example.net,DEP001,1.97,CRS017,94.0
1,STU00000,Danielle,Johnson,F,john21@example.net,DEP001,1.97,CRS018,95.0
2,STU00001,NaN,NaN,NaN,NaN,NaN,NaN,CRS014,56.0
3,STU00002,Jesse,Guzman,F,jennifermiles@example.com,DEP001,3.02,CRS005,89.0
4,STU00002,Jesse,Guzman,F,jennifermiles@example.com,DEP001,3.02,CRS007,98.0
5,STU00003,Jeffrey,Lawrence,F,blakeerik@example.com,DEP002,2.59,CRS020,87.0
6,STU00004,Matthew,Moore,F,curtis61@example.com,DEP003,3.55,CRS011,21.0
7,STU00004,Matthew,Moore,F,curtis61@example.com,DEP003,3.55,CRS009,12.0
8,STU00004,Matthew,Moore,F,curtis61@example.com,DEP003,3.55,CRS018,54.0
9,STU00004,Matthew,Moore,F,curtis61@example.com,DEP003,3.55,CRS015,33.0

In [215]:
students_enrollment.dropna(inplace=True)

In [216]:
students_enrollment.tail(10)

,student_id,first_name,last_name,gender,email,department_id,cgpa,course_id,score
2572,STU00996,April,Byrd,F,lawrencesmith@example.org,DEP004,3.78,CRS014,95.0
2573,STU00996,April,Byrd,F,lawrencesmith@example.org,DEP004,3.78,CRS003,56.0
2577,STU00998,Connor,Garcia,M,ubell@example.com,DEP004,3.19,CRS006,58.0
2578,STU00998,Connor,Garcia,M,ubell@example.com,DEP004,3.19,CRS001,15.0
2579,STU00999,Johnathan,Johnson,F,brownbrooke@example.org,DEP003,2.80,CRS004,79.0
2580,STU00999,Johnathan,Johnson,F,brownbrooke@example.org,DEP003,2.80,CRS005,73.0
2581,STU00999,Johnathan,Johnson,F,brownbrooke@example.org,DEP003,2.80,CRS015,49.0
2582,STU00999,Johnathan,Johnson,F,brownbrooke@example.org,DEP003,2.80,CRS015,18.0
2583,STU00999,Johnathan,Johnson,F,brownbrooke@example.org,DEP003,2.80,CRS009,20.0
2584,STU00999,Johnathan,Johnson,F,brownbrooke@example.org,DEP003,2.80,CRS020,84.0

In [217]:
students_enrollment.isnull().sum()

student_id       0
first_name       0
last_name        0
gender           0
email            0
department_id    0
cgpa             0
course_id        0
score            0
dtype: int64

In [218]:
students_enrollment.set_index(['student_id','first_name','last_name','gender','email','department_id','cgpa','course_id'], inplace=True)

In [219]:
students_enrollment.head(5)

                                                                                               score
student_id first_name last_name gender email                     department_id cgpa course_id
STU00000   Danielle   Johnson   F      john21@example.net        DEP001        1.97 CRS017      94.0
                                                                                    CRS018      95.0
STU00002   Jesse      Guzman    F      jennifermiles@example.com DEP001        3.02 CRS005      89.0
                                                                                    CRS007      98.0
STU00003   Jeffrey    Lawrence  F      blakeerik@example.com     DEP002        2.59 CRS020      87.0

In [222]:
students_enrollment.to_excel('../data/interim/students_enrollment.xlsx')