In [1]:
import pandas as pd

In [4]:
#Cleaning students dataset
students_df = pd.read_csv('../data/raw/students.csv', index_col='student_id')
students_df.head(10)

,first_name,last_name,gender,email,department_id,cgpa
student_id,,,,,,
STU00000,Danielle,Johnson,Female,john21@example.net,DEP001,1.97
STU00001,Joy,Gardner,NaN,fjohnson@example.org,DEP002,2.58
STU00002,Jesse,Guzman,F,jennifermiles@example.com,DEP001,3.02
STU00003,Jeffrey,Lawrence,F,blakeerik@example.com,DEP002,2.59
STU00004,Matthew,Moore,Female,curtis61@example.com,DEP003,3.55
STU00004,Matthew,Moore,Female,curtis61@example.com,DEP003,3.55
STU00006,Christian,Carter,M,barbara10@example.net,DEP004,1.17
STU00007,Jeremy,Roberts,F,NaN,DEP003,2.58
STU00008,Christopher,Hall,NaN,jamesshawn@example.com,DEP003,2.03
STU00009,Francisco,Kelly,Male,jacqueline19@example.net,DEP003,2.49

In [3]:
students_df.isnull().sum()

first_name         0
last_name          0
gender           176
email             77
department_id      0
cgpa               0
dtype: int64

In [12]:
students = students_df.dropna()

In [13]:
students.head(10)

,first_name,last_name,gender,email,department_id,cgpa
student_id,,,,,,
STU00000,Danielle,Johnson,Female,john21@example.net,DEP001,1.97
STU00002,Jesse,Guzman,F,jennifermiles@example.com,DEP001,3.02
STU00003,Jeffrey,Lawrence,F,blakeerik@example.com,DEP002,2.59
STU00004,Matthew,Moore,Female,curtis61@example.com,DEP003,3.55
STU00004,Matthew,Moore,Female,curtis61@example.com,DEP003,3.55
STU00006,Christian,Carter,M,barbara10@example.net,DEP004,1.17
STU00009,Francisco,Kelly,Male,jacqueline19@example.net,DEP003,2.49
STU00010,George,Daniel,Male,stevennelson@example.net,DEP001,2.44
STU00011,Hailey,Robinson,M,megan03@example.org,DEP003,3.53
STU00012,Linda,Morales,Female,clarksherri@example.net,DEP001,2.67

In [14]:
students.tail(10)

,first_name,last_name,gender,email,department_id,cgpa
student_id,,,,,,
STU00988,Mary,Mullins,Female,ptownsend@example.net,DEP005,2.10
STU00989,Scott,Walsh,F,beckywilkinson@example.org,DEP004,3.10
STU00990,Dawn,Campos,M,williamssteven@example.com,DEP002,2.19
STU00991,Kevin,Reese,F,noahthornton@example.com,DEP001,3.09
STU00992,Jose,Moreno,M,zsmith@example.com,DEP001,2.70
STU00994,Stephanie,Reynolds,Female,matthew41@example.com,DEP003,1.94
STU00995,Destiny,Myers,male,jessicachapman@example.org,DEP002,2.87
STU00996,April,Byrd,F,lawrencesmith@example.org,DEP004,3.78
STU00998,Connor,Garcia,male,ubell@example.com,DEP004,3.19
STU00999,Johnathan,Johnson,F,brownbrooke@example.org,DEP003,2.80

In [15]:
students.isnull().sum()

first_name       0
last_name        0
gender           0
email            0
department_id    0
cgpa             0
dtype: int64

In [18]:
students[students.duplicated()]

,first_name,last_name,gender,email,department_id,cgpa
student_id,,,,,,
STU00004,Matthew,Moore,Female,curtis61@example.com,DEP003,3.55

In [21]:
students.drop_duplicates(inplace=True)

C:\Users\admin\AppData\Local\Temp\ipykernel_59568\2394516557.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students.drop_duplicates(inplace=True)

In [22]:
students.duplicated().sum()

0

In [42]:
students.head(10)

,first_name,last_name,gender,email,department_id,cgpa
student_id,,,,,,
STU00000,Danielle,Johnson,F,john21@example.net,DEP001,1.97
STU00002,Jesse,Guzman,F,jennifermiles@example.com,DEP001,3.02
STU00003,Jeffrey,Lawrence,F,blakeerik@example.com,DEP002,2.59
STU00004,Matthew,Moore,F,curtis61@example.com,DEP003,3.55
STU00006,Christian,Carter,M,barbara10@example.net,DEP004,1.17
STU00009,Francisco,Kelly,M,jacqueline19@example.net,DEP003,2.49
STU00010,George,Daniel,M,stevennelson@example.net,DEP001,2.44
STU00011,Hailey,Robinson,M,megan03@example.org,DEP003,3.53
STU00012,Linda,Morales,F,clarksherri@example.net,DEP001,2.67
STU00014,Douglas,Taylor,F,julie69@example.com,DEP005,3.12

In [31]:
students[['first_name','last_name','email']] = students[['first_name','last_name','email']].map(lambda column: column.strip())

C:\Users\admin\AppData\Local\Temp\ipykernel_59568\3141586106.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students[['first_name','last_name','email']] = students[['first_name','last_name','email']].map(lambda column: column.strip())

In [33]:
students[['first_name','last_name','email']].head(10)

           first_name last_name                      email
student_id
STU00000     Danielle   Johnson         john21@example.net
STU00002        Jesse    Guzman  jennifermiles@example.com
STU00003      Jeffrey  Lawrence      blakeerik@example.com
STU00004      Matthew     Moore       curtis61@example.com
STU00006    Christian    Carter      barbara10@example.net
STU00009    Francisco     Kelly   jacqueline19@example.net
STU00010       George    Daniel   stevennelson@example.net
STU00011       Hailey  Robinson        megan03@example.org
STU00012        Linda   Morales    clarksherri@example.net
STU00014      Douglas    Taylor        julie69@example.com

In [48]:
students['gender'] = students['gender'].str.replace(r'^(Female|female|f)$', 'F', regex=True)
students['gender'] = students['gender'].str.replace(r'^(male|Male|m)$', 'M', regex=True)

C:\Users\admin\AppData\Local\Temp\ipykernel_59568\1679328303.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students['gender'] = students['gender'].str.replace(r'^(Female|female|f)$', 'F', regex=True)
C:\Users\admin\AppData\Local\Temp\ipykernel_59568\1679328303.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students['gender'] = students['gender'].str.replace(r'^(male|Male|m)$', 'M', regex=True)

In [49]:
students.head(10)

,first_name,last_name,gender,email,department_id,cgpa
student_id,,,,,,
STU00000,Danielle,Johnson,F,john21@example.net,DEP001,1.97
STU00002,Jesse,Guzman,F,jennifermiles@example.com,DEP001,3.02
STU00003,Jeffrey,Lawrence,F,blakeerik@example.com,DEP002,2.59
STU00004,Matthew,Moore,F,curtis61@example.com,DEP003,3.55
STU00006,Christian,Carter,M,barbara10@example.net,DEP004,1.17
STU00009,Francisco,Kelly,M,jacqueline19@example.net,DEP003,2.49
STU00010,George,Daniel,M,stevennelson@example.net,DEP001,2.44
STU00011,Hailey,Robinson,M,megan03@example.org,DEP003,3.53
STU00012,Linda,Morales,F,clarksherri@example.net,DEP001,2.67
STU00014,Douglas,Taylor,F,julie69@example.com,DEP005,3.12

In [53]:
students.tail(15)

,first_name,last_name,gender,email,department_id,cgpa
student_id,,,,,,
STU00979,Taylor,Hunt,M,vberry@example.com,DEP003,3.25
STU00983,Lisa,Weber,M,todd28@example.org,DEP001,3.59
STU00984,Melissa,Ramirez,M,christinahill@example.com,DEP002,3.53
STU00985,Alexis,Rodriguez,F,reneestevenson@example.net,DEP004,3.46
STU00987,Lauren,Atkins,M,tracey29@example.org,DEP001,1.99
STU00988,Mary,Mullins,F,ptownsend@example.net,DEP005,2.10
STU00989,Scott,Walsh,F,beckywilkinson@example.org,DEP004,3.10
STU00990,Dawn,Campos,M,williamssteven@example.com,DEP002,2.19
STU00991,Kevin,Reese,F,noahthornton@example.com,DEP001,3.09
STU00992,Jose,Moreno,M,zsmith@example.com,DEP001,2.70
STU00994,Stephanie,Reynolds,F,matthew41@example.com,DEP003,1.94
STU00995,Destiny,Myers,M,jessicachapman@example.org,DEP002,2.87
STU00996,April,Byrd,F,lawrencesmith@example.org,DEP004,3.78
STU00998,Connor,Garcia,M,ubell@example.com,DEP004,3.19
STU00999,Johnathan,Johnson,F,brownbrooke@example.org,DEP003,2.80

In [54]:
students.to_csv('../data/interim/students_cleaned.csv')